<?php 
return array(
	'3' => array(
		'title' => 'asd',
		'fields' => 'aa',
		'url' => 'lookupGeneral',
		'mode' => 'a',
		'field' => NULL,
		'val' => 'a',
		'condition' => 'aa',
		'status' => '1',
		'level' => '15',
		'' => array(
		),
	),
	'4' => array(
		'title' => 'asd',
		'fields' => 'a,b,c,d',
		'url' => 'lookupGeneral',
		'mode' => 'a',
		'field' => NULL,
		'val' => 'b',
		'condition' => 'asd',
		'status' => '1',
		'level' => '15',
	),
	'5' => array(
		'title' => '1111',
		'fields' => 'a,b,c,d,e',
		'url' => 'lookupGeneral',
		'mode' => 'asdf',
		'filed' => 'a',
		'val' => 'a',
		'condition' => 'b',
		'status' => '1',
	),
	'6' => array(
		'title' => 'asd',
		'fields' => 'a,b,c,d,e',
		'url' => 'lookupGeneral',
		'mode' => 'wefrwe',
		'filed' => 'qe',
		'val' => 'wqe',
		'condition' => '_string,time > 15001254 ; satat,1',
		'status' => '1',
		'level' => '15',
	),
	'7' => array(
		'title' => '富商大贾',
		'fields' => 'q,q,q',
		'url' => 'lookupGeneral',
		'mode' => 'dsf',
		'filed' => 'a',
		'val' => 'b',
		'condition' => 'c',
		'status' => '0',
	),
);

?>