<?php 
return array(
	'1' => array(
		'title' => '测试修改',
		'fields' => 'id,orderno,deptid,dutylevelid,sumpeople,deptpeople',
		'fields_china' => array(
			'id' => 'ID',
			'orderno' => '申请编号',
			'deptid' => '申请部门',
			'dutylevelid' => '申请职级',
			'sumpeople' => '共增补人数',
			'deptpeople' => '部门现有人数',
		),
		'checkforfields' => '&#39;id&#39;=>&#39;ID&#39;,&#39;orderno&#39;=>&#39;申请编号&#39;,&#39;deptid&#39;=>&#39;申请部门&#39;,&#39;dutylevelid&#39;=>&#39;申请职级&#39;,&#39;sumpeople&#39;=>&#39;共增补人数&#39;,&#39;deptpeople&#39;=>&#39;部门现有人数&#39;',
		'fieldcom' => NULL,
		'listshowfields' => NULL,
		'listshowfields_china' => array(
		),
		'funccheck' => NULL,
		'funccheck_china' => array(
		),
		'funcinfo' => NULL,
		'url' => 'lookupGeneral',
		'mode' => 'MisHrPersonnelApplicationInfo',
		'checkformodel' => 'MisHrPersonnelApplicationInfo',
		'filed' => 'sumpeople',
		'filed1' => 'sumpeople',
		'val' => 'id',
		'showrules' => '(申请部门 包含 &#39;测试,测试2&#39;) 并且 (申请职级 包含 &#39;队长,班长,办事员&#39;)',
		'rulesinfo' => 'YToyOntzOjY6ImRlcHRpZCI7YToxOntpOjA7YTo2OntzOjQ6Im5hbWUiO3M6NjoiZGVwdGlkIjtzOjY6InN5bWJvbCI7czoxOiIzIjtzOjc6InNob3d2YWwiO3M6MTQ6Iua1i+ivlSzmtYvor5UyIjtzOjM6InZhbCI7YToyOntpOjA7czoyOiIyOSI7aToxO3M6MjoiMzAiO31zOjc6ImNvbnRyb2wiO3M6Njoic2VsZWN0IjtzOjY6IndpZGdldCI7czoxMzoicm9sZXRleHRpbnNldCI7fX1zOjExOiJkdXR5bGV2ZWxpZCI7YToxOntpOjA7YTo2OntzOjQ6Im5hbWUiO3M6MTE6ImR1dHlsZXZlbGlkIjtzOjY6InN5bWJvbCI7czoxOiIzIjtzOjc6InNob3d2YWwiO3M6MjM6IumYn+mVvyznj63plb8s5Yqe5LqL5ZGYIjtzOjM6InZhbCI7YTozOntpOjA7czoxOiI4IjtpOjE7czoxOiI5IjtpOjI7czoyOiIxMCI7fXM6NzoiY29udHJvbCI7czo2OiJzZWxlY3QiO3M6Njoid2lkZ2V0IjtzOjEzOiJyb2xldGV4dGluc2V0Ijt9fX0=',
		'rules' => 'deptid in(&#39;29,30&#39;)  and dutylevelid in(&#39;8,9,10&#39;)',
		'condition' => 'deptid in(&#39;29,30&#39;)  and dutylevelid in(&#39;8,9,10&#39;)',
		'status' => '1',
		'level' => '15',
	),
	'13' => array(
		'title' => '员工档案',
		'fields' => 'id,name',
		'fields_china' => array(
			'id' => '编号',
			'name' => '姓名',
		),
		'checkforfields' => '&#39;id&#39;=>&#39;编号&#39;,&#39;name&#39;=>&#39;姓名&#39;',
		'fieldcom' => NULL,
		'listshowfields' => NULL,
		'listshowfields_china' => array(
		),
		'funccheck' => NULL,
		'funccheck_china' => array(
		),
		'funcinfo' => NULL,
		'url' => 'lookupGeneral',
		'mode' => 'User',
		'checkformodel' => 'User',
		'filed' => 'name',
		'filed1' => NULL,
		'val' => 'id',
		'showrules' => '',
		'rulesinfo' => '',
		'rules' => '',
		'condition' => '',
		'status' => '1',
		'level' => '15',
	),
	'14' => array(
		'title' => '客户信息',
		'fields' => 'id,code,enterprisename',
		'fields_china' => array(
			'id' => 'ID',
			'code' => '客户代码',
			'enterprisename' => '客户名称',
		),
		'checkforfields' => NULL,
		'fieldcom' => NULL,
		'listshowfields' => NULL,
		'listshowfields_china' => array(
		),
		'funccheck' => NULL,
		'funccheck_china' => array(
		),
		'funcinfo' => false,
		'url' => 'lookupGeneral',
		'mode' => 'MisSalesCustomer',
		'checkformodel' => NULL,
		'filed' => 'enterprisename',
		'filed1' => NULL,
		'val' => 'id',
		'showrules' => NULL,
		'rulesinfo' => NULL,
		'rules' => NULL,
		'condition' => NULL,
		'status' => '1',
		'level' => NULL,
	),
	'15' => array(
		'title' => '客户基本信息',
		'fields' => 'name,linkman,linktel,id',
		'fields_china' => array(
			'name' => '客户名称',
			'linkman' => '联系人',
			'linktel' => '联系电话',
		),
		'checkforfields' => '&#39;name&#39;=>&#39;客户名称&#39;,&#39;linkman&#39;=>&#39;联系人&#39;,&#39;linktel&#39;=>&#39;联系电话&#39;,&#39;id&#39;=>&#39;编号&#39;',
		'fieldcom' => NULL,
		'listshowfields' => NULL,
		'listshowfields_china' => array(
		),
		'funccheck' => NULL,
		'funccheck_china' => array(
		),
		'funcinfo' => false,
		'url' => 'lookupGeneral',
		'mode' => 'MisAutoIgf',
		'checkformodel' => '',
		'filed' => 'name',
		'filed1' => 'name',
		'val' => NULL,
		'showrules' => '',
		'rulesinfo' => '',
		'rules' => '',
		'condition' => '',
		'status' => '1',
		'level' => '15',
	),
	'16' => array(
		'title' => 'LD行业档案',
		'fields' => 'orderno,name,id',
		'fields_china' => array(
			'orderno' => '编号',
			'name' => '名称',
		),
		'checkforfields' => '&#39;orderno&#39;=>&#39;编号&#39;,&#39;name&#39;=>&#39;名称&#39;,&#39;id&#39;=>&#39;编号&#39;',
		'fieldcom' => NULL,
		'listshowfields' => NULL,
		'listshowfields_china' => array(
		),
		'funccheck' => NULL,
		'funccheck_china' => array(
		),
		'funcinfo' => false,
		'url' => 'lookupGeneral',
		'mode' => 'MisAutoEjs',
		'checkformodel' => '',
		'filed' => 'name',
		'filed1' => 'name',
		'val' => NULL,
		'showrules' => '',
		'rulesinfo' => '',
		'rules' => '',
		'condition' => '',
		'status' => '1',
		'level' => '15',
	),
	'17' => array(
		'title' => '区域档案',
		'fields' => 'orderno,name,id',
		'fields_china' => array(
			'orderno' => '编号',
			'name' => '名称',
		),
		'checkforfields' => '&#39;orderno&#39;=>&#39;编号&#39;,&#39;name&#39;=>&#39;名称&#39;,&#39;id&#39;=>&#39;编号&#39;',
		'fieldcom' => NULL,
		'listshowfields' => NULL,
		'listshowfields_china' => array(
		),
		'funccheck' => NULL,
		'funccheck_china' => array(
		),
		'funcinfo' => false,
		'url' => 'lookupGeneral',
		'mode' => 'MisAutoMji',
		'checkformodel' => '',
		'filed' => 'name',
		'filed1' => 'name',
		'val' => NULL,
		'showrules' => '',
		'rulesinfo' => '',
		'rules' => '',
		'condition' => '',
		'status' => '1',
		'level' => '15',
	),
	'18' => array(
		'title' => 'LD金融机构档案',
		'fields' => 'jinrongjigoumingchen,orderno,id',
		'fields_china' => array(
			'jinrongjigoumingchen' => '金融机构名称',
			'orderno' => '编号',
		),
		'checkforfields' => '&#39;jinrongjigoumingchen&#39;=>&#39;金融机构名称&#39;,&#39;orderno&#39;=>&#39;编号&#39;,&#39;id&#39;=>&#39;编号&#39;',
		'fieldcom' => NULL,
		'listshowfields' => NULL,
		'listshowfields_china' => array(
		),
		'funccheck' => NULL,
		'funccheck_china' => array(
		),
		'funcinfo' => false,
		'url' => 'lookupGeneral',
		'mode' => 'MisAutoSft',
		'checkformodel' => '',
		'filed' => 'orderno',
		'filed1' => NULL,
		'val' => NULL,
		'showrules' => '',
		'rulesinfo' => '',
		'rules' => '',
		'condition' => '',
		'status' => '1',
		'level' => '15',
	),
	'19' => array(
		'title' => 'LD客户基本信息',
		'fields' => 'mingchen,orderno,id',
		'fields_china' => array(
			'mingchen' => '名称',
			'orderno' => '编号',
		),
		'checkforfields' => '&#39;mingchen&#39;=>&#39;名称&#39;,&#39;orderno&#39;=>&#39;编号&#39;,&#39;id&#39;=>&#39;编号&#39;',
		'fieldcom' => NULL,
		'listshowfields' => NULL,
		'listshowfields_china' => array(
		),
		'funccheck' => NULL,
		'funccheck_china' => array(
		),
		'funcinfo' => false,
		'url' => 'lookupGeneral',
		'mode' => 'MisAutoNyg',
		'checkformodel' => '',
		'filed' => 'mingchen',
		'filed1' => 'mingchen',
		'val' => NULL,
		'showrules' => '',
		'rulesinfo' => '',
		'rules' => '',
		'condition' => '',
		'status' => '1',
		'level' => '15',
	),
	'20' => array(
		'title' => 'LD客户信息综合参照',
		'fields' => 'mingchen,nashuihao',
		'fields_china' => array(
		),
		'checkforfields' => NULL,
		'fieldcom' => NULL,
		'listshowfields' => NULL,
		'listshowfields_china' => array(
		),
		'funccheck' => NULL,
		'funccheck_china' => array(
		),
		'funcinfo' => false,
		'url' => 'lookupGeneral',
		'mode' => '015',
		'checkformodel' => NULL,
		'filed' => '',
		'filed1' => NULL,
		'val' => '',
		'showrules' => NULL,
		'rulesinfo' => NULL,
		'rules' => NULL,
		'condition' => NULL,
		'status' => '1',
		'level' => '15',
	),
	'21' => array(
		'title' => 'LD客户信息综合参照',
		'fields' => 'customername,nashuihao',
		'fields_china' => array(
		),
		'checkforfields' => NULL,
		'fieldcom' => NULL,
		'listshowfields' => NULL,
		'listshowfields_china' => array(
		),
		'funccheck' => NULL,
		'funccheck_china' => array(
		),
		'funcinfo' => false,
		'url' => 'lookupGeneral',
		'mode' => '015',
		'checkformodel' => NULL,
		'filed' => 'customername',
		'filed1' => NULL,
		'val' => 'customername',
		'showrules' => NULL,
		'rulesinfo' => NULL,
		'rules' => NULL,
		'condition' => NULL,
		'status' => '1',
		'level' => '15',
	),
	'28' => array(
		'title' => '333',
		'fields' => '',
		'fields_china' => array(
		),
		'checkforfields' => NULL,
		'fieldcom' => NULL,
		'listshowfields' => NULL,
		'listshowfields_china' => array(
		),
		'funccheck' => NULL,
		'funccheck_china' => array(
		),
		'funcinfo' => false,
		'url' => 'lookupGeneral',
		'mode' => '1222',
		'checkformodel' => NULL,
		'filed' => '',
		'filed1' => NULL,
		'val' => '',
		'showrules' => NULL,
		'rulesinfo' => NULL,
		'rules' => NULL,
		'condition' => NULL,
		'status' => '1',
		'level' => '15',
	),
	'22' => array(
		'title' => '344',
		'fields' => '',
		'fields_china' => array(
		),
		'checkforfields' => NULL,
		'fieldcom' => NULL,
		'listshowfields' => NULL,
		'listshowfields_china' => array(
		),
		'funccheck' => NULL,
		'funccheck_china' => array(
		),
		'funcinfo' => false,
		'url' => 'lookupGeneral',
		'mode' => '33',
		'checkformodel' => NULL,
		'filed' => '',
		'filed1' => NULL,
		'val' => '',
		'showrules' => NULL,
		'rulesinfo' => NULL,
		'rules' => NULL,
		'condition' => NULL,
		'status' => '1',
		'level' => '15',
	),
	'23' => array(
		'title' => '232323',
		'fields' => '',
		'fields_china' => array(
		),
		'checkforfields' => NULL,
		'fieldcom' => NULL,
		'listshowfields' => NULL,
		'listshowfields_china' => array(
		),
		'funccheck' => NULL,
		'funccheck_china' => array(
		),
		'funcinfo' => false,
		'url' => 'lookupGeneral',
		'mode' => '323',
		'checkformodel' => NULL,
		'filed' => '',
		'filed1' => NULL,
		'val' => '',
		'showrules' => NULL,
		'rulesinfo' => NULL,
		'rules' => NULL,
		'condition' => NULL,
		'status' => '1',
		'level' => '15',
	),
	'24' => array(
		'title' => '444',
		'fields' => '',
		'fields_china' => array(
		),
		'checkforfields' => NULL,
		'fieldcom' => NULL,
		'listshowfields' => NULL,
		'listshowfields_china' => array(
		),
		'funccheck' => NULL,
		'funccheck_china' => array(
		),
		'funcinfo' => false,
		'url' => 'lookupGeneral',
		'mode' => '333',
		'checkformodel' => NULL,
		'filed' => '',
		'filed1' => NULL,
		'val' => '',
		'showrules' => NULL,
		'rulesinfo' => NULL,
		'rules' => NULL,
		'condition' => NULL,
		'status' => '1',
		'level' => '15',
	),
	'25' => array(
		'title' => '计量单位参照',
		'fields' => 'zhudanwei,huansuanlv,fudanwei,id',
		'fields_china' => array(
			'zhudanwei' => '主单位',
			'huansuanlv' => '换算率',
			'fudanwei' => '辅单位',
		),
		'checkforfields' => '&#39;zhudanwei&#39;=>&#39;主单位&#39;,&#39;huansuanlv&#39;=>&#39;换算率&#39;,&#39;fudanwei&#39;=>&#39;辅单位&#39;,&#39;id&#39;=>&#39;编号&#39;',
		'fieldcom' => NULL,
		'listshowfields' => NULL,
		'listshowfields_china' => array(
		),
		'funccheck' => NULL,
		'funccheck_china' => array(
		),
		'funcinfo' => false,
		'url' => 'lookupGeneral',
		'mode' => 'MisAutoIqe',
		'checkformodel' => '',
		'filed' => 'zhudanwei',
		'filed1' => 'zhudanwei',
		'val' => NULL,
		'showrules' => '',
		'rulesinfo' => '',
		'rules' => '',
		'condition' => '',
		'status' => '1',
		'level' => '15',
	),
	'26' => array(
		'title' => '企业资产负债表项目参照',
		'fields' => 'zhanghufangxiang,orderno,name,id',
		'fields_china' => array(
			'zhanghufangxiang' => '账户方向',
			'orderno' => '编号',
			'name' => '名称',
		),
		'checkforfields' => '&#39;zhanghufangxiang&#39;=>&#39;账户方向&#39;,&#39;orderno&#39;=>&#39;编号&#39;,&#39;name&#39;=>&#39;名称&#39;,&#39;id&#39;=>&#39;编号&#39;',
		'fieldcom' => NULL,
		'listshowfields' => NULL,
		'listshowfields_china' => array(
		),
		'funccheck' => NULL,
		'funccheck_china' => array(
		),
		'funcinfo' => false,
		'url' => 'lookupGeneral',
		'mode' => 'MisAutoObt',
		'checkformodel' => '',
		'filed' => 'name',
		'filed1' => NULL,
		'val' => NULL,
		'showrules' => '',
		'rulesinfo' => '',
		'rules' => '',
		'condition' => '',
		'status' => '1',
		'level' => '15',
	),
	'27' => array(
		'title' => 'LD行业(标准)',
		'fields' => 'orderno,pid,name,id',
		'fields_china' => array(
			'orderno' => '编号',
			'pid' => '所属行业',
			'name' => '行业名称',
		),
		'checkforfields' => '&#39;orderno&#39;=>&#39;编号&#39;,&#39;pid&#39;=>&#39;所属行业&#39;,&#39;name&#39;=>&#39;行业名称&#39;,&#39;id&#39;=>&#39;编号&#39;',
		'fieldcom' => NULL,
		'listshowfields' => NULL,
		'listshowfields_china' => array(
		),
		'funccheck' => NULL,
		'funccheck_china' => array(
		),
		'funcinfo' => false,
		'url' => 'lookupGeneral',
		'mode' => 'MisSaleProfession',
		'checkformodel' => '',
		'filed' => 'name',
		'filed1' => NULL,
		'val' => NULL,
		'showrules' => '',
		'rulesinfo' => '',
		'rules' => '',
		'condition' => '',
		'status' => '1',
		'level' => '15',
	),
	'fbc8848c1c1bf663928a8d396d550879' => array(
		'title' => '2323',
		'fields' => 'clientname,orderno,mobile,sourceid,id',
		'fields_china' => array(
			'clientname' => '客户名称',
			'orderno' => '商机编码',
			'mobile' => '手机',
			'sourceid' => '商机来源',
		),
		'checkforfields' => '&#39;clientname&#39;=>&#39;客户名称&#39;,&#39;orderno&#39;=>&#39;商机编码&#39;,&#39;mobile&#39;=>&#39;手机&#39;,&#39;sourceid&#39;=>&#39;商机来源&#39;,&#39;id&#39;=>&#39;编号&#39;',
		'fieldcom' => NULL,
		'listshowfields' => NULL,
		'listshowfields_china' => array(
		),
		'funccheck' => NULL,
		'funccheck_china' => array(
		),
		'funcinfo' => false,
		'url' => 'lookupGeneral',
		'mode' => 'MisSaleBusiness',
		'checkformodel' => '2323',
		'filed' => 'clientname',
		'filed1' => NULL,
		'val' => NULL,
		'showrules' => '',
		'rulesinfo' => '',
		'rules' => '',
		'condition' => '',
		'status' => '1',
		'level' => '15',
	),
	'f9cd188a5f57ea4c1053314fc31adec6' => array(
		'title' => '测试123456',
		'fields' => 'id,orderno,deptid',
		'fields_china' => array(
			'id' => 'ID',
			'orderno' => '申请编号',
			'deptid' => '申请部门',
		),
		'checkforfields' => '&#39;id&#39;=>&#39;ID&#39;,&#39;orderno&#39;=>&#39;申请编号&#39;,&#39;deptid&#39;=>&#39;申请部门&#39;',
		'fieldcom' => NULL,
		'listshowfields' => NULL,
		'listshowfields_china' => array(
		),
		'funccheck' => NULL,
		'funccheck_china' => array(
		),
		'funcinfo' => NULL,
		'url' => 'lookupGeneral',
		'mode' => 'MisHrPersonnelApplicationInfo',
		'checkformodel' => 'MisHrPersonnelApplicationInfo',
		'filed' => 'id',
		'filed1' => 'deptid',
		'val' => 'id',
		'showrules' => '',
		'rulesinfo' => '',
		'rules' => '',
		'condition' => '',
		'status' => '1',
		'level' => '15',
	),
	'bd2e1857df0a1a84930c69a622ddf77c' => array(
		'title' => '客户信息测试',
		'fields' => 'id,orderno,deptid',
		'fields_china' => array(
			'id' => 'ID',
			'orderno' => '申请编号',
			'deptid' => '申请部门',
		),
		'checkforfields' => '&#39;id&#39;=>&#39;ID&#39;,&#39;orderno&#39;=>&#39;申请编号&#39;,&#39;deptid&#39;=>&#39;申请部门&#39;',
		'fieldcom' => NULL,
		'listshowfields' => NULL,
		'listshowfields_china' => array(
		),
		'funccheck' => NULL,
		'funccheck_china' => array(
		),
		'funcinfo' => NULL,
		'url' => 'lookupGeneral',
		'mode' => 'MisHrPersonnelApplicationInfo',
		'checkformodel' => 'MisHrPersonnelApplicationInfo',
		'filed' => 'orderno',
		'filed1' => 'deptid',
		'val' => 'orderno',
		'showrules' => 'KOeUs+ivt+e8luWPtyDkuI3nrYnkuo4gJzEnKSAg',
		'rulesinfo' => 'YToyOntzOjc6Im9yZGVybm8iO2E6MTp7aTowO2E6MTA6e3M6NDoibmFtZSI7czo3OiJvcmRlcm5vIjtzOjU6InRpdGxlIjtzOjEyOiLnlLPor7fnvJblj7ciO3M6Njoic3ltYm9sIjtzOjE6IjIiO3M6MzoidmFsIjtzOjE6IjEiO3M6NzoiY29udHJvbCI7czo0OiJ0ZXh0IjtzOjY6IndpZGdldCI7czoxMzoicm9sZXRleHRpbnNldCI7czo3OiJsZWZ0aXB0IjtOO3M6ODoicmlnaHRpcHQiO047czo0OiJzb3J0IjtpOjA7czo5OiJjZW50ZXJ0aXAiO047fX1zOjY6Im1hcHNxbCI7YToxOntpOjA7YToyOntzOjQ6Im5hbWUiO3M6Mzoic3FsIjtzOjM6InNxbCI7czowOiIiO319fQ==',
		'rules' => 'orderno!=(&#39;1&#39;)',
		'condition' => 'orderno!=(&#39;1&#39;)',
		'status' => '1',
		'level' => '15',
	),
	'306ea7c19135faa788f22fefd9fdfacc' => array(
		'title' => '请假测试',
		'fields' => 'id,orderno,personid,name',
		'fields_china' => array(
			'id' => 'ID',
			'orderno' => '请假编号',
			'personid' => '员工编号',
			'name' => '员工姓名',
		),
		'checkforfields' => '&#39;id&#39;=>&#39;ID&#39;,&#39;orderno&#39;=>&#39;请假编号&#39;,&#39;personid&#39;=>&#39;员工编号&#39;,&#39;name&#39;=>&#39;员工姓名&#39;,&#39;id&#39;=>&#39;编号&#39;',
		'fieldcom' => NULL,
		'listshowfields' => NULL,
		'listshowfields_china' => array(
		),
		'funccheck' => NULL,
		'funccheck_china' => array(
		),
		'funcinfo' => false,
		'url' => 'lookupGeneral',
		'mode' => 'MisHrEmployeeLeaveManagement',
		'checkformodel' => 'MisHrEmployeeLeaveManagement',
		'filed' => 'orderno',
		'filed1' => NULL,
		'val' => 'id',
		'showrules' => '',
		'rulesinfo' => '',
		'rules' => '',
		'condition' => '',
		'status' => '1',
		'level' => '15',
	),
	'409e024225d7184feaff9ad34e633196' => array(
		'title' => '测试222',
		'fields' => 'id,orderno,deptid,dutylevelid',
		'fields_china' => array(
			'id' => 'ID',
			'orderno' => '申请编号',
			'deptid' => '申请部门',
			'dutylevelid' => '申请职级',
		),
		'checkforfields' => '&#39;id&#39;=>&#39;ID&#39;,&#39;orderno&#39;=>&#39;申请编号&#39;,&#39;deptid&#39;=>&#39;申请部门&#39;,&#39;dutylevelid&#39;=>&#39;申请职级&#39;,&#39;id&#39;=>&#39;编号&#39;',
		'fieldcom' => NULL,
		'listshowfields' => NULL,
		'listshowfields_china' => array(
		),
		'funccheck' => NULL,
		'funccheck_china' => array(
		),
		'funcinfo' => false,
		'url' => 'lookupGeneral',
		'mode' => 'MisHrPersonnelApplicationInfo',
		'checkformodel' => 'MisHrPersonnelApplicationInfo',
		'filed' => 'deptid',
		'filed1' => NULL,
		'val' => 'id',
		'showrules' => '',
		'rulesinfo' => '',
		'rules' => '',
		'condition' => '',
		'status' => '1',
		'level' => '15',
	),
	'06b4355b234fab00e173cf0f6e3d083f' => array(
		'title' => '撒地方为其',
		'fields' => 'id,orderno,deptid,dutylevelid',
		'fields_china' => array(
			'id' => 'ID',
			'orderno' => '申请编号',
			'deptid' => '申请部门',
			'dutylevelid' => '申请职级',
		),
		'checkforfields' => '&#39;id&#39;=>&#39;ID&#39;,&#39;orderno&#39;=>&#39;申请编号&#39;,&#39;deptid&#39;=>&#39;申请部门&#39;,&#39;dutylevelid&#39;=>&#39;申请职级&#39;,&#39;id&#39;=>&#39;编号&#39;',
		'fieldcom' => NULL,
		'listshowfields' => NULL,
		'listshowfields_china' => array(
		),
		'funccheck' => NULL,
		'funccheck_china' => array(
		),
		'funcinfo' => false,
		'url' => 'lookupGeneral',
		'mode' => 'MisHrPersonnelApplicationInfo',
		'checkformodel' => 'MisHrPersonnelApplicationInfo',
		'filed' => 'orderno',
		'filed1' => NULL,
		'val' => 'id',
		'showrules' => '',
		'rulesinfo' => '',
		'rules' => '',
		'condition' => '',
		'status' => '1',
		'level' => '15',
	),
	'272c818e31f3ea65afbebbff936ec117' => array(
		'title' => '表格测试',
		'fields' => 'dahuobujie,text1,text3,text2',
		'fields_china' => array(
			'dahuobujie' => '大惑不解',
			'text1' => '大学',
			'text3' => '高中',
			'text2' => '初中',
		),
		'checkforfields' => '&#39;dahuobujie&#39;=>&#39;大惑不解&#39;,&#39;text1&#39;=>&#39;大学&#39;,&#39;text3&#39;=>&#39;高中&#39;,&#39;text2&#39;=>&#39;初中&#39;,&#39;id&#39;=>&#39;编号&#39;',
		'fieldcom' => NULL,
		'listshowfields' => NULL,
		'listshowfields_china' => array(
		),
		'funccheck' => NULL,
		'funccheck_china' => array(
		),
		'funcinfo' => false,
		'url' => 'lookupGeneral',
		'mode' => 'MisAutoDdq',
		'checkformodel' => 'MisAutoDdq',
		'filed' => 'text1',
		'filed1' => NULL,
		'val' => 'id',
		'showrules' => '',
		'rulesinfo' => '',
		'rules' => '',
		'condition' => '',
		'status' => '1',
		'level' => '15',
		'proid' => '279',
		'fieldback' => '6921,6922,6923',
		'dt' => array(
			'mis_auto_okmhz_sub_datatable4' => array(
				'title' => '内嵌数据表格_4',
				'datename' => 'mis_auto_okmhz_sub_datatable4',
				'list' => array(
					'diyi' => array(
						'title' => '第一',
						'category' => 'date',
						'length' => '11',
					),
					'dier' => array(
						'title' => '第二',
						'category' => 'lookup',
						'length' => '30',
					),
					'disan' => array(
						'title' => '第三',
						'category' => 'text',
						'length' => '30',
					),
				),
			),
		),
	),
	'1cb36fb245e44ab053910eeaa066b994' => array(
		'title' => '撒旦',
		'fields' => 'dahuobujie,text1,text3,text2',
		'fields_china' => array(
			'dahuobujie' => '大惑不解',
			'text1' => '大学',
			'text3' => '高中',
			'text2' => '初中',
		),
		'checkforfields' => '&#39;dahuobujie&#39;=>&#39;大惑不解&#39;,&#39;text1&#39;=>&#39;大学&#39;,&#39;text3&#39;=>&#39;高中&#39;,&#39;text2&#39;=>&#39;初中&#39;,&#39;id&#39;=>&#39;编号&#39;',
		'fieldcom' => 'text1,text3',
		'listshowfields' => NULL,
		'listshowfields_china' => array(
		),
		'funccheck' => NULL,
		'funccheck_china' => array(
		),
		'funcinfo' => false,
		'url' => 'lookupGeneral',
		'mode' => 'MisAutoDdq',
		'checkformodel' => 'MisAutoDdq',
		'filed' => 'text1',
		'filed1' => NULL,
		'val' => 'id',
		'showrules' => '',
		'rulesinfo' => '',
		'rules' => '',
		'condition' => '',
		'status' => '1',
		'level' => '15',
		'proid' => '279',
		'fieldback' => '6921,6922,6923',
		'dt' => array(
			'mis_auto_okmhz_sub_datatable4' => array(
				'title' => '内嵌数据表格_4',
				'datename' => 'mis_auto_okmhz_sub_datatable4',
				'list' => array(
					'diyi' => array(
						'title' => '第一',
						'category' => 'date',
						'length' => '11',
					),
					'dier' => array(
						'title' => '第二',
						'category' => 'lookup',
						'length' => '30',
					),
					'disan' => array(
						'title' => '第三',
						'category' => 'text',
						'length' => '30',
					),
				),
			),
		),
	),
	'd6714a86c0cbd02c38e9ec1467327b9e' => array(
		'title' => '多表带回测试',
		'fields' => 'xingming,dizhi,gongsi',
		'fields_china' => array(
			'xingming' => '姓名',
			'dizhi' => '地址',
			'gongsi' => '公司',
		),
		'checkforfields' => '&#39;xingming&#39;=>&#39;姓名&#39;,&#39;dizhi&#39;=>&#39;地址&#39;,&#39;gongsi&#39;=>&#39;公司&#39;,&#39;id&#39;=>&#39;编号&#39;',
		'fieldcom' => 'xingming',
		'listshowfields' => NULL,
		'listshowfields_china' => array(
		),
		'funccheck' => NULL,
		'funccheck_china' => array(
		),
		'funcinfo' => false,
		'url' => 'lookupGeneral',
		'mode' => 'MisAutoVtu',
		'checkformodel' => 'MisAutoVtu',
		'filed' => 'xingming',
		'filed1' => NULL,
		'val' => 'id',
		'showrules' => '',
		'rulesinfo' => '',
		'rules' => '',
		'condition' => '',
		'status' => '1',
		'level' => '15',
		'proid' => '377',
		'fieldback' => '6950,6951',
		'dt' => array(
			'mis_auto_ddskf_sub_datatable4' => array(
				'title' => '内嵌数据表格_4',
				'datename' => 'mis_auto_ddskf_sub_datatable4',
				'list' => array(
					'xueli' => array(
						'title' => '学历',
						'category' => 'text',
						'length' => '30',
					),
					'congyejingyan' => array(
						'title' => '从业经验',
						'category' => 'text',
						'length' => '10',
					),
				),
			),
		),
	),
	'75b8f1896d9a44733d45a3c5032e9b42' => array(
		'title' => '带回设置fordatatable',
		'fields' => 'orderno,ceshiziduanyi,ceshiziduaner,ceshiziduansan,ceshiziduansi,date9-date-date',
		'fields_china' => array(
			'orderno' => '编号',
			'ceshiziduanyi' => '测试字段一',
			'ceshiziduaner' => '测试字段二',
			'ceshiziduansan' => '测试字段三',
			'ceshiziduansi' => '测试字段四',
		),
		'checkforfields' => '&#39;orderno&#39;=>&#39;编号&#39;,&#39;ceshiziduanyi&#39;=>&#39;测试字段一&#39;,&#39;ceshiziduaner&#39;=>&#39;测试字段二&#39;,&#39;ceshiziduansan&#39;=>&#39;测试字段三&#39;,&#39;ceshiziduansi&#39;=>&#39;测试字段四&#39;,&#39;id&#39;=>&#39;编号&#39;',
		'fieldcom' => 'ceshiziduanyi',
		'listshowfields' => NULL,
		'listshowfields_china' => array(
		),
		'funccheck' => NULL,
		'funccheck_china' => array(
		),
		'funcinfo' => false,
		'url' => 'lookupGeneral',
		'mode' => 'MisAutoSmg',
		'checkformodel' => 'MisAutoSmg',
		'filed' => 'orderno',
		'filed1' => NULL,
		'val' => 'id',
		'showrules' => '',
		'rulesinfo' => '',
		'rules' => '',
		'condition' => '',
		'status' => '1',
		'level' => '15',
		'proid' => '534',
		'fieldback' => '6984,6985,6986,6987,6995,7007,7008',
		'dt' => array(
			'mis_auto_ajesd_sub_datatable7' => array(
				'title' => '内嵌数据表格_7',
				'datename' => 'mis_auto_ajesd_sub_datatable7',
				'list' => array(
					'zhong' => array(
						'title' => '中',
						'category' => 'text',
						'length' => '30',
					),
					'hua' => array(
						'title' => '华',
						'category' => 'text',
						'length' => '30',
					),
					'ren' => array(
						'title' => '人',
						'category' => 'text',
						'length' => '30',
					),
					'min' => array(
						'title' => '民',
						'category' => 'text',
						'length' => '30',
					),
					'qian' => array(
						'title' => '钱',
						'category' => 'text',
						'length' => '10',
					),
					'kaishi' => array(
						'title' => '开始',
						'category' => 'date',
						'length' => '11',
					),
					'jieshu' => array(
						'title' => '结束',
						'category' => 'date',
						'length' => '11',
					),
				),
			),
		),
	),
	'29ac30ac1d7e7e550d235b990b512d03' => array(
		'title' => '撒的看风景',
		'fields' => 'id,orderno,personid,name',
		'fields_china' => array(
			'id' => 'ID',
			'orderno' => '请假编号',
			'personid' => '员工编号',
			'name' => '员工姓名',
		),
		'checkforfields' => '&#39;id&#39;=>&#39;ID&#39;,&#39;orderno&#39;=>&#39;请假编号&#39;,&#39;personid&#39;=>&#39;员工编号&#39;,&#39;name&#39;=>&#39;员工姓名&#39;,&#39;id&#39;=>&#39;编号&#39;',
		'fieldcom' => NULL,
		'listshowfields' => NULL,
		'listshowfields_china' => array(
		),
		'funccheck' => NULL,
		'funccheck_china' => array(
		),
		'funcinfo' => false,
		'url' => 'lookupGeneral',
		'mode' => 'MisHrEmployeeLeaveManagement',
		'checkformodel' => 'MisHrEmployeeLeaveManagement',
		'filed' => 'orderno',
		'filed1' => NULL,
		'val' => 'id',
		'showrules' => '',
		'rulesinfo' => '',
		'rules' => '',
		'condition' => '',
		'status' => '1',
		'level' => '15',
	),
	'0ee624ecc86781d1bb191ec5c3d54f4b' => array(
		'title' => '带回设置fordatatable2',
		'fields' => 'orderno,ceshiziduanyi,ceshiziduaner,ceshiziduansan,ceshiziduansi,date9-date,ceshiziduanwu,date10-date',
		'fields_china' => array(
			'orderno' => '编号',
			'ceshiziduanyi' => '测试字段一',
			'ceshiziduaner' => '测试字段二',
			'ceshiziduansan' => '测试字段三',
			'ceshiziduansi' => '测试字段四',
			'ceshiziduanwu' => '测试字段五',
		),
		'checkforfields' => '&#39;orderno&#39;=>&#39;编号&#39;,&#39;ceshiziduanyi&#39;=>&#39;测试字段一&#39;,&#39;ceshiziduaner&#39;=>&#39;测试字段二&#39;,&#39;ceshiziduansan&#39;=>&#39;测试字段三&#39;,&#39;ceshiziduansi&#39;=>&#39;测试字段四&#39;,&#39;ceshiziduanwu&#39;=>&#39;测试字段五&#39;,&#39;id&#39;=>&#39;编号&#39;',
		'fieldcom' => 'orderno',
		'listshowfields' => NULL,
		'listshowfields_china' => array(
		),
		'funccheck' => NULL,
		'funccheck_china' => array(
		),
		'funcinfo' => false,
		'url' => 'lookupGeneral',
		'mode' => 'MisAutoSmg',
		'checkformodel' => 'MisAutoSmg',
		'filed' => 'ceshiziduanyi',
		'filed1' => NULL,
		'val' => 'id',
		'showrules' => '',
		'rulesinfo' => '',
		'rules' => '',
		'condition' => '',
		'status' => '1',
		'level' => '15',
		'proid' => '534',
		'fieldback' => '6984,6987,6995,7007,7008',
		'dt' => array(
			'mis_auto_ajesd_sub_datatable7' => array(
				'title' => '内嵌数据表格_7',
				'datename' => 'mis_auto_ajesd_sub_datatable7',
				'list' => array(
					'zhong' => array(
						'title' => '中',
						'category' => 'text',
						'length' => '30',
					),
					'min' => array(
						'title' => '民',
						'category' => 'text',
						'length' => '30',
					),
					'qian' => array(
						'title' => '钱',
						'category' => 'text',
						'length' => '10',
					),
					'kaishi' => array(
						'title' => '开始',
						'category' => 'date',
						'length' => '11',
					),
					'jieshu' => array(
						'title' => '结束',
						'category' => 'date',
						'length' => '11',
					),
				),
			),
		),
	),
	'c983ae1d779d7d37d1b1d8e09c222b2c' => array(
		'title' => 'rewg34g',
		'fields' => 'id,orderno,deptid,dutylevelid,sumpeople,deptpeople',
		'fields_china' => array(
			'id' => 'ID',
			'orderno' => '申请编号',
			'deptid' => '申请部门',
			'dutylevelid' => '申请职级',
			'sumpeople' => '共增补人数',
			'deptpeople' => '部门现有人数',
		),
		'checkforfields' => '&#39;id&#39;=>&#39;ID&#39;,&#39;orderno&#39;=>&#39;申请编号&#39;,&#39;deptid&#39;=>&#39;申请部门&#39;,&#39;dutylevelid&#39;=>&#39;申请职级&#39;,&#39;sumpeople&#39;=>&#39;共增补人数&#39;,&#39;deptpeople&#39;=>&#39;部门现有人数&#39;,&#39;id&#39;=>&#39;编号&#39;',
		'fieldcom' => NULL,
		'listshowfields' => 'id,orderno,deptid',
		'listshowfields_china' => array(
			'id' => 'ID',
			'orderno' => '申请编号',
			'deptid' => '申请部门',
		),
		'funccheck' => 'orderno,deptid,sumpeople',
		'funccheck_china' => array(
			'orderno' => '申请编号',
			'deptid' => '申请部门',
			'sumpeople' => '共增补人数',
		),
		'funcinfo' => false,
		'url' => 'lookupGeneral',
		'mode' => 'MisHrPersonnelApplicationInfo',
		'checkformodel' => 'MisHrPersonnelApplicationInfo',
		'filed' => 'id',
		'filed1' => NULL,
		'val' => 'id',
		'showrules' => '',
		'rulesinfo' => '',
		'rules' => '',
		'condition' => '',
		'status' => '1',
		'level' => '15',
	),
	'e54500e42e3f8110534b1fd7691387cd' => array(
		'title' => '11111',
		'fields' => 'id,orderno,deptid,dutylevelid,sumpeople,deptpeople',
		'fields_china' => array(
			'id' => 'ID',
			'orderno' => '申请编号',
			'deptid' => '申请部门',
			'dutylevelid' => '申请职级',
			'sumpeople' => '共增补人数',
			'deptpeople' => '部门现有人数',
		),
		'checkforfields' => '&#39;id&#39;=>&#39;ID&#39;,&#39;orderno&#39;=>&#39;申请编号&#39;,&#39;deptid&#39;=>&#39;申请部门&#39;,&#39;dutylevelid&#39;=>&#39;申请职级&#39;,&#39;sumpeople&#39;=>&#39;共增补人数&#39;,&#39;deptpeople&#39;=>&#39;部门现有人数&#39;,&#39;id&#39;=>&#39;编号&#39;',
		'fieldcom' => NULL,
		'listshowfields' => 'id,orderno,deptid',
		'listshowfields_china' => array(
			'id' => 'ID',
			'orderno' => '申请编号',
			'deptid' => '申请部门',
		),
		'funccheck' => 'orderno,deptid,dutylevelid,sumpeople',
		'funccheck_china' => array(
			'orderno' => '申请编号',
			'deptid' => '申请部门',
			'dutylevelid' => '申请职级',
			'sumpeople' => '共增补人数',
		),
		'funcinfo' => false,
		'url' => 'lookupGeneral',
		'mode' => 'MisHrPersonnelApplicationInfo',
		'checkformodel' => 'MisHrPersonnelApplicationInfo',
		'filed' => 'id',
		'filed1' => NULL,
		'val' => 'id',
		'showrules' => '',
		'rulesinfo' => '',
		'rules' => '',
		'condition' => '',
		'status' => '1',
		'level' => '15',
	),
	'f7f56ae72c27ff88c68b87d75f92dfc8' => array(
		'title' => '视图查询',
		'fields' => 'id,userid,email,mobile,account,username',
		'fields_china' => array(
			'id' => 'ID',
		),
		'checkforfields' => NULL,
		'fieldcom' => NULL,
		'listshowfields' => NULL,
		'listshowfields_china' => array(
		),
		'funccheck' => NULL,
		'funccheck_china' => array(
		),
		'funcinfo' => false,
		'url' => 'lookupGeneral',
		'mode' => 'MisHrPersonnelManagement',
		'checkformodel' => NULL,
		'filed' => '',
		'filed1' => NULL,
		'val' => '',
		'showrules' => NULL,
		'rulesinfo' => NULL,
		'rules' => NULL,
		'condition' => NULL,
		'status' => '1',
		'level' => '15',
	),
	'81004f9f7ffcb2fd809037ee183e3b92' => array(
		'title' => 'sadg',
		'fields' => 'id,orderno,deptid,dutylevelid,sumpeople,applicationdate',
		'fields_china' => array(
			'id' => 'ID',
			'orderno' => '申请编号',
			'deptid' => '申请部门',
			'dutylevelid' => '申请职级',
			'sumpeople' => '共增补人数',
			'applicationdate' => '申请日期',
		),
		'checkforfields' => '&#39;id&#39;=>&#39;ID&#39;,&#39;orderno&#39;=>&#39;申请编号&#39;,&#39;deptid&#39;=>&#39;申请部门&#39;,&#39;dutylevelid&#39;=>&#39;申请职级&#39;,&#39;sumpeople&#39;=>&#39;共增补人数&#39;,&#39;applicationdate&#39;=>&#39;申请日期&#39;,&#39;id&#39;=>&#39;编号&#39;',
		'fieldcom' => NULL,
		'listshowfields' => 'orderno,deptid,dutylevelid',
		'listshowfields_china' => array(
			'orderno' => '申请编号',
			'deptid' => '申请部门',
			'dutylevelid' => '申请职级',
		),
		'funccheck' => 'deptid,applicationdate',
		'funccheck_china' => array(
			'deptid' => '申请部门',
			'applicationdate' => '申请日期',
		),
		'funcinfo' => array(
			'\'deptid\'' => array(
				'field' => '\'deptid\'',
				'funcname' => 'getFieldBy',
				'funcdata' => array(
					'0' => '###',
					'1' => 'orderno',
					'2' => 'name',
					'3' => 'mis_system_department',
				),
			),
			'\'applicationdate\'' => array(
				'field' => '\'applicationdate\'',
				'funcname' => 'transTime',
				'funcdata' => array(
					'0' => '',
				),
			),
		),
		'url' => 'lookupGeneral',
		'mode' => 'MisHrPersonnelApplicationInfo',
		'checkformodel' => 'MisHrPersonnelApplicationInfo',
		'filed' => 'deptid',
		'filed1' => NULL,
		'val' => 'id',
		'showrules' => '',
		'rulesinfo' => '',
		'rules' => '',
		'condition' => '',
		'status' => '1',
		'level' => '15',
	),
	'a82e2a04780bff578298c0da5fdfec98' => array(
		'title' => '测试转换函数',
		'fields' => 'id,orderno,deptid,dutylevelid,sumpeople,deptpeople,formationpeople,applicationdate,toworkdate',
		'fields_china' => array(
			'id' => 'ID',
			'orderno' => '申请编号',
			'deptid' => '申请部门',
			'dutylevelid' => '申请职级',
			'sumpeople' => '共增补人数',
			'deptpeople' => '部门现有人数',
			'formationpeople' => '部门编制人数',
			'applicationdate' => '申请日期',
			'toworkdate' => '到职日期',
		),
		'checkforfields' => '&#39;id&#39;=>&#39;ID&#39;,&#39;orderno&#39;=>&#39;申请编号&#39;,&#39;deptid&#39;=>&#39;申请部门&#39;,&#39;dutylevelid&#39;=>&#39;申请职级&#39;,&#39;sumpeople&#39;=>&#39;共增补人数&#39;,&#39;deptpeople&#39;=>&#39;部门现有人数&#39;,&#39;formationpeople&#39;=>&#39;部门编制人数&#39;,&#39;applicationdate&#39;=>&#39;申请日期&#39;,&#39;toworkdate&#39;=>&#39;到职日期&#39;,&#39;id&#39;=>&#39;编号&#39;',
		'fieldcom' => NULL,
		'listshowfields' => 'deptid,dutylevelid,sumpeople,deptpeople,formationpeople,applicationdate',
		'listshowfields_china' => array(
			'deptid' => '申请部门',
			'dutylevelid' => '申请职级',
			'sumpeople' => '共增补人数',
			'deptpeople' => '部门现有人数',
			'formationpeople' => '部门编制人数',
			'applicationdate' => '申请日期',
		),
		'funccheck' => 'applicationdate',
		'funccheck_china' => array(
			'applicationdate' => '申请日期',
		),
		'funcinfo' => false,
		'url' => 'lookupGeneral',
		'mode' => 'MisHrPersonnelApplicationInfo',
		'checkformodel' => 'MisHrPersonnelApplicationInfo',
		'filed' => 'sumpeople',
		'filed1' => NULL,
		'val' => 'id',
		'showrules' => '',
		'rulesinfo' => '',
		'rules' => '',
		'condition' => '',
		'status' => '1',
		'level' => '15',
	),
	'1cf9cb772e37e09dd862f48d0b75b170' => array(
		'title' => '测试转换函数2',
		'fields' => 'id,orderno,deptid,dutylevelid,sumpeople,deptpeople,formationpeople,applicationdate',
		'fields_china' => array(
			'id' => 'ID',
			'orderno' => '申请编号',
			'deptid' => '申请部门',
			'dutylevelid' => '申请职级',
			'sumpeople' => '共增补人数',
			'deptpeople' => '部门现有人数',
			'formationpeople' => '部门编制人数',
			'applicationdate' => '申请日期',
		),
		'checkforfields' => '&#39;id&#39;=>&#39;ID&#39;,&#39;orderno&#39;=>&#39;申请编号&#39;,&#39;deptid&#39;=>&#39;申请部门&#39;,&#39;dutylevelid&#39;=>&#39;申请职级&#39;,&#39;sumpeople&#39;=>&#39;共增补人数&#39;,&#39;deptpeople&#39;=>&#39;部门现有人数&#39;,&#39;formationpeople&#39;=>&#39;部门编制人数&#39;,&#39;applicationdate&#39;=>&#39;申请日期&#39;,&#39;id&#39;=>&#39;编号&#39;',
		'fieldcom' => NULL,
		'listshowfields' => 'orderno,deptid,dutylevelid,sumpeople,deptpeople,formationpeople,applicationdate',
		'listshowfields_china' => array(
			'orderno' => '申请编号',
			'deptid' => '申请部门',
			'dutylevelid' => '申请职级',
			'sumpeople' => '共增补人数',
			'deptpeople' => '部门现有人数',
			'formationpeople' => '部门编制人数',
			'applicationdate' => '申请日期',
		),
		'funccheck' => 'deptid,applicationdate',
		'funccheck_china' => array(
			'deptid' => '申请部门',
			'applicationdate' => '申请日期',
		),
		'funcinfo' => array(
			'deptid' => array(
				'field' => 'deptid',
				'funcname' => 'getFieldBy',
				'funcdata' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'mis_system_department',
				),
			),
			'applicationdate' => array(
				'field' => 'applicationdate',
				'funcname' => 'transTime',
				'funcdata' => array(
					'0' => '',
				),
			),
		),
		'url' => 'lookupGeneral',
		'mode' => 'MisHrPersonnelApplicationInfo',
		'checkformodel' => 'MisHrPersonnelApplicationInfo',
		'filed' => 'deptid',
		'filed1' => NULL,
		'val' => 'id',
		'showrules' => '',
		'rulesinfo' => '',
		'rules' => '',
		'condition' => '',
		'status' => '1',
		'level' => '15',
	),
	'b6765a97128b93de2dcfbf4d3903c2ec' => array(
		'title' => '测试转换函数3',
		'fields' => 'id,orderno,deptid,dutylevelid,sumpeople,deptpeople,formationpeople,applicationdate',
		'fields_china' => array(
			'id' => 'ID',
			'orderno' => '申请编号',
			'deptid' => '申请部门',
			'dutylevelid' => '申请职级',
			'sumpeople' => '共增补人数',
			'deptpeople' => '部门现有人数',
			'formationpeople' => '部门编制人数',
			'applicationdate' => '申请日期',
		),
		'checkforfields' => '&#39;id&#39;=>&#39;ID&#39;,&#39;orderno&#39;=>&#39;申请编号&#39;,&#39;deptid&#39;=>&#39;申请部门&#39;,&#39;dutylevelid&#39;=>&#39;申请职级&#39;,&#39;sumpeople&#39;=>&#39;共增补人数&#39;,&#39;deptpeople&#39;=>&#39;部门现有人数&#39;,&#39;formationpeople&#39;=>&#39;部门编制人数&#39;,&#39;applicationdate&#39;=>&#39;申请日期&#39;,&#39;id&#39;=>&#39;编号&#39;',
		'fieldcom' => NULL,
		'listshowfields' => 'id,orderno,deptid,applicationdate',
		'listshowfields_china' => array(
			'id' => 'ID',
			'orderno' => '申请编号',
			'deptid' => '申请部门',
			'applicationdate' => '申请日期',
		),
		'funccheck' => 'deptid,applicationdate',
		'funccheck_china' => array(
			'deptid' => '申请部门',
			'applicationdate' => '申请日期',
		),
		'funcinfo' => array(
			'deptid' => array(
				'field' => 'deptid',
				'funcname' => 'getFieldBy',
				'funcdata' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'mis_system_department',
				),
			),
			'applicationdate' => array(
				'field' => 'applicationdate',
				'funcname' => 'transTime',
				'funcdata' => array(
					'0' => '',
				),
			),
		),
		'url' => 'lookupGeneral',
		'mode' => 'MisHrPersonnelApplicationInfo',
		'checkformodel' => 'MisHrPersonnelApplicationInfo',
		'filed' => 'deptid',
		'filed1' => NULL,
		'val' => 'id',
		'showrules' => '',
		'rulesinfo' => '',
		'rules' => '',
		'condition' => '',
		'status' => '1',
		'level' => '15',
	),
	'f7a67a646dbc93e2c06db0ca8c06a9b4' => array(
		'title' => '测试转换函数4',
		'fields' => 'id,orderno,deptid,dutylevelid,sumpeople,deptpeople,formationpeople,applicationdate',
		'fields_china' => array(
			'id' => 'ID',
			'orderno' => '申请编号',
			'deptid' => '申请部门',
			'dutylevelid' => '申请职级',
			'sumpeople' => '共增补人数',
			'deptpeople' => '部门现有人数',
			'formationpeople' => '部门编制人数',
			'applicationdate' => '申请日期',
		),
		'checkforfields' => '&#39;id&#39;=>&#39;ID&#39;,&#39;orderno&#39;=>&#39;申请编号&#39;,&#39;deptid&#39;=>&#39;申请部门&#39;,&#39;dutylevelid&#39;=>&#39;申请职级&#39;,&#39;sumpeople&#39;=>&#39;共增补人数&#39;,&#39;deptpeople&#39;=>&#39;部门现有人数&#39;,&#39;formationpeople&#39;=>&#39;部门编制人数&#39;,&#39;applicationdate&#39;=>&#39;申请日期&#39;',
		'fieldcom' => NULL,
		'listshowfields' => 'orderno,deptid,applicationdate',
		'listshowfields_china' => array(
			'orderno' => '申请编号',
			'deptid' => '申请部门',
			'applicationdate' => '申请日期',
		),
		'funccheck' => 'deptid',
		'funccheck_china' => array(
			'deptid' => '申请部门',
		),
		'funcinfo' => array(
			'deptid' => array(
				'field' => 'deptid',
				'funcname' => 'getFieldBy',
				'funcdata' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'mis_system_department',
				),
			),
			'applicationdate' => array(
				'field' => 'applicationdate',
				'funcname' => 'transTime',
				'funcdata' => array(
					'0' => '',
				),
			),
		),
		'url' => 'lookupGeneral',
		'mode' => 'MisHrPersonnelApplicationInfo',
		'checkformodel' => 'MisHrPersonnelApplicationInfo',
		'filed' => 'deptid',
		'filed1' => NULL,
		'val' => 'id',
		'showrules' => '',
		'rulesinfo' => '',
		'rules' => '',
		'condition' => '',
		'status' => '1',
		'level' => '15',
	),
	'ee772665fe13c9ce7ade82e49db9d1df' => array(
		'title' => '测试转换函数5',
		'fields' => 'id,orderno,deptid,dutylevelid,sumpeople,deptpeople,formationpeople,applicationdate',
		'fields_china' => array(
			'id' => 'ID',
			'orderno' => '申请编号',
			'deptid' => '申请部门',
			'dutylevelid' => '申请职级',
			'sumpeople' => '共增补人数',
			'deptpeople' => '部门现有人数',
			'formationpeople' => '部门编制人数',
			'applicationdate' => '申请日期',
		),
		'checkforfields' => '&#39;id&#39;=>&#39;ID&#39;,&#39;orderno&#39;=>&#39;申请编号&#39;,&#39;deptid&#39;=>&#39;申请部门&#39;,&#39;dutylevelid&#39;=>&#39;申请职级&#39;,&#39;sumpeople&#39;=>&#39;共增补人数&#39;,&#39;deptpeople&#39;=>&#39;部门现有人数&#39;,&#39;formationpeople&#39;=>&#39;部门编制人数&#39;,&#39;applicationdate&#39;=>&#39;申请日期&#39;',
		'fieldcom' => NULL,
		'listshowfields' => 'deptid,deptpeople,formationpeople,applicationdate',
		'listshowfields_china' => array(
			'deptid' => '申请部门',
			'deptpeople' => '部门现有人数',
			'formationpeople' => '部门编制人数',
			'applicationdate' => '申请日期',
		),
		'funccheck' => NULL,
		'funccheck_china' => array(
		),
		'funcinfo' => array(
			'deptid' => array(
				'field' => 'deptid',
				'funcname' => 'getFieldBy',
				'funcdata' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'mis_system_department',
				),
			),
			'applicationdate' => array(
				'field' => 'applicationdate',
				'funcname' => 'transTime',
				'funcdata' => array(
					'0' => '',
				),
			),
		),
		'url' => 'lookupGeneral',
		'mode' => 'MisHrPersonnelApplicationInfo',
		'checkformodel' => 'MisHrPersonnelApplicationInfo',
		'filed' => 'deptid',
		'filed1' => NULL,
		'val' => 'id',
		'showrules' => '(申请编号 不等于 &#39;1&#39;)',
		'rulesinfo' => 'YToyOntzOjc6Im9yZGVybm8iO2E6MTp7aTowO2E6MTA6e3M6NDoibmFtZSI7czo3OiJvcmRlcm5vIjtzOjU6InRpdGxlIjtzOjEyOiLnlLPor7fnvJblj7ciO3M6Njoic3ltYm9sIjtzOjE6IjIiO3M6MzoidmFsIjtzOjE6IjEiO3M6NzoiY29udHJvbCI7czo0OiJ0ZXh0IjtzOjY6IndpZGdldCI7czoxMzoicm9sZXRleHRpbnNldCI7czo3OiJsZWZ0aXB0IjtzOjA6IiI7czo4OiJyaWdodGlwdCI7czowOiIiO3M6NDoic29ydCI7aTowO3M6OToiY2VudGVydGlwIjtzOjA6IiI7fX1zOjY6Im1hcHNxbCI7YToxOntpOjA7YToyOntzOjQ6Im5hbWUiO3M6Mzoic3FsIjtzOjM6InNxbCI7czowOiIiO319fQ==',
		'rules' => 'orderno!=(&#39;1&#39;)',
		'condition' => 'orderno!=(&#39;1&#39;)',
		'status' => '1',
		'level' => '15',
	),
	'bd704061c069be5846e0296cc2113be1' => array(
		'title' => '测试转换函数6',
		'fields' => 'id,orderno,deptid,dutylevelid,sumpeople,deptpeople,formationpeople,applicationdate',
		'fields_china' => array(
			'id' => 'ID',
			'orderno' => '申请编号',
			'deptid' => '申请部门',
			'dutylevelid' => '申请职级',
			'sumpeople' => '共增补人数',
			'deptpeople' => '部门现有人数',
			'formationpeople' => '部门编制人数',
			'applicationdate' => '申请日期',
		),
		'checkforfields' => '&#39;id&#39;=>&#39;ID&#39;,&#39;orderno&#39;=>&#39;申请编号&#39;,&#39;deptid&#39;=>&#39;申请部门&#39;,&#39;dutylevelid&#39;=>&#39;申请职级&#39;,&#39;sumpeople&#39;=>&#39;共增补人数&#39;,&#39;deptpeople&#39;=>&#39;部门现有人数&#39;,&#39;formationpeople&#39;=>&#39;部门编制人数&#39;,&#39;applicationdate&#39;=>&#39;申请日期&#39;',
		'fieldcom' => NULL,
		'listshowfields' => 'orderno,deptid,dutylevelid,sumpeople,deptpeople,formationpeople,applicationdate',
		'listshowfields_china' => array(
			'orderno' => '申请编号',
			'deptid' => '申请部门',
			'dutylevelid' => '申请职级',
			'sumpeople' => '共增补人数',
			'deptpeople' => '部门现有人数',
			'formationpeople' => '部门编制人数',
			'applicationdate' => '申请日期',
		),
		'funccheck' => 'deptid,applicationdate',
		'funccheck_china' => array(
			'deptid' => '申请部门',
			'applicationdate' => '申请日期',
		),
		'funcinfo' => array(
			'deptid' => array(
				'field' => 'deptid',
				'funcname' => 'getFieldBy',
				'funcdata' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'mis_system_department',
				),
			),
			'applicationdate' => array(
				'field' => 'applicationdate',
				'funcname' => 'transTime',
				'funcdata' => array(
					'0' => '',
				),
			),
		),
		'url' => 'lookupGeneral',
		'mode' => 'MisHrPersonnelApplicationInfo',
		'checkformodel' => 'MisHrPersonnelApplicationInfo',
		'filed' => 'formationpeople',
		'filed1' => NULL,
		'val' => 'id',
		'showrules' => '',
		'rulesinfo' => '',
		'rules' => '',
		'condition' => '',
		'status' => '1',
		'level' => '15',
	),
);

?>