<?php 
return array(
	'debit' => array(
		'remark' => '基础设置-财务相关-会计科目，模型',
		'status' => '1',
		'name' => '基础设置-财务相关-会计科目，模型',
		'level' => '15',
		'debit' => array(
			'0' => '否',
			'1' => '是',
		),
	),
	'credit' => array(
		'remark' => '基础设置-财务相关-会计科目，模型',
		'status' => '1',
		'name' => '基础设置-财务相关-会计科目，模型',
		'level' => '15',
		'credit' => array(
			'0' => '否',
			'1' => '是',
		),
	),
	'sex' => array(
		'remark' => '通用-性别类数组',
		'status' => '1',
		'name' => '通用-性别类数组',
		'level' => '15',
		'sex' => array(
			'0' => '女',
			'1' => '男',
		),
	),
	'status' => array(
		'remark' => '通用-状态类数组',
		'status' => array(
			'-1' => '禁用',
			'0' => '锁定',
			'1' => '正常',
		),
		'name' => '通用-状态类数组',
		'level' => '15',
	),
	'positivestatus' => array(
		'remark' => '人事基本资料-转正状态，模型-MisHrPersonnelPersonInfo',
		'status' => '1',
		'name' => '人事基本资料-转正状态，模型-MisHrPersonnelPersonInfo',
		'level' => '15',
		'positivestatus' => array(
			'0' => '否',
			'1' => '是',
		),
	),
	'working' => array(
		'remark' => '人事基本资料-离职状态，模型-MisHrPersonnelPersonInfo',
		'status' => '1',
		'name' => '人事基本资料-离职状态，模型-MisHrPersonnelPersonInfo',
		'level' => '15',
		'working' => array(
			'0' => '离职',
			'1' => '在职',
		),
	),
	'workkind' => array(
		'remark' => '人事基本资料-工种，模型-MisHrPersonnelPersonInfo  这里是有问题的。如果是checkbox的话。组合出来的sql是 workkind in （非技，技术，实习）',
		'status' => '1',
		'name' => '人事基本资料-工种，模型-MisHrPersonnelPersonInfo  这里是有问题的。如果是checkbox的话。组合出来的sql是 workkind in （非技，技术，实习）',
		'level' => '15',
		'workkind' => array(
			'1' => '技术',
			'2' => '非技',
			'3' => '实习',
			'4' => '普工',
		),
	),
	'reportmaintain' => array(
		'remark' => '人事工伤管理-工伤认定，模型-MisHrPersonnelIndustrialInjuryInfo',
		'status' => '1',
		'name' => '人事工伤管理-工伤认定，模型-MisHrPersonnelIndustrialInjuryInfo',
		'level' => '15',
		'reportmaintain' => array(
			'是' => '离职',
			'非' => '在职',
		),
	),
	'elcomercioreport' => array(
		'remark' => '人事工伤管理-商保报案，模型-MisHrPersonnelIndustrialInjuryInfo',
		'status' => '1',
		'name' => '人事工伤管理-商保报案，模型-MisHrPersonnelIndustrialInjuryInfo',
		'level' => '15',
		'elcomercioreport' => array(
			'是' => '是',
			'否' => '否',
		),
	),
	'maimidentify' => array(
		'remark' => '人事工伤管理-伤残鉴定，模型-MisHrPersonnelIndustrialInjuryInfo',
		'status' => '1',
		'name' => '人事工伤管理-伤残鉴定，模型-MisHrPersonnelIndustrialInjuryInfo',
		'level' => '15',
		'maimidentify' => array(
			'是' => '是',
			'否' => '否',
		),
	),
	'interviewfirst' => array(
		'remark' => '人事招骋管理-招骋管理模块，模型-MisHrInvitereForm',
		'status' => '1',
		'name' => '人事招骋管理-招骋管理模块，模型-MisHrInvitereForm',
		'level' => '15',
		'interviewfirst' => array(
			'0' => '不合格',
			'1' => '合格',
			'2' => '放入人才库',
			'3' => '待定',
			'4' => '未面试',
		),
	),
	'interviewagain' => array(
		'remark' => '人事招骋管理-招骋管理模块，模型-MisHrInvitereForm',
		'status' => '1',
		'name' => '人事招骋管理-招骋管理模块，模型-MisHrInvitereForm',
		'level' => '15',
		'interviewagain' => array(
			'0' => '不合格',
			'1' => '合格',
			'2' => '放入人才库',
			'3' => '待定',
			'4' => '未面试',
		),
	),
	'introducemethod' => array(
		'remark' => '人事招骋管理-招骋管理模块，模型-MisHrInvitereForm',
		'status' => '1',
		'name' => '人事招骋管理-招骋管理模块，模型-MisHrInvitereForm',
		'level' => '15',
		'introducemethod' => array(
			'1' => '网络面试',
			'2' => '现场招聘',
			'3' => '内部介绍',
			'4' => '校园招聘',
			'5' => '猎头招聘',
			'6' => '其他方式',
		),
	),
	'quittype' => array(
		'remark' => '人事招骋 模型-MisHrPersonnelQuitInfo',
		'status' => '1',
		'name' => '人事招骋 模型-MisHrPersonnelQuitInfo',
		'level' => '15',
		'quittype' => array(
			'19' => '辞职',
			'20' => '自离',
			'21' => '其他',
		),
	),
	'limittype' => array(
		'remark' => '人事员工合同 合同期限',
		'status' => '1',
		'name' => '人事员工合同 合同期限',
		'level' => '15',
		'limittype' => array(
			'固定期' => '固定期',
			'无固定期' => '无固定期',
		),
	),
	'employeecontracttype' => array(
		'remark' => '人事员工合同 合同类型',
		'status' => '1',
		'name' => '人事员工合同 合同类型',
		'level' => '15',
		'employeecontracttype' => array(
			'合同' => '合同',
			'协议' => '协议',
		),
	),
	'employeecontractstatus' => array(
		'remark' => '人事员工合同 合同状态',
		'status' => '1',
		'name' => '人事员工合同 合同状态',
		'level' => '15',
		'employeecontractstatus' => array(
			'0' => '合同中',
			'1' => '已结束',
		),
	),
	'type' => array(
		'remark' => '人事外联合同管理 模型-MisHrOutsideBargain',
		'status' => '1',
		'name' => '人事外联合同管理 模型-MisHrOutsideBargain',
		'level' => '15',
		'type' => array(
			'1' => '招聘合同',
			'2' => '工伤合同',
			'3' => '其他合同',
		),
	),
	'unittype' => array(
		'remark' => '产品单位 模型-MisProductUnit',
		'status' => '1',
		'name' => '产品单位 模型-MisProductUnit',
		'level' => '15',
		'unittype' => array(
			'0' => '整数型',
			'1' => '浮点型',
		),
	),
	'leavetype' => array(
		'remark' => '人事外请假管理 模型-MisHrPersonnelLeaveInfo',
		'status' => '1',
		'name' => '人事外请假管理 模型-MisHrPersonnelLeaveInfo',
		'level' => '15',
		'leavetype' => array(
			'1' => '招聘合同',
			'2' => '年假',
			'3' => '病假',
			'4' => '事假',
			'5' => '丧假',
			'6' => '婚假',
			'7' => '工伤假',
			'8' => '培训假',
			'9' => '补休',
			'10' => '其他',
			'53' => '现场招骋',
			'55' => '现场招骋',
			'60' => '锐成猎头',
		),
	),
	'yjzgltype' => array(
		'remark' => '外经证管理 模型-MisFinanceProjectWaijingzheng',
		'status' => '1',
		'name' => '外经证管理 模型-MisFinanceProjectWaijingzheng',
		'level' => '15',
		'yjzgltype' => array(
			'1' => '合作方',
			'2' => '一般项目',
			'5' => '其他',
		),
	),
	'yuetongcard' => array(
		'remark' => '派车申请 模型-MisRequestCar',
		'status' => '1',
		'name' => '派车申请 模型-MisRequestCar',
		'level' => '15',
		'yuetongcard' => array(
			'0' => '不需要',
			'1' => '需要',
		),
	),
	'dnbzgltype' => array(
		'remark' => '电脑配制管理 模型-MisComputer',
		'status' => '1',
		'name' => '电脑配制管理 模型-MisComputer',
		'level' => '15',
		'dnbzgltype' => array(
			'1' => '台式机',
			'2' => '笔记本',
			'3' => '相机',
			'4' => '服务器',
			'5' => '打印机',
			'6' => '网络设备',
			'7' => '电话机',
			'8' => '其他',
		),
	),
	'dyxxorganization' => array(
		'remark' => '党员信息 模型-MisHrPartOrganization',
		'status' => '1',
		'name' => '党员信息 模型-MisHrPartOrganization',
		'level' => '15',
		'dyxxorganization' => array(
			'1' => '正式',
			'2' => '预备',
		),
	),
	'dyxxadministration' => array(
		'remark' => '党员信息 模型-MisHrPartOrganization',
		'status' => '1',
		'name' => '党员信息 模型-MisHrPartOrganization',
		'level' => '15',
		'dyxxadministration' => array(
			'1' => '是',
			'2' => '候选',
			'3' => '否',
		),
	),
	'yuangongBz' => array(
		'remark' => '员工基础资料管理 模型-MisHrPersonnelPersonInfo',
		'status' => '1',
		'name' => '员工基础资料管理 模型-MisHrPersonnelPersonInfo',
		'level' => '15',
		'yuangongBz' => array(
			'1' => '监管',
			'2' => '守护',
			'3' => '押运',
			'4' => '行政',
			'5' => '驾驶员',
			'6' => '普通队员',
			'7' => '技术人员',
		),
	),
	'HrOutsideBargainHT' => array(
		'remark' => '人事外联合同 模型-MisHrOutsideBargain',
		'status' => '1',
		'name' => '人事外联合同 模型-MisHrOutsideBargain',
		'level' => '15',
		'HrOutsideBargainHT' => array(
			'1' => '招聘合同',
			'2' => '工伤合同',
			'3' => '其他合同',
		),
	),
	'MisHrInvitereFormZP' => array(
		'remark' => '人员招聘管理 模型-MisHrInvitereForm',
		'status' => '1',
		'name' => '人员招聘管理 模型-MisHrInvitereForm',
		'level' => '15',
		'MisHrInvitereFormZP' => array(
			'1' => '网络招聘',
			'2' => '现场招聘',
			'3' => '内部介绍',
			'4' => '校园招聘',
			'5' => '猎头招聘',
			'6' => '其他方式',
		),
	),
	'SystemLogSelect' => array(
		'remark' => '系统日志-SystemLog',
		'status' => '1',
		'name' => '系统日志-SystemLog',
		'level' => '15',
		'SystemLogSelect' => array(
			'0' => '异常',
			'1' => '更新',
			'2' => '删除',
		),
	),
	'bxkctype' => array(
		'remark' => '培训课程-MisHrEvaluationTrain',
		'status' => '1',
		'name' => '培训课程-MisHrEvaluationTrain',
		'level' => '15',
		'bxkctype' => array(
			'通用素质' => '通用素质',
			'企业文化' => '企业文化',
			'专业类' => '专业类',
			'管理类' => '管理类',
			'安全生产' => '安全生产',
		),
	),
	'bxkcclasssource' => array(
		'remark' => '培训课程-MisHrEvaluationTrain',
		'status' => '1',
		'name' => '培训课程-MisHrEvaluationTrain',
		'level' => '15',
		'bxkcclasssource' => array(
			'企业内部' => '企业内部',
			'外训机构' => '外训机构',
			'院校' => '院校',
			'其他' => '其他',
		),
	),
	'bxkclevel' => array(
		'remark' => '培训课程-MisHrEvaluationTrain',
		'status' => '1',
		'name' => '培训课程-MisHrEvaluationTrain',
		'level' => '15',
		'bxkclevel' => array(
			'无' => '无',
			'初级' => '初级',
			'中级' => '中级',
			'高级' => '高级',
		),
	),
	'bxkctrainform' => array(
		'remark' => '培训课程-MisHrEvaluationTrain',
		'status' => '1',
		'name' => '培训课程-MisHrEvaluationTrain',
		'level' => '15',
		'bxkctrainform' => array(
			'讲座' => '讲座',
			'参观学习' => '参观学习',
			'视频' => '视频',
			'在岗学习' => '在岗学习',
			'其他' => '其他',
		),
	),
	'bxkcassessment' => array(
		'remark' => '培训课程-MisHrEvaluationTrain',
		'status' => '1',
		'name' => '培训课程-MisHrEvaluationTrain',
		'level' => '15',
		'bxkcassessment' => array(
			'口试' => '口试',
			'笔试' => '笔试',
			'实操演练' => '实操演练',
			'其他' => '其他',
		),
	),
	'levels' => array(
		'remark' => '文章管理-MisKnowledgeManage',
		'status' => '1',
		'name' => '文章管理-MisKnowledgeManage',
		'level' => '15',
		'levels' => array(
			'0' => '未知级别',
			'1' => 'A级',
			'2' => 'B级',
			'3' => 'C级',
			'4' => 'D级',
		),
	),
	'applicationtype' => array(
		'remark' => '人事申请管理-MisHrPersonnelApplicationInfo',
		'status' => '1',
		'name' => '人事申请管理-MisHrPersonnelApplicationInfo',
		'level' => '15',
		'applicationtype' => array(
			'编制内申请' => '编制内申请',
			'编制外申请' => '编制外申请',
		),
	),
	'politicsstatus' => array(
		'remark' => '员工基础资料管理-MisHrPersonnelPersonInfo',
		'status' => '1',
		'name' => '员工基础资料管理-MisHrPersonnelPersonInfo',
		'level' => '15',
		'politicsstatus' => array(
			'群众' => '群众',
			'团员' => '团员',
			'党员' => '党员',
		),
	),
	'ismarry' => array(
		'remark' => '员工基础资料 - 婚姻状况',
		'status' => '1',
		'name' => '员工基础资料 - 婚姻状况',
		'level' => '15',
		'ismarry' => array(
			'未婚' => '未婚',
			'已婚' => '已婚',
			'离异' => '离异',
			'丧偶' => '丧偶',
		),
	),
	'probationcycle' => array(
		'remark' => '员工基础资料 - 婚姻状况',
		'status' => '1',
		'name' => '员工基础资料 - 婚姻状况',
		'level' => '15',
		'probationcycle' => array(
			'1' => '1个月',
			'2' => '2个月',
			'3' => '3个月',
			'4' => '4个月',
			'5' => '5个月',
			'6' => '6个月',
			'7' => '7个月',
			'8' => '8个月',
			'9' => '9个月',
			'10' => '10个月',
			'11' => '11个月',
			'12' => '12个月',
		),
	),
	'linkonecontent' => array(
		'remark' => '绩效评估管理-MisHrPersonnelAppraisalInfo',
		'status' => '1',
		'name' => '绩效评估管理-MisHrPersonnelAppraisalInfo',
		'level' => '15',
		'linkonecontent' => array(
			'0' => '未评估',
			'1' => '已评估',
		),
	),
	'business_type' => array(
		'remark' => '车辆管理加油记录-MisCarAddOilInfo',
		'status' => '1',
		'name' => '车辆管理加油记录-MisCarAddOilInfo',
		'level' => '15',
		'business_type' => array(
			'0' => '圈钱',
			'1' => '加油',
			'2' => '异地圈钱',
		),
	),
	'MisTaskInformation_executingstatus' => array(
		'remark' => '任务动态 模型-MisTaskInformation',
		'status' => '1',
		'name' => '任务动态 模型-MisTaskInformation',
		'level' => '15',
		'MisTaskInformation_executingstatus' => array(
			'0' => '未启动',
			'1' => '未查看',
			'2' => '已查看',
			'3' => '进行中',
			'4' => '终止',
			'5' => '打回',
			'6' => '结束',
		),
	),
	'fixed' => array(
		'remark' => '行政的日常维护记录-MisLogistcsFixLog',
		'status' => '1',
		'name' => '行政的日常维护记录-MisLogistcsFixLog',
		'level' => '15',
		'fixed' => array(
			'1' => '修复',
			'2' => '未修复',
			'3' => '报废',
			'4' => '外修',
			'5' => '报告状态',
		),
	),
	'falut_type' => array(
		'remark' => '行政的日常维护记录-MisLogistcsFixLog',
		'status' => '1',
		'name' => '行政的日常维护记录-MisLogistcsFixLog',
		'level' => '15',
		'falut_type' => array(
			'1' => '结排水',
			'2' => '电路',
			'3' => '电气设备',
			'4' => '其它',
		),
	),
	'makeinvoicetype' => array(
		'remark' => '发票信息',
		'status' => '1',
		'name' => '发票信息',
		'level' => '15',
		'makeinvoicetype' => array(
			'1' => '普通发票',
			'2' => '增值税发票',
		),
	),
	'projectmakeinvoicetype' => array(
		'remark' => '发票信息',
		'status' => '1',
		'name' => '发票信息',
		'level' => '15',
		'projectmakeinvoicetype' => array(
			'2' => '增值税发票',
			'3' => '地税服务费',
			'4' => '地税建安发票',
		),
	),
	'financemakeinvoicetype' => array(
		'remark' => '发票信息 便于财务开票查看',
		'status' => '1',
		'name' => '发票信息 便于财务开票查看',
		'level' => '15',
		'financemakeinvoicetype' => array(
			'1' => '普通发票',
			'2' => '增值税发票',
			'3' => '地税服务费',
			'4' => '地税建安发票',
		),
	),
	'chargetypelist' => array(
		'remark' => '发票开具方式',
		'status' => '1',
		'name' => '发票开具方式',
		'level' => '15',
		'chargetypelist' => array(
			'1' => '月',
			'2' => '年',
			'3' => '季度',
			'4' => '全款',
			'5' => '半年',
		),
	),
	'persontype' => array(
		'remark' => '人力资源 -人事招聘 -人员类型',
		'status' => '1',
		'name' => '人力资源 -人事招聘 -人员类型',
		'level' => '15',
		'persontype' => array(
			'1' => '普通',
			'2' => '特殊',
		),
	),
	'equipmenttype' => array(
		'remark' => '办公设备的类型MisWorkFacilityManage',
		'status' => '1',
		'name' => '办公设备的类型MisWorkFacilityManage',
		'level' => '15',
		'equipmenttype' => array(
			'1' => '电脑',
			'2' => '打印机',
			'3' => '空调',
			'4' => '文件柜',
			'5' => '其他',
		),
	),
	'customertype' => array(
		'remark' => '部门类型配置',
		'status' => '1',
		'name' => '部门类型配置',
		'level' => '15',
		'customertype' => array(
			'1' => '人力防范',
			'2' => '技术防范',
			'3' => '民爆守押',
		),
	),
	'customervitalityid' => array(
		'remark' => '客户状态',
		'status' => '1',
		'name' => '客户状态',
		'level' => '15',
		'customervitalityid' => array(
			'1' => '正常',
			'2' => '流失',
		),
	),
	'oaarchivesmanagetype' => array(
		'remark' => '档案管理类型：MisOaArchivesManage',
		'status' => '1',
		'name' => '档案管理类型：MisOaArchivesManage',
		'level' => '15',
		'oaarchivesmanagetype' => array(
			'1' => '文书',
			'2' => '业务',
		),
	),
	'specialemployeemanagepoliticsstatus' => array(
		'remark' => '特殊人员管理MisBusinessSpecialEmployeeManage',
		'status' => '1',
		'name' => '特殊人员管理MisBusinessSpecialEmployeeManage',
		'level' => '15',
		'specialemployeemanagepoliticsstatus' => array(
			'1' => '团员',
			'2' => '群众',
			'3' => '党员',
			'4' => '预备党员',
			'5' => '其他',
		),
	),
	'carsource' => array(
		'remark' => '国产还是进口',
		'status' => '1',
		'name' => '国产还是进口',
		'level' => '15',
		'carsource' => array(
			'1' => '国产',
			'2' => '进口',
		),
	),
	'airconditioningsystem' => array(
		'remark' => '空调系统',
		'status' => '1',
		'name' => '空调系统',
		'level' => '15',
		'airconditioningsystem' => array(
			'1' => '其他',
			'2' => '制冷',
			'3' => '采暖',
		),
	),
	'abs' => array(
		'remark' => '防抱制动装置(ABS)',
		'status' => '1',
		'name' => '防抱制动装置(ABS)',
		'level' => '15',
		'abs' => array(
			'0' => '无',
			'1' => '有',
		),
	),
	'carbelong' => array(
		'remark' => '车辆信息',
		'status' => '1',
		'name' => '车辆信息',
		'level' => '15',
		'carbelong' => array(
			'2' => '公共所有',
		),
	),
	'carcolour' => array(
		'remark' => '车辆颜色配置',
		'status' => '1',
		'name' => '车辆颜色配置',
		'level' => '15',
		'carcolour' => array(
			'银色' => '银色',
			'黄色' => '黄色',
			'灰色' => '灰色',
			'蓝色' => '蓝色',
			'白色' => '白色',
			'红色' => '红色',
			'黑色' => '黑色',
			'其他' => '其他',
		),
	),
	'fueltype' => array(
		'remark' => '燃料种类',
		'status' => '1',
		'name' => '燃料种类',
		'level' => '15',
		'fueltype' => array(
			'0号柴油' => '0号柴油',
			'93号汽油' => '93号汽油',
			'97号汽油' => '97号汽油',
		),
	),
	'responsibility' => array(
		'remark' => '伤病管理',
		'status' => '1',
		'name' => '伤病管理',
		'level' => '15',
		'responsibility' => array(
			'1' => '6个月',
			'2' => '12个月',
			'3' => '24个月',
		),
	),
	'healback' => array(
		'remark' => '伤病管理--治愈情况',
		'status' => '1',
		'name' => '伤病管理--治愈情况',
		'level' => '15',
		'healback' => array(
			'1' => '治疗中',
			'2' => '已治愈',
			'3' => '未开始',
			'4' => '已超期',
		),
	),
	'agreetypeid' => array(
		'remark' => '入职办理 ,合约性质',
		'status' => '1',
		'name' => '入职办理 ,合约性质',
		'level' => '15',
		'agreetypeid' => array(
			'1' => '合同',
			'2' => '兼职',
			'3' => '自主择业',
			'4' => '4050',
			'5' => '退休',
		),
	),
	'accounttype' => array(
		'remark' => '员工管理 户口类型',
		'status' => '1',
		'name' => '员工管理 户口类型',
		'level' => '15',
		'accounttype' => array(
			'0' => '城镇',
			'1' => '农村',
		),
	),
	'top' => array(
		'remark' => '系统公告,是否置顶',
		'status' => '1',
		'name' => '系统公告,是否置顶',
		'level' => '15',
		'top' => array(
			'1' => '是',
			'2' => '否',
		),
	),
	'commit' => array(
		'remark' => '系统公告,提交状态',
		'status' => '1',
		'name' => '系统公告,提交状态',
		'level' => '15',
		'commit' => array(
			'1' => '已发布',
			'2' => '待审核',
			'3' => '审核未通过',
			'4' => '已终止',
			'5' => '新建',
		),
	),
	'hurtcondition' => array(
		'remark' => '工伤 伤势情况',
		'status' => '1',
		'name' => '工伤 伤势情况',
		'level' => '15',
		'hurtcondition' => array(
			'1' => '轻微',
			'2' => '一般',
			'3' => '严重',
			'4' => '死亡',
			'5' => '其他',
		),
	),
	'disposestage' => array(
		'remark' => '工伤处理阶段',
		'status' => '1',
		'name' => '工伤处理阶段',
		'level' => '15',
		'disposestage' => array(
			'1' => '准备资料',
			'2' => '社保认定中',
			'3' => '待康复',
			'4' => '评残或放弃',
			'5' => '报销',
			'6' => '冲账',
			'7' => '完结',
		),
	),
	'auditstatus' => array(
		'remark' => '工伤处理阶段',
		'status' => '1',
		'name' => '工伤处理阶段',
		'level' => '15',
		'auditstatus' => array(
			'1' => '审核通过',
			'0' => '审核未通过',
		),
	),
	'linkprefix' => array(
		'remark' => '网址前缀',
		'status' => '1',
		'name' => '网址前缀',
		'level' => '15',
		'linkprefix' => array(
			'1' => 'http://',
			'2' => 'https://',
		),
	),
	'roleinexp' => array(
		'remark' => '流程管理规则符号',
		'status' => '1',
		'name' => NULL,
		'level' => '15',
		'roleinexp' => array(
			'1' => '等于',
			'2' => '不等于',
			'3' => '大于',
			'4' => '大于等于',
			'5' => '小于',
			'6' => '小于等于',
		),
	),
	'roleexp' => array(
		'remark' => '流程管理规则符号',
		'status' => '1',
		'name' => NULL,
		'level' => '15',
		'roleexp' => array(
			'1' => '=',
			'2' => '!=',
			'3' => '&gt;',
			'4' => '&gt;=',
			'5' => '&lt;',
			'6' => '&lt;=',
		),
	),
	'roletextinexp' => array(
		'remark' => '流程管理规则符号',
		'status' => '1',
		'name' => '流程管理规则符号',
		'level' => '15',
		'roletextinexp' => array(
			'1' => '等于',
			'2' => '不等于',
			'3' => '包含',
			'4' => '不包含',
		),
	),
	'roletextinset' => array(
		'remark' => '流程管理规则符号',
		'status' => '1',
		'name' => '流程管理规则符号',
		'level' => '15',
		'roletextinset' => array(
			'1' => '=',
			'2' => '!=',
			'3' => 'in',
			'4' => 'not in',
		),
	),
	'roleremind' => array(
		'remark' => '提醒条件',
		'status' => '1',
		'name' => '提醒条件',
		'level' => '15',
		'roleremind' => array(
			'1' => '=',
			'2' => '!=',
			'3' => '>',
			'4' => '>=',
			'5' => '<',
			'6' => '<=',
		),
	),
	'phoneflag' => array(
		'remark' => '手机发送信息状态',
		'status' => '1',
		'name' => '手机发送信息状态',
		'level' => '15',
		'phoneflag' => array(
			'0' => '未发送',
			'1' => '已发送',
		),
	),
	'employeeStatus' => array(
		'remark' => '人事 员工档案',
		'status' => '1',
		'name' => '人事 员工档案',
		'level' => '15',
		'employeeStatus' => array(
			'1' => '转正',
			'2' => '离职',
			'3' => '请假',
			'4' => '异动',
		),
	),
	'computerfault' => array(
		'remark' => '电脑维护',
		'status' => '1',
		'name' => '电脑维护',
		'level' => '15',
		'computerfault' => array(
			'1' => '系统',
			'2' => '硬件',
			'3' => '软件',
			'4' => '网络',
			'5' => '病毒感染',
			'6' => '其他',
		),
	),
	'statementreadstatus' => array(
		'remark' => '工作报告阅读',
		'status' => '1',
		'name' => '工作报告阅读',
		'level' => '15',
		'statementreadstatus' => array(
			'0' => '未读',
			'1' => '已读',
		),
	),
	'forleavetype' => array(
		'remark' => '员工离职类别',
		'status' => '1',
		'name' => '员工离职类别',
		'level' => '15',
		'forleavetype' => array(
			'95' => '辞退',
			'94' => '离职',
		),
	),
	'isinjob' => array(
		'remark' => '招聘是否入职',
		'status' => '1',
		'name' => '招聘是否入职',
		'level' => '15',
		'isinjob' => array(
			'0' => '未入职',
			'1' => '已入职',
		),
	),
	'dealstatus' => array(
		'remark' => '协同事项 处理状态',
		'status' => '1',
		'name' => '协同事项 处理状态',
		'level' => '15',
		'dealstatus' => array(
			'1' => '待发事项',
			'2' => '已发事项',
			'3' => '已办事项',
		),
	),
	'secretlevel' => array(
		'remark' => '协同事项 保密程度',
		'status' => '1',
		'name' => '协同事项 保密程度',
		'level' => '15',
		'secretlevel' => array(
			'1' => '普通',
			'2' => '机密',
			'3' => '绝密',
		),
	),
	'urgentlevel' => array(
		'remark' => '协同事项 紧急程度',
		'status' => '1',
		'name' => '协同事项 紧急程度',
		'level' => '15',
		'urgentlevel' => array(
			'1' => '普通',
			'2' => '紧急',
			'3' => '特急',
		),
	),
	'instancedostatus' => array(
		'remark' => '协同事项审核状态',
		'status' => '1',
		'name' => '协同事项审核状态',
		'level' => '15',
		'instancedostatus' => array(
			'0' => '未处理',
			'1' => '已查看',
			'2' => '审核通过',
			'3' => '终止流程',
		),
	),
	'expensespaymethod' => array(
		'remark' => '报销支付类型',
		'status' => '1',
		'name' => '报销支付类型',
		'level' => '15',
		'expensespaymethod' => array(
			'1' => '现金',
			'2' => '转工资卡',
			'3' => '冲借款',
		),
	),
	'apptype' => array(
		'remark' => 'app应用类型',
		'status' => '1',
		'name' => 'app应用类型',
		'level' => '15',
		'apptype' => array(
			'1' => '办公应用',
			'2' => '个人应用',
			'3' => '网管工具',
			'4' => '快递查询',
			'5' => '休闲娱乐',
			'6' => '最新应用',
			'7' => '我的添加',
		),
	),
	'workplan' => array(
		'remark' => '工作计划',
		'status' => '1',
		'name' => '工作计划',
		'level' => '15',
		'workplan' => array(
			'1' => '日计划',
			'2' => '周计划',
			'3' => '月计划',
		),
	),
	'operation' => array(
		'remark' => '设备 库存查看',
		'status' => '1',
		'name' => '设备 库存查看',
		'level' => '15',
		'operation' => array(
			'1' => '添加',
			'2' => '修改',
			'3' => '申请',
			'4' => '异动',
			'5' => '归还',
		),
	),
	'operationdis' => array(
		'remark' => '设备 库存分布',
		'status' => '1',
		'name' => '设备 库存分布',
		'level' => '15',
		'operationdis' => array(
			'1' => '申请',
			'2' => '异动',
		),
	),
	'county' => array(
		'remark' => '所属区县',
		'status' => '1',
		'name' => '所属区县',
		'level' => '15',
		'county' => array(
			'渝中区' => '渝中区',
			'沙坪坝区' => '沙坪坝区',
			'江北区' => '江北区',
			'渝北区' => '渝北区',
			'南岸区' => '南岸区',
			'九龙坡区' => '九龙坡区',
			'大渡口区' => '大渡口区',
			'巴南区' => '巴南区',
			'北碚区' => '北碚区',
			'万州区' => '万州区',
			'涪陵区' => '涪陵区',
			'长寿区' => '长寿区',
			'黔江区' => '黔江区',
			'永川区' => '永川区',
			'江津区' => '江津区',
			'南川区' => '南川区',
			'合川区' => '合川区',
			'大足区' => '大足区',
			'綦江区' => '綦江区',
			'璧山区' => '璧山区',
			'潼南县' => '潼南县',
			'铜梁区' => '铜梁区',
			'荣昌区' => '荣昌区',
			'梁平县' => '梁平县',
			'城口县' => '城口县',
			'丰都县' => '丰都县',
			'垫江县' => '垫江县',
			'武隆县' => '武隆县',
			'忠县' => '忠县',
			'开县' => '开县',
			'云阳县' => '云阳县',
			'奉节县' => '奉节县',
			'巫山县' => '巫山县',
			'巫溪县' => '巫溪县',
			'石柱土家族自治县' => '石柱土家族自治县',
			'秀山土家族苗族自治县' => '秀山土家族苗族自治县',
			'酉阳土家族苗族自治县' => '酉阳土家族苗族自治县',
			'彭水苗族土家族自治县' => '彭水苗族土家族自治县',
		),
	),
	'clientsource' => array(
		'remark' => '客户来源',
		'status' => '1',
		'name' => '客户来源',
		'level' => '15',
		'clientsource' => array(
			'大众媒体' => '大众媒体',
			'网络' => '网络',
			'区县工商联' => '区县工商联',
			'区县中小企业局' => '区县中小企业局',
			'商会协会' => '商会协会',
			'园区' => '园区',
			'客户推荐' => '客户推荐',
			'其他' => '其他',
		),
	),
	'test' => array(
		'remark' => '木',
		'status' => '1',
		'name' => '木',
		'level' => '15',
		'test' => array(
			'2' => '苛',
		),
	),
	'roleinday' => array(
		'remark' => '提醒 时间',
		'status' => '1',
		'name' => NULL,
		'level' => '15',
		'roleinday' => array(
			'day' => '天',
			'month' => '月',
			'year' => '年',
		),
	),
	'ABC' => array(
		'remark' => 'ces',
		'status' => '1',
		'name' => '123456',
		'level' => '15',
		'ABC' => array(
			'' => '',
		),
	),
	'tool' => array(
		'remark' => '客户端类型',
		'status' => '1',
		'name' => '客户端类型',
		'level' => '15',
		'tool' => array(
			'1' => '网站',
			'2' => '移动端',
			'3' => '内部系统',
			'4' => '其他渠道',
		),
	),
	'businessstatus' => array(
		'remark' => '商机状态',
		'status' => '1',
		'name' => '商机状态',
		'level' => '15',
		'businessstatus' => array(
			'1' => '新建',
			'2' => '待受理',
			'3' => '已受理',
			'4' => '转项目',
			'5' => '转储备',
			'6' => '审核中',
		),
	),
	'endstatus' => array(
		'remark' => '是否超期',
		'status' => '1',
		'name' => '是否超期',
		'level' => '15',
		'endstatus' => array(
			'0' => '未超期',
			'1' => '已超期',
		),
	),
	'turnstatus' => array(
		'remark' => '是否转交',
		'status' => '1',
		'name' => '是否转交',
		'level' => '15',
		'turnstatus' => array(
			'0' => '未转交',
			'1' => '已转交',
		),
	),
	'projectstatus' => array(
		'remark' => '参照项目状态',
		'status' => '1',
		'name' => '参照项目状态',
		'level' => '15',
		'projectstatus' => array(
			'1' => '未完成',
			'2' => '进行中',
			'3' => '已完成',
		),
	),
	'YesOrNo' => array(
		'remark' => '标准是否判断',
		'status' => '1',
		'name' => '标准是否',
		'level' => '15',
		'YesOrNo' => array(
			'0' => '否',
			'1' => '是',
		),
	),
	'taskComplete' => array(
		'remark' => '项目是否完成',
		'status' => '1',
		'name' => '项目是否完成',
		'level' => '15',
		'taskComplete' => array(
			'0' => '未完成',
			'1' => '已完成',
		),
	),
	'systemRoamMas' => array(
		'remark' => '漫游数据类型',
		'status' => '1',
		'name' => '漫游数据类型',
		'level' => '15',
		'systemRoamMas' => array(
			'0' => '未选择类型',
			'1' => '新增',
			'2' => '修改',
			'3' => '删除',
			'4' => '生成单据',
		),
	),
	'typeOfReviewMeeting' => array(
		'remark' => '评审会类型',
		'status' => '1',
		'name' => '评审会类型',
		'level' => '15',
		'typeOfReviewMeeting' => array(
			'1' => '内部评审会',
			'2' => '专家评审会',
		),
	),
	'dateformatchoice' => array(
		'remark' => '日期格式',
		'status' => '1',
		'name' => '日期格式',
		'level' => '15',
		'dateformatchoice' => array(
			'1' => 'yyyy-MM-dd',
			'2' => 'yyyy-MM-dd HH:mm',
		),
	),
	'LD客户职务' => array(
		'remark' => 'LD客户职务',
		'status' => '1',
		'name' => 'enum001',
		'level' => '15',
		'LD客户职务' => array(
			'法定代表人' => '法定代表人',
			'总经理' => '总经理',
			'技术总监' => '技术总监',
			'财务总监' => '财务总监',
			'副总经理' => '副总经理',
		),
	),
	'LD证件类型' => array(
		'remark' => 'LD证件类型',
		'status' => '1',
		'name' => 'enum002',
		'level' => '15',
		'LD证件类型' => array(
			'身份证' => '身份证',
			'军官证' => '军官证',
		),
	),
	'LD性别' => array(
		'remark' => 'LD性别',
		'status' => '1',
		'name' => 'enum003',
		'level' => '15',
		'LD性别' => array(
			'男' => '男',
			'女' => '女',
			'未知' => '未知',
		),
	),
	'LD是否' => array(
		'remark' => 'LD是否',
		'status' => '1',
		'name' => 'enum004',
		'level' => '15',
		'LD是否' => array(
			'是' => '是',
			'否' => '否',
		),
	),
	'LD文化程度' => array(
		'remark' => 'LD文化程度',
		'status' => '1',
		'name' => 'enum005',
		'level' => '15',
		'LD文化程度' => array(
			'小学' => '小学',
			'初中' => '初中',
			'高中' => '高中',
			'大学' => '大学',
			'硕士' => '硕士',
			'博士' => '博士',
		),
	),
	'LD婚姻状况' => array(
		'remark' => 'LD婚姻状况',
		'status' => '1',
		'name' => 'nuem005',
		'level' => '15',
		'LD婚姻状况' => array(
			'未婚' => '未婚',
			'已婚' => '已婚',
			'未知' => '未知',
		),
	),
	'LD民族' => array(
		'remark' => 'LD民族',
		'status' => '1',
		'name' => 'nuem006',
		'level' => '15',
		'LD民族' => array(
			'汉族' => '汉族',
		),
	),
	'LD有无' => array(
		'remark' => 'LD有无',
		'status' => '1',
		'name' => 'nuem007',
		'level' => '15',
		'LD有无' => array(
			'有' => '有',
			'无' => '无',
		),
	),
	'LD借贷方向' => array(
		'remark' => 'LD借贷方向',
		'status' => '1',
		'name' => 'nuem008',
		'level' => '15',
		'LD借贷方向' => array(
			'借方' => '借方',
			'贷方' => '贷方',
		),
	),
	'ld00020' => array(
		'remark' => 'LD是否有效',
		'status' => '1',
		'name' => 'LD是否有效',
		'level' => '15',
		'ld00020' => array(
			'有效' => '有效',
			'无效' => '无效',
		),
	),
	'NDCH' => array(
		'remark' => '',
		'status' => '1',
		'name' => 'ND称呼',
		'level' => '15',
		'NDCH' => array(
			'先生' => '先生',
			'女士' => '女士',
			'小姐' => '小姐',
		),
	),
	'ndclqq' => array(
		'remark' => '',
		'status' => '1',
		'name' => 'ND材料是否齐全',
		'level' => '15',
		'ndclqq' => array(
			'材料齐全' => '材料齐全',
			'材料不全' => '材料不全',
		),
	),
	'sfty' => array(
		'remark' => '',
		'status' => '1',
		'name' => 'ND是否同意',
		'level' => '15',
		'sfty' => array(
			'同意' => '同意',
			'不同意' => '不同意',
		),
	),
	'ywyy' => array(
		'remark' => '',
		'status' => '1',
		'name' => 'ND是否有异议',
		'level' => '15',
		'ywyy' => array(
			'有异议' => '有异议',
			'无异议' => '无异议',
		),
	),
	'zsdbhwcqk' => array(
		'remark' => '',
		'status' => '1',
		'name' => 'ND正式担保函完成情况',
		'level' => '15',
		'zsdbhwcqk' => array(
			'未完成' => '未完成',
			'已完成' => '已完成',
		),
	),
	'misdrules' => array(
		'remark' => '',
		'status' => '1',
		'name' => '动态表单隐藏条件符',
		'level' => '15',
		'misdrules' => array(
			'1' => '==',
			'2' => '!=',
			'3' => '&gt;',
			'4' => '&gt;=',
			'5' => '&lt;',
			'6' => '&lt;=',
		),
	),
	'menu0021' => array(
		'remark' => '',
		'status' => '1',
		'name' => 'ND落实情况',
		'level' => '15',
		'menu0021' => array(
			'已落实' => '已落实',
			'已签订合同' => '已签订合同',
			'洽谈中' => '洽谈中',
		),
	),
	'menu00019' => array(
		'remark' => '逾期',
		'status' => '1',
		'name' => 'ND信用状况',
		'level' => '15',
		'menu00019' => array(
			'逾期' => '逾期',
			'不良' => '不良',
		),
	),
	'menu00020' => array(
		'remark' => '有效',
		'status' => '1',
		'name' => 'ND状态',
		'level' => '15',
		'menu00020' => array(
			'有效' => '有效',
			'无效' => '无效',
		),
	),
	'ListYesOrNo' => array(
		'remark' => '是否列表',
		'status' => '1',
		'name' => '是否列表',
		'level' => '15',
		'ListYesOrNo' => array(
			'0' => '单数据',
			'1' => '多数据',
		),
	),
	'pingshenfangshi' => array(
		'remark' => '评审方式',
		'status' => '1',
		'name' => '评审方式',
		'level' => '15',
		'pingshenfangshi' => array(
			'1' => '集中评审',
			'2' => '传签评审',
		),
	),
	'YesOrNoAgree' => array(
		'remark' => '是否同意',
		'status' => '1',
		'name' => '是否同意',
		'level' => '15',
		'YesOrNoAgree' => array(
			'1' => '同意',
			'2' => '不同意',
		),
	),
	'AppraisalOpinion' => array(
		'remark' => '评审意见',
		'status' => '1',
		'name' => '评审意见',
		'level' => '15',
		'AppraisalOpinion' => array(
			'1' => '同意',
			'2' => '不同意',
			'3' => '下次复议',
		),
	),
	'YesOrNoFinish' => array(
		'remark' => '完成情况',
		'status' => '1',
		'name' => '完成情况',
		'level' => '15',
		'YesOrNoFinish' => array(
			'1' => '进行中',
			'2' => '已完成',
			'3' => '已终止',
		),
	),
	'menu00022' => array(
		'remark' => '应收',
		'status' => '1',
		'name' => 'ND保证金类型',
		'level' => '15',
		'menu00022' => array(
			'应收' => '应收',
			'应付' => '应付',
		),
	),
	'StartOrForbidden' => array(
		'remark' => '',
		'status' => '1',
		'name' => '启用禁用',
		'level' => '15',
		'StartOrForbidden' => array(
			'1' => '启用',
			'0' => '禁用',
		),
	),
		
		'auditStateVal'=>array(
				'remark' => '审核状态',
				'status' => '1',
				'name' => '启用禁用',
				'level' => '15',
				'auditStateVal' => array(
						'0' => '新增',
						'1' => '启动',
						'2' => '审核中',
						'3' => '审核完毕',
						'-1' => '打回',
						'4' => '变更',
						
				),
		),
		'operateidVal'=>array(
				'remark' => '普通单据',
				'status' => '1',
				'name' => '启用禁用',
				'level' => '15',
				'operateidVal' => array(
						'0' => '未确认提交',
						'1' => '确认提交',
				),
		),
);

?>