<?php 
$aryType = array(
	'32' => array(
		'type' => '32',
		'typename' => '员工费用单',
		'modelname' => 'MisEmployeeExpens',
		'status' => '1',
	),
	'33' => array(
		'type' => '33',
		'typename' => '知识库管理',
		'modelname' => 'MisKnowledgeManage',
		'status' => '1',
	),
	'34' => array(
		'type' => '34',
		'typename' => '车辆申请单',
		'modelname' => 'MisRequestCar',
		'status' => '1',
	),
	'35' => array(
		'type' => '35',
		'typename' => '员工评估管理',
		'modelname' => 'MisHrPersonnelProbat',
		'status' => '1',
	),
	'40' => array(
		'type' => '40',
		'typename' => '导航首页模块分类',
		'modelname' => 'Group',
		'status' => '1',
	),
	'46' => array(
		'type' => '46',
		'typename' => '费用报销单',
		'modelname' => 'MisFinanceExpensesMas',
		'status' => '1',
	),
	'47' => array(
		'type' => '47',
		'typename' => '人事基本资料',
		'modelname' => 'MisHrPersonnelPersonInfo',
		'status' => '1',
	),
	'48' => array(
		'type' => '48',
		'typename' => '添加汽车信息',
		'modelname' => 'MisSystemCar',
		'status' => '1',
	),
	'59' => array(
		'type' => '59',
		'typename' => '员工请假',
		'modelname' => 'MisHrPersonnelLeaveInfo',
		'status' => '1',
	),
	'60' => array(
		'type' => '60',
		'typename' => '员工离职',
		'modelname' => 'MisHrPersonnelQuitInfo',
		'status' => '1',
	),
	'61' => array(
		'type' => '61',
		'typename' => '试用期评估考评',
		'modelname' => 'MisHrPersonnelProbationInfo',
		'status' => '1',
	),
	'64' => array(
		'type' => '64',
		'typename' => '短消息',
		'modelname' => 'MisMessage',
		'status' => '1',
	),
	'65' => array(
		'type' => '65',
		'typename' => '日程安排',
		'modelname' => 'MisUserEvents',
		'status' => '1',
	),
	'66' => array(
		'type' => '66',
		'typename' => '任务',
		'modelname' => 'MisTaskInformation',
		'status' => '1',
	),
	'67' => array(
		'type' => '67',
		'typename' => '工作报告',
		'modelname' => 'MisWorkStatement',
		'status' => '1',
	),
	'70' => array(
		'type' => '70',
		'typename' => '待阅工作报告',
		'modelname' => 'MisWorkReadStatement',
		'status' => '1',
	),
	'71' => array(
		'type' => '71',
		'typename' => '系统公告',
		'modelname' => 'MisSystemAnnouncement',
		'status' => '1',
	),
	'72' => array(
		'type' => '72',
		'typename' => '缺陷',
		'modelname' => 'MisTaskFeedbackInformation',
		'status' => '1',
	),
	'73' => array(
		'type' => '73',
		'typename' => '日常维护记录',
		'modelname' => 'MisLogisticsFixLog',
		'status' => '1',
	),
	'83' => array(
		'type' => '83',
		'typename' => '办公设备管理',
		'modelname' => 'MisWorkFacilityManage',
		'status' => '1',
	),
	'84' => array(
		'type' => '84',
		'typename' => '办公设备异动',
		'modelname' => 'MisWorkFacilityAbnormalmove',
		'status' => '1',
	),
	'85' => array(
		'type' => '85',
		'typename' => '会议管理',
		'modelname' => 'MisOaMeetingManage',
		'status' => '1',
	),
	'86' => array(
		'type' => '86',
		'typename' => '档案管理',
		'modelname' => 'MisOaArchivesManageMas',
		'status' => '1',
	),
	'87' => array(
		'type' => '87',
		'typename' => '特殊人员管理',
		'modelname' => 'MisBusinessSpecialEmployeeManage',
		'status' => '1',
	),
	'88' => array(
		'type' => '88',
		'typename' => '特殊车辆管理',
		'modelname' => 'MisBusinessSpecialCarManage',
		'status' => '1',
	),
	'89' => array(
		'type' => '89',
		'typename' => '人事合同管理',
		'modelname' => 'MisHrBasicEmployeeContract',
		'status' => '1',
	),
	'95'=>array(
		'type'=>'95',
		'typename'=>'发文拟稿',
		'modelname' => 'MisOfficialdocumentOut',
		'status' => '1',
			),
	'96'=>array(
			'type'=>'96',
			'typename'=>'收文登记',
			'modelname' => 'MisOfficialdocumentIn',
			'status' => '1',
	),
	'97'=>array(
			'type'=>'97',
			'typename'=>'特殊合同终止',
			'modelname' => 'MisBusinessContractTermination',
			'status' => '1',
	),
	'98'=>array(
			'type'=>'98',
			'typename'=>'专家问答',
			'modelname' => 'MisExpertquestionList',
			'status' => '1',
	),
	'99' => array(
			'type' => '99',
			'typename' => '工作计划',
			'modelname' => 'MisWorkPlan',
			'status' => '1',
	),
	'100' => array(
			'type' => '100',
			'typename' => '办公设备归还',
			'modelname' => 'MisWorkFacilityReturnMas',
			'status' => '1',
	),
);
?>