<?php 
return array(
	'0' => array(
		'name' => 'id',
		'showname' => '编号',
		'shows' => '1',
		'widths' => '33',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'id',
		'sortnum' => '1',
		'issearch' => '',
		'searchField' => '',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'isallsearch' => '',
		'searchsortnum' => '',
	),
		'1' => array(
				'name' => 'type',
				'showname' => '类型',
				'shows' => '1',
				'widths' => '',
				'sorts' => '0',
				'models' => '',
				'sortname' => 'type',
				'sortnum' => '2',
				'func' => array(
						'0' => array(
								'0' => 'excelTplselected',
						),
				),
				'funcdata' => array(
						'0' => array(
								'0' => array(
										'0' => '###',
										'1' => '0:个人,1:权限组',
								),
						),
				),
				'issearch' => '1',
				'searchField' => 'mis_authorize_project.type',
				'table' => '',
				'field' => '',
				'conditions' => '',
				'type' => 'text',
				'isallsearch' => '1',
				'searchsortnum' => '2',
		),
		'2' => array(
				'name' => 'objectname',
				'showname' => '对&nbsp;&nbsp;象',
				'shows' => '1',
				'widths' => '',
				'sorts' => '0',
				'models' => '',
				'sortname' => 'objectname',
				'sortnum' => '3',
				'issearch' => '1',
				'searchField' => 'mis_authorize_project.objectname',
				'table' => '',
				'field' => '',
				'conditions' => '',
				'type' => 'text',
				'isallsearch' => '1',
				'searchsortnum' => '3',
		),
	'3' => array(
		'name' => 'tablename',
		'showname' => '表&nbsp;&nbsp;名',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'tablename',
		'sortnum' => '4',
		'issearch' => '1',
		'searchField' => 'mis_authorize_project.tablename',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '1',
		'searchsortnum' => '4',
	),
	'4' => array(
		'name' => 'remark',
		'showname' => '备&nbsp;&nbsp;注',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'remark',
		'sortnum' => '5',
		'issearch' => '',
		'searchField' => 'mis_authorize_project.remark',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '',
		'searchsortnum' => '5',
	),
        '5' => array(
		'name' => 'modelname',
		'showname' => '模型名',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'modelname',
		'sortnum' => '6',
		'issearch' => '1',
		'searchField' => 'mis_authorize_project.modelname',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '1',
		'searchsortnum' => '6',
	),
       
        '6' => array(
		'name' => 'status',
		'showname' => '状&nbsp;&nbsp;态',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'status',
		'func' => array(
			'0' => array(
				'0' => 'getStatus',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
				),
			),
		),
		'sortnum' => '7',
		'issearch' => '',
		'searchField' => '',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'isallsearch' => '',
		'searchsortnum' => '',
	),
);

?>