<?php 
return array(
	'0' => array(
		'name' => 'id',
		'showname' => '序号',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'id',
		'sortnum' => '1',
		'issearch' => '0',
		'searchField' => '',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'isallsearch' => '0',
		'searchsortnum' => '0',
		'status' => '1',
	),
	'1' => array(
		'name' => 'account',
		'showname' => '用户名',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'account',
		'sortnum' => '2',
		'issearch' => '1',
		'searchField' => 'user.account',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '1',
		'searchsortnum' => '2',
		'status' => '1',
	),
	'2' => array(
		'name' => 'name',
		'showname' => '姓名',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'name',
		'sortnum' => '3',
		'issearch' => '0',
		'searchField' => 'user.name',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '1',
		'searchsortnum' => '3',
		'status' => '1',
	),
	'3' => array(
		'name' => 'sex',
		'showname' => '性别',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'sex',
		'func' => array(
			'0' => array(
				'0' => 'getS',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
				),
			),
		),
		'sortnum' => '4',
		'issearch' => '0',
		'searchField' => 'user.sex',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'radio|sex',
		'isallsearch' => '0',
		'searchsortnum' => '4',
		'status' => '1',
	),
	'4' => array(
		'name' => 'dept_id',
		'showname' => '部门',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => 'MisSystemDepartment',
		'sortname' => 'dept',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'MisSystemDepartment',
				),
			),
		),
		'sortnum' => '5',
		'issearch' => '1',
		'searchField' => 'user.dept_id',
		'table' => 'mis_system_department',
		'field' => 'id',
		'conditions' => '',
		'type' => 'db',
		'isallsearch' => '0',
		'searchsortnum' => '5',
		'status' => '1',
	),
	'5' => array(
		'name' => 'duty_id',
		'showname' => '职务',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => 'Duty',
		'sortname' => 'duty',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'Duty',
				),
			),
		),
		'sortnum' => '6',
		'issearch' => '1',
		'searchField' => 'user.duty_id',
		'table' => 'duty',
		'field' => 'id',
		'conditions' => 'status=1',
		'type' => 'db',
		'isallsearch' => '0',
		'searchsortnum' => '6',
		'status' => '1',
	),
);

?>