<?php 
return array(
	'1' => array(
		'name' => 'id',
		'showname' => 'ID',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'id',
		'sortnum' => '1',
		'searchField' => '',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '0',
		'status' => '1',
		'isexport' => '1',
	),
	'2' => array(
		'name' => 'planid',
		'showname' => '计划名称',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'mis_performance_plan',
				),
			),
		),
		'sortname' => 'planid',
		'sortnum' => '2',
		'searchField' => 'mis_performance_assess.planid',
		'field' => 'id',
		'conditions' => '',
		'type' => 'db',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '2',
		'status' => '1',
		'table' => 'mis_performance_plan',
		'isexport' => '1',
	),
	'3' => array(
		'name' => 'byuser',
		'showname' => '被考核人',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'mis_hr_personnel_person_info',
				),
			),
		),
		'sortname' => 'byuser',
		'sortnum' => '3',
		'searchField' => 'mis_performance_assess.byuser',
		'field' => 'id',
		'conditions' => '',
		'type' => 'db',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '3',
		'status' => '1',
		'table' => 'mis_hr_personnel_person_info',
		'isexport' => '1',
	),
	'4' => array(
		'name' => 'deptname',
		'showname' => '部门',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
				'1' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '#byuser#',
					'1' => 'id',
					'2' => 'deptid',
					'3' => 'mis_hr_personnel_person_info',
				),
				'1' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'MisSystemDepartment', 
				),
			),
		),
		'sortname' => 'deptname',
		'sortnum' => '4',
		'searchField' => 'mis_performance_assess.byuser',
		'field' => 'id,deptid',
		'conditions' => '',
		'type' => 'db|name,deptid',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '4',
		'status' => '1',
		'table' => 'mis_system_department,mis_hr_personnel_person_info',
		'isexport' => '1',
	),
	'5' => array(
		'name' => 'dutyname',
		'showname' => '职级',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
				'1' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '#byuser#',
					'1' => 'id',
					'2' => 'dutylevelid',
					'3' => 'MisHrBasicEmployee',
				),
				'1' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'Duty',
				),
			),
		),
		'sortname' => 'dutyname',
		'sortnum' => '5',
		'searchField' => 'mis_performance_assess.byuser',
		'field' => 'id,dutylevelid',
		'conditions' => '',
		'type' => 'db|name,dutylevelid',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '5',
		'status' => '1',
		'table' => 'duty,mis_hr_personnel_person_info',
		'isexport' => '1',
	),
	'6' => array(
		'name' => 'totalscore',
		'showname' => '计算总分',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'totalscore',
		'sortnum' => '6',
		'searchField' => 'mis_performance_assess.totalscore',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '6',
		'status' => '1',
		'isexport' => '1',
	),
	'7' => array(
		'name' => 'amendscore',
		'showname' => '修正总分',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'amendscore',
		'sortnum' => '7',
		'searchField' => 'mis_performance_assess.amendscore',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '7',
		'status' => '1',
		'isexport' => '1',
	),
	'8' => array(
		'name' => 'level',
		'showname' => '等级',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'level',
		'sortnum' => '8',
		'issearch' => '0',
		'searchField' => 'mis_performance_assess.level',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '8',
		'status' => '1',
		'isexport' => '1',
	),
	'9' => array(
		'name' => 'comments',
		'showname' => '评语',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'comments',
		'sortnum' => '9',
		'searchField' => 'mis_performance_assess.comments',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '9',
		'status' => '1',
		'isexport' => '1',
	),
	'10' => array(
		'name' => 'conclusions',
		'showname' => '总结',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'conclusions',
		'sortnum' => '10',
		'searchField' => 'mis_performance_assess.conclusions',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '10',
		'status' => '1',
		'isexport' => '1',
	),
);

?>