<?php 
return array(
	'0' => array(
		'name' => 'id',
		'showname' => 'ID',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'title',
		'sortnum' => '1',
		'issearch' => '1',
		'searchField' => 'mis_system_data_roam_mas.id',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '1',
		'searchsortnum' => '1',
		'status' => '1',
		'rules' => '0',
		'message' => '0',
	),
	'1' => array(
		'name' => 'title',
		'showname' => '漫游名称',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'title',
		'sortnum' => '2',
		'issearch' => '1',
		'searchField' => 'mis_system_data_roam_mas.title',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '1',
		'searchsortnum' => '3',
		'status' => '1',
		'rules' => '0',
		'message' => '0',
	),
	'2' => array(
		'name' => 'sourcename',
		'showname' => '来源model',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'sourcename',
		'sortnum' => '3',
		'issearch' => '1',
		'searchField' => 'mis_system_data_roam_mas.sourcename',
		'table' => 'mis_system_data_roam_mas',
		'field' => 'sourcename',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '1',
		'searchsortnum' => '3',
		'status' => '1',
		'rules' => '0',
		'message' => '0',
	),
	'3' => array(
		'name' => 'targetname',
		'showname' => '目标model',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'targetname',
		'sortnum' => '4',
		'issearch' => '1',
		'searchField' => 'mis_system_data_roam_mas.targetname',
		'table' => 'mis_system_data_roam_mas',
		'field' => 'targetname',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '1',
		'searchsortnum' => '3',
		'status' => '1',
		'rules' => '0',
		'message' => '0',
	),
	'4' => array(
		'name' => 'isbindsettable',
		'showname' => '漫游类型',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'isbindsettable',
		'sortnum' => '5',
		'func' => array(
				'0' => array(
						'0' => 'excelTplselected',
				),
		),
		'funcdata' => array(
				'0' => array(
						'0' => array(
								'0' => '###',
								'1' => '0:普通漫游,1:套表漫游,2:子流程漫游',
						),
				),
		),
		'issearch' => '1',
		'searchField' => 'mis_system_data_roam_mas.isbindsettable',
		'table' => 'excelTplselected',
		'field' => 'isbindsettable',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '1',
		'searchsortnum' => '3',
		'status' => '1',
		'rules' => '0',
		'message' => '0',
 	),
// 	'4' => array(
// 		'name' => 'sourcetype',
// 		'showname' => '来源动作',
// 		'shows' => '1',
// 		'widths' => '',
// 		'sorts' => '0',
// 		'models' => '',
// 		'sortname' => 'sourcetype',
// 		'sortnum' => '5',
// 		'issearch' => '1',
// 		'searchField' => 'mis_system_data_roam_mas.sourcetype',
// 		'table' => 'excelTplselected',
// 		'field' => 'sourcetype',
// 		'conditions' => '',
// 		'type' => 'text',
// 		'isallsearch' => '1',
// 		'searchsortnum' => '3',
// 		'status' => '1',
// 		'rules' => '0',
// 		'message' => '0',
// 	),
// 	'5' => array(
// 		'name' => 'targettype',
// 		'showname' => '目标动作',
// 		'shows' => '1',
// 		'widths' => '',
// 		'sorts' => '0',
// 		'models' => '',
// 		'sortname' => 'tragettype',
// 		'sortnum' => '6',
// 		'issearch' => '1',
// 		'searchField' => 'mis_system_data_roam_mas.targettype',
// 		'table' => 'excelTplselected',
// 		'field' => 'targettype',
// 		'conditions' => '',
// 		'type' => 'text',
// 		'isallsearch' => '1',
// 		'searchsortnum' => '3',
// 		'status' => '1',
// 		'rules' => '0',
// 		'message' => '0',
// 		'func' => array(
// 			'0' => array(
// 				'0' => 'excelTplselected',
// 			),
// 		),
// 		'funcdata' => array(
// 			'0' => array(
// 				'0' => array(
// 					'0' => '###',
// 					'1' => '1:新增,2:修改,3:删除,4:生成表单',
// 				),
// 			),
// 		),
// 	),
	'9' => array(
		'name' => 'action',
		'showname' => '操作',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'status',
		'func' => array(
			'0' => array(
				'0' => 'showStatus',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '#status#',
					'1' => '#id#',
				),
			),
		),
		'sortnum' => '7',
		'searchField' => '',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '0',
	),
);

?>