<?php 
return array(
	'0' => array(
		'name' => 'id',
		'showname' => '序号',
		'shows' => '0',
		'widths' => '30',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'id',
		'sortnum' => '1',
		'issearch' => '0',
		'searchField' => 'mis_work_monitoring.id',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'isallsearch' => '0',
		'searchsortnum' => '0',
		'status' => '1',
		'isexport' => '0',
	),
	'1' => array(
		'name' => 'tablename',
		'showname' => '工作名称',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'tablename',
		'sortnum' => '2',
		'issearch' => '1',
		'searchField' => 'mis_work_monitoring.tablename',
		'table' => 'node',
		'field' => 'name',
		'conditions' => '',
		'type' => 'db|title',
		'isallsearch' => '1',
		'searchsortnum' => '1',
		'status' => '1',
		'isexport' => '1',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'name',
					'2' => 'title',
					'3' => 'node',
				),
			),
		),
	),
	'2' => array(
		'name' => 'orderno',
		'showname' => '工作编号',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'orderno',
		'sortnum' => '3',
		'issearch' => '1',
		'searchField' => 'mis_work_monitoring.orderno',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '1',
		'searchsortnum' => '2',
		'status' => '1',
		'isexport' => '1',
	),
	'3' => array(
		'name' => 'ptmptid',
		'showname' => '当前流程',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'ptmptid',
		'sortnum' => '5',
		'issearch' => '1',
		'searchField' => 'mis_work_monitoring.ptmptid',
		'table' => 'process_info_form',
		'field' => 'id',
		'conditions' => '',
		'type' => 'db',
		'isallsearch' => '1',
		'searchsortnum' => '3',
		'status' => '1',
		'isexport' => '1',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'process_info_form',
				),
			),
		),
	),
	'title' => array(
			'name' => 'title',
			'showname' => '标题大概',
			'shows' => '1',
			'widths' => '',
			'sorts' => '0',
			'models' => '',
			'sortname' => 'title',
			'sortnum' => '4',
			'issearch' => '1',
			'searchField' => 'mis_work_monitoring.title',
			'table' => '',
			'field' => '',
			'conditions' => '',
			'type' => 'text',
			'isallsearch' => '1',
			'searchsortnum' => '2',
			'status' => '1',
			'isexport' => '1',
	),
	'projectid' => array(
		'name' => 'projectid',
		'showname' => '项目名称',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'projectid',
		'sortnum' => '4',
		'issearch' => '1',
		'searchField' => 'mis_work_monitoring.projectid',
		'table' => 'mis_auto_kimpu',
		'field' => 'id',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'mis_auto_kimpu',
				),
			),
		),
		'conditions' => '',
		'type' => 'db|name',
		'isallsearch' => '1',
		'searchsortnum' => '2',
		'status' => '1',
		'isexport' => '1',
	),
	'5' => array(
		'name' => 'createid',
		'showname' => '发起人',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'createtime',
		'sortnum' => '6',
		'issearch' => '1',
		'searchField' => 'mis_work_monitoring.createid',
		'table' => 'user',
		'field' => 'id',
		'conditions' => '',
		'type' => 'db',
		'isallsearch' => '1',
		'searchsortnum' => '5',
		'status' => '1',
		'isexport' => '1',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'user',
				),
			),
		),
	),
	'6' => array(
		'name' => 'createtime',
		'showname' => '到达时间',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'createtime',
		'sortnum' => '7',
		'issearch' => '1',
		'searchField' => 'mis_work_monitoring.createtime',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'time',
		'isallsearch' => '1',
		'searchsortnum' => '6',
		'status' => '1',
		'isexport' => '1',
		'func' => array(
			'0' => array(
				'0' => 'transTime',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'Y-m-d H:i:s',
				),
			),
		),
	),
	'7' => array(
		'name' => 'userid',
		'showname' => '办理人',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'userid',
		'sortnum' => '8',
		'issearch' => '1',
		'searchField' => 'mis_work_monitoring.userid',
		'table' => 'user',
		'field' => 'id',
		'conditions' => '',
		'type' => 'db',
		'isallsearch' => '1',
		'searchsortnum' => '7',
		'status' => '1',
		'isexport' => '1',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'user',
				),
			),
		),
	),
	'8' => array(
		'name' => 'dotime',
		'showname' => '办理时间',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'dotime',
		'sortnum' => '9',
		'issearch' => '1',
		'searchField' => 'mis_work_monitoring.dotime',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'time',
		'isallsearch' => '1',
		'searchsortnum' => '8',
		'status' => '1',
		'isexport' => '1',
		'func' => array(
			'0' => array(
				'0' => 'transTime',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'Y-m-d H:i:s',
				),
			),
		),
	),
	'9' => array(
		'name' => 'timeout',
		'showname' => '停留时间',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'timeout',
		'sortnum' => '10',
		'issearch' => '0',
		'searchField' => 'mis_work_monitoring.timeout',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '9',
		'status' => '1',
		'isexport' => '1',
		'func' => array(
			'0' => array(
				'0' => 'getCHStimeDifference',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '#createtime#',
					'1' => '#dotime#',
				),
			),
		),
	),
	'10' => array(
		'name' => 'doinfo',
		'showname' => '办理意见',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'doinfo',
		'sortnum' => '11',
		'issearch' => '1',
		'searchField' => 'mis_work_monitoring.doinfo',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '1',
		'searchsortnum' => '10',
		'status' => '1',
		'isexport' => '1',
	),
);

?>