<?php 
return array(
	'0' => array(
		'name' => 'code',
		'showname' => '类型编码',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'code',
		'sortnum' => '1',
		'issearch' => '1',
		'searchField' => 'mis_finance_expenses_type.code',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '1',
		'searchsortnum' => '1',
	),
	'1' => array(
		'name' => 'name',
		'showname' => '类型编码',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'name',
		'func' => array(
			'0' => array(
				'0' => 'getnextUrl',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => '#id#',
					'2' => 'parentid',
					'3' => 'index',
					'4' => '###',
				),
			),
		),
		'sortnum' => '2',
		'issearch' => '',
		'searchField' => 'mis_finance_expenses_type.name',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '',
		'searchsortnum' => '3',
	),
	'2' => array(
		'name' => 'name',
		'showname' => '搜索名称',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'name',
		'func' => array(
			'0' => array(
				'0' => 'getnextUrl',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => '#id#',
					'2' => 'parentid',
					'3' => 'index',
					'4' => '###',
				),
			),
		),
		'sortnum' => '3',
		'issearch' => '',
		'searchField' => 'mis_finance_expenses_type.name',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '',
		'searchsortnum' => '3',
	),
	'3' => array(
		'name' => 'accountcode',
		'showname' => '关联科目编码',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'accountid',
		'sortnum' => '4',
		'issearch' => '1',
		'searchField' => 'mis_finance_expenses_type.accountid',
		'table' => 'mis_finance_amount_title',
		'field' => 'id',
		'conditions' => '',
		'type' => 'db|code',
		'isallsearch' => '1',
		'searchsortnum' => '4',
	),
	'4' => array(
		'name' => 'accountname',
		'showname' => '关联科目名称',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'accountid',
		'sortnum' => '5',
		'issearch' => '1',
		'searchField' => 'mis_finance_expenses_type.accountid',
		'table' => 'mis_finance_amount_title',
		'field' => 'id',
		'conditions' => '',
		'type' => 'db',
		'isallsearch' => '1',
		'searchsortnum' => '5',
	),
	'5' => array(
		'name' => 'remark',
		'showname' => '备注',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'remark',
		'sortnum' => '6',
		'issearch' => '1',
		'searchField' => 'mis_finance_expenses_type.remark',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '1',
		'searchsortnum' => '6',
	),
	'6' => array(
		'name' => 'status',
		'showname' => '状态',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'status',
		'func' => array(
			'0' => array(
				'0' => 'getStatus',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
				),
			),
		),
		'sortnum' => '7',
		'issearch' => '',
		'searchField' => '',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'isallsearch' => '',
		'searchsortnum' => '',
	),
	'7' => array(
		'name' => 'action',
		'showname' => '操作',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'func' => array(
			'0' => array(
				'0' => 'showStatus',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '#status#',
					'1' => '#id#',
				),
			),
		),
		'sortname' => 'status',
		'sortnum' => '8',
		'issearch' => '',
		'searchField' => '',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'isallsearch' => '',
		'searchsortnum' => '',
	),
);

?>