<?php 
return array(
	'id' => array(
		'name' => 'id',
		'showname' => 'ID',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'id',
		'sortnum' => '1',
		'issearch' => '1',
		'searchField' => 'mis_system_company.id',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '1',
		'searchsortnum' => '3',
		'status' => '1',
		'rules' => '0',
		'message' => '0',
	),
	'name' => array(
		'name' => 'name',
		'showname' => '公司名称',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'name',
		'sortnum' => '2',
		'issearch' => '1',
		'searchField' => 'mis_system_company.name',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '1',
		'searchsortnum' => '3',
		'status' => '1',
		'rules' => '0',
		'message' => '0',
	),
	'orderno' => array(
		'name' => 'orderno',
		'showname' => '公司编码',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'orderno',
		'sortnum' => '1',
		'issearch' => '1',
		'searchField' => 'mis_system_company.orderno',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '1',
		'searchsortnum' => '3',
		'status' => '1',
		'rules' => '0',
		'message' => '0',
	),
	'juridicalperson' => array(
		'name' => 'juridicalperson',
		'showname' => '法人',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'juridicalperson',
		'sortnum' => '3',
		'issearch' => '1',
		'searchField' => 'mis_system_company.juridicalperson',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '1',
		'searchsortnum' => '4',
		'status' => '1',
		'rules' => '0',
		'message' => '0',
	),
	'address' => array(
		'name' => 'address',
		'showname' => '公司地址',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'address',
		'sortnum' => '4',
		'issearch' => '1',
		'searchField' => 'mis_system_company.address',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '1',
		'searchsortnum' => '5',
		'status' => '1',
		'rules' => '0',
		'message' => '0',
	),
	'tel' => array(
		'name' => 'tel',
		'showname' => '联系电话',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'tel',
		'sortnum' => '6',
		'issearch' => '',
		'searchField' => 'mis_system_company.tel',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '',
		'searchsortnum' => '6',
		'status' => '1',
		'rules' => '0',
		'message' => '0',
	),
	'fax' => array(
		'name' => 'fax',
		'showname' => '传真',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'fax',
		'sortnum' => '7',
		'issearch' => '',
		'searchField' => 'mis_system_company.fax',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '',
		'searchsortnum' => '7',
		'status' => '1',
		'rules' => '0',
		'message' => '0',
	),
	'website' => array(
		'name' => 'website',
		'showname' => '网站',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'website',
		'sortnum' => '8',
		'issearch' => '',
		'searchField' => 'mis_system_company.website',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '',
		'searchsortnum' => '8',
		'status' => '1',
		'rules' => '0',
		'message' => '0',
	),
	'orgcode' => array(
		'name' => 'orgcode',
		'showname' => '组织机构代码',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'orgcode',
		'sortnum' => '9',
		'issearch' => '',
		'searchField' => 'mis_system_company.orgcode',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '',
		'searchsortnum' => '9',
		'status' => '1',
		'rules' => '0',
		'message' => '0',
	),
	'dutyregno' => array(
		'name' => 'dutyregno',
		'showname' => '税务登记号',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'dutyregno',
		'sortnum' => '10',
		'issearch' => '',
		'searchField' => 'mis_system_company.dutyregno',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '',
		'searchsortnum' => '10',
		'status' => '1',
		'rules' => '0',
		'message' => '0',
	),
	'bankid' => array(
		'name' => 'bankid',
		'showname' => '开户银行',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => 'MisFinanceBank',
		'sortname' => 'bankid',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'MisFinanceBank',
				),
			),
		),
		'sortnum' => '20',
		'issearch' => '',
		'searchField' => 'mis_system_company.bankid',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '',
		'searchsortnum' => '20',
		'status' => '1',
		'rules' => '0',
		'message' => '0',
	),
	'bank' => array(
		'name' => 'bank',
		'showname' => '银行账号',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'bank',
		'sortnum' => '21',
		'issearch' => '',
		'searchField' => 'mis_system_company.bank',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '',
		'searchsortnum' => '21',
		'status' => '1',
		'rules' => '0',
		'message' => '0',
	),
	'action' => array(
		'name' => 'action',
		'showname' => '操作',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'status',
		'sortnum' => '23',
		'issearch' => '',
		'searchField' => '',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'isallsearch' => '',
		'searchsortnum' => '',
		'status' => '1',
		'extention_html_end' => array(
			'0' => ' ',
		),
		'func' => array(
			'0' => array(
				'0' => 'getOperateStatus',
			),
			'1' => array(
				'0' => 'getStatus',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '#createid#',
					'1' => '#auditState#',
					'2' => 'id/#id#',
					'3' => '',
					'4' => '',
					'5' => 'dialog',
					'6' => '公司信息',
					'7' => '',
					'8' => '500',
				),
			),
			'1' => array(
				'0' => array(
					'0' => '#status#',
				),
			),
		),
		'rules' => '0',
		'message' => '0',
	),
);

?>