<?php 
return array(
	'0' => array(
		'name' => 'id',
		'showname' => '编号',
		'shows' => '1',
		'widths' => '33',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'id',
		'sortnum' => '1',
		'issearch' => '',
		'searchField' => '',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'isallsearch' => '',
		'searchsortnum' => '',
		'status' => '1',
	),
	'2' => array(
		'name' => 'exacttable',
		'showname' => '关联模式',
		'shows' => '1',
		'widths' => '33',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'id',
		'sortnum' => '2',
		'issearch' => '',
		'searchField' => '',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'isallsearch' => '',
		'searchsortnum' => '',
		'status' => '1',
	),
	'1' => array(
		'name' => 'type',
		'showname' => '类型',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'userid',
		'sortnum' => '3',
		'func' => array(
			'0' => array(
				'0' => 'excelTplselected',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => '0:个人,1:权限组',
				),
			),
		),
		'issearch' => '1',
		'searchField' => 'mis_authorize_special.type',
		'table' => 'user',
		'field' => 'id',
		'conditions' => '',
		'type' => 'db',
		'isallsearch' => '1',
		'searchsortnum' => '2',
		'status' => '1',
	),
	'3' => array(
		'name' => 'tablename',
		'showname' => '表  名',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'tablename',
		'sortnum' => '4',
		'issearch' => '1',
		'searchField' => 'mis_authorize_special.tablename',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '1',
		'searchsortnum' => '3',
		'status' => '1',
	),
	'5' => array(
		'name' => 'remark',
		'showname' => '备  注',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'remark',
		'sortnum' => '5',
		'issearch' => '',
		'searchField' => 'mis_authorize_special.remark',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '',
		'searchsortnum' => '4',
		'status' => '1',
	),
	'4' => array(
		'name' => 'conditions',
		'showname' => '条  件',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'conditions',
		'sortnum' => '6',
		'issearch' => '1',
		'searchField' => 'mis_authorize_special.conditions',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '1',
		'searchsortnum' => '4',
		'status' => '1',
	),
	'6' => array(
		'name' => 'modelname',
		'showname' => '模型名',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'modelname',
		'sortnum' => '7',
		'issearch' => '1',
		'searchField' => 'mis_authorize_special.modelname',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '1',
		'searchsortnum' => '3',
		'status' => '1',
	),
	'7' => array(
		'name' => 'methodname',
		'showname' => '方法名',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'methodname',
		'sortnum' => '8',
		'issearch' => '1',
		'searchField' => 'mis_authorize_special.methodname',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '1',
		'searchsortnum' => '3',
		'status' => '1',
	),
	'8' => array(
		'name' => 'status',
		'showname' => '状  态',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'status',
		'func' => array(
			'0' => array(
				'0' => 'getStatus',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
				),
			),
		),
		'sortnum' => '9',
		'issearch' => '',
		'searchField' => '',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'isallsearch' => '',
		'searchsortnum' => '',
		'status' => '1',
	),
);

?>