<?php 
return array(
	'0' => array(
		'name' => 'id',
		'showname' => 'ID',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'id',
		'sortnum' => '1',
		'searchField' => '',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '0',
	),
	'1' => array(
		'name' => 'upname',
		'showname' => '附件名',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'upname',
		'sortnum' => '2',
		'searchField' => 'mis_attached_record.upname',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '0',
	),
	'2' => array(
		'name' => 'orderid',
		'showname' => '附件所在的单据编号',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'orderid',
		'sortnum' => '3',
		'searchField' => 'mis_attached_record.orderid',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '0',
	),
	'3' => array(
		'name' => 'tablename',
		'showname' => '附件所在的模块名',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'tablename',
		'sortnum' => '4',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'name',
					'2' => 'title',
					'3' => 'node',
				),
			),
		),
		'searchField' => 'mis_attached_record.tablename',
		'table' => 'node',
		'field' => 'name',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '0',
	),
	'4' => array(
		'name' => 'createid',
		'showname' => '上传人',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'createid',
		'sortnum' => '5',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'user',
				),
			),
		),
		'searchField' => 'mis_attached_record.createid',
		'table' => 'user',
		'field' => 'id',
		'conditions' => '',
		'type' => 'db',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '0',
	),
	'5' => array(
		'name' => 'createtime',
		'showname' => '上传时间',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'createtime',
		'sortnum' => '6',
		'func' => array(
			'0' => array(
				'0' => 'transTime',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
				),
			),
		),
		'searchField' => 'mis_attached_record.createtime',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'time',
		'issearch' => '1',
		'isallsearch' => '0',
		'searchsortnum' => '0',
	),
	'6' => array(
		'name' => 'action',
		'showname' => '下载',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'status',
		'sortnum' => '7',
		'extention_html_end' => array(
			'0' => ' ',
		),
		'func' => array(
			'0' => array(
				'0' => 'download',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '#status#',
					'1' => '#attached#',
				),
			),
		),
		'searchField' => '',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '0',
	),
	'7' => array(
		'name' => 'attached',
		'showname' => '附件地址',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'attached',
		'sortnum' => '8',
		'searchField' => 'mis_attached_record.attached',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '0',
	),
	'orderno'=> array(
		'name' => 'orderno',
		'showname' => '文档编号',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'orderno',
		'sortnum' => '9',
		'searchField' => 'mis_attached_record.orderno',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '0',
	),	
	'position'=> array(
			'name' => 'position',
			'showname' => '文档位置',
			'shows' => '1',
			'widths' => '',
			'sorts' => '0',
			'models' => '',
			'sortname' => 'position',
			'sortnum' => '10',
			'searchField' => 'mis_attached_record.position',
			'table' => '',
			'field' => '',
			'conditions' => '',
			'type' => 'text',
			'issearch' => '0',
			'isallsearch' => '0',
			'searchsortnum' => '0',
	),
	'page'=> array(
			'name' => 'page',
			'showname' => '文档页数',
			'shows' => '1',
			'widths' => '',
			'sorts' => '0',
			'models' => '',
			'sortname' => 'page',
			'sortnum' => '11',
			'searchField' => 'mis_attached_record.page',
			'table' => '',
			'field' => '',
			'conditions' => '',
			'type' => 'text',
			'issearch' => '0',
			'isallsearch' => '0',
			'searchsortnum' => '0',
	),
	'remark'=> array(
			'name' => 'remark',
			'showname' => '备注',
			'shows' => '1',
			'widths' => '',
			'sorts' => '0',
			'models' => '',
			'sortname' => 'remark',
			'sortnum' => '9',
			'searchField' => 'mis_attached_record.remark',
			'table' => '',
			'field' => '',
			'conditions' => '',
			'type' => 'text',
			'issearch' => '0',
			'isallsearch' => '0',
			'searchsortnum' => '0',
	),
);

?>