<?php 
return array(
	'0' => array(
		'name' => 'id',
		'showname' => '编号',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'id',
		'sortnum' => '1',
		'issearch' => '',
		'searchField' => '',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'isallsearch' => '',
		'searchsortnum' => '',
		'status' => '1',
	),
	'1' => array(
		'name' => 'account',
		'showname' => '用户名',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'account',
		'sortnum' => '2',
		'issearch' => '1',
		'searchField' => 'user.account',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '1',
		'searchsortnum' => '2',
		'status' => '1',
	),
	'2' => array(
		'name' => 'name',
		'showname' => '姓名',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'name',
		'sortnum' => '3',
		'issearch' => '1',
		'searchField' => 'user.name',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '1',
		'searchsortnum' => '3',
		'status' => '1',
	),
	'3' => array(
		'name' => 'sex',
		'showname' => '性别',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'sex',
		'func' => array(
			'0' => array(
				'0' => 'getS',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
				),
			),
		),
		'sortnum' => '4',
		'issearch' => '1',
		'searchField' => 'user.sex',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'radio|sex',
		'isallsearch' => '',
		'searchsortnum' => '4',
		'status' => '1',
	),
	'4' => array(
		'name' => 'dept_id',
		'showname' => '部门',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => 'MisSystemDepartment',
		'sortname' => 'dept',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'MisSystemDepartment',
				),
			),
		),
		'sortnum' => '5',
		'issearch' => '1',
		'searchField' => 'user.dept_id',
		'table' => 'mis_system_department',
		'field' => 'id',
		'conditions' => '',
		'type' => 'db',
		'isallsearch' => '1',
		'searchsortnum' => '5',
		'status' => '1',
	),
	'5' => array(
		'name' => 'duty_id',
		'showname' => '职务',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => 'Duty',
		'sortname' => 'duty',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'Duty',
				),
			),
		),
		'sortnum' => '6',
		'issearch' => '1',
		'searchField' => 'user.duty_id',
		'table' => 'duty',
		'field' => 'id',
		'conditions' => 'status=1',
		'type' => 'db',
		'isallsearch' => '1',
		'searchsortnum' => '6',
		'status' => '1',
	),
	'6' => array(
		'name' => 'orderdisplay',
		'showname' => '个人单据浏览权限',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'orderdisplay',
		'func' => array(
			'0' => array(
				'0' => 'getViewpermissions',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
				),
			),
		),
		'sortnum' => '7',
		'issearch' => '',
		'searchField' => 'user.orderdisplay',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '',
		'searchsortnum' => '7',
		'status' => '1',
	),
	'7' => array(
		'name' => 'mobile',
		'showname' => 'mobile',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'mobile',
		'sortnum' => '8',
		'issearch' => '',
		'searchField' => 'user.mobile',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '',
		'searchsortnum' => '8',
		'status' => '1',
	),
	'8' => array(
		'name' => 'email',
		'showname' => 'Email',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'email',
		'sortnum' => '9',
		'issearch' => '',
		'searchField' => 'user.email',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '',
		'searchsortnum' => '9',
		'status' => '1',
	),
	'9' => array(
		'name' => 'work_date',
		'showname' => '入职时间',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'work_date',
		'func' => array(
			'0' => array(
				'0' => 'transTime',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
				),
			),
		),
		'sortnum' => '10',
		'issearch' => '1',
		'searchField' => 'user.work_date',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'time',
		'isallsearch' => '',
		'searchsortnum' => '10',
		'status' => '1',
	),
	'10' => array(
		'name' => 'last_login_time',
		'showname' => '上次登录',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'last_login_time',
		'func' => array(
			'0' => array(
				'0' => 'transTime',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
				),
			),
		),
		'sortnum' => '11',
		'issearch' => '',
		'searchField' => 'user.last_login_time',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '',
		'searchsortnum' => '11',
		'status' => '1',
	),
	'11' => array(
		'name' => 'login_count',
		'showname' => '登录次数',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'login_count',
		'sortnum' => '12',
		'issearch' => '',
		'searchField' => 'user.login_count',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '',
		'searchsortnum' => '12',
		'status' => '1',
	),
	'12' => array(
		'name' => 'remark',
		'showname' => '备注',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'remark',
		'sortnum' => '13',
		'issearch' => '',
		'searchField' => 'user.remark',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '',
		'searchsortnum' => '13',
		'status' => '1',
	),
	'13' => array(
		'name' => 'status',
		'showname' => '状态',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'status',
		'func' => array(
			'0' => array(
				'0' => 'getStatus',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
				),
			),
		),
		'sortnum' => '14',
		'issearch' => '',
		'searchField' => '',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'isallsearch' => '',
		'searchsortnum' => '',
		'status' => '1',
	),
	'14' => array(
		'name' => 'action',
		'showname' => '操作',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'status',
		'sortnum' => '15',
		'issearch' => '',
		'searchField' => '',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'isallsearch' => '',
		'searchsortnum' => '',
		'status' => '1',
		'func' => array(
			'0' => array(
				'0' => 'getBaseRole',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '#id#',
					'1' => '#name#',
				),
			),
		),
	),
);

?>