<?php 
return array(
	'0' => array(
		'name' => 'id',
		'showname' => '编号',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'id',
		'sortnum' => '1',
		'issearch' => '0',
		'isexport' => '1',
		'searchField' => '',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'isallsearch' => '0',
		'searchsortnum' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '0',	
		'helpvalue' => '',
	),
	 
	'2' => array(
		'name' => 'modelname',
		'showname' => '模型名称',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'modelname',
		'sortnum' => '3',
		'issearch' => '1',
		'isexport' => '1',
		'searchField' => 'mis_system_sysremind.modelname',
		'table' => 'node',
		'field' => 'name',
		'conditions' => '',
		'type' => 'db|title',
		'isallsearch' => '0',
		'searchsortnum' => '3',
		'status' => '1',
		'rules' => '1',
		'message' => '0',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'name',
					'2' => 'title',
					'3' => 'node',
				),
			),
		),
		'helpvalue' => '',
	),
	'3' => array(
			'name' => 'content',
			'showname' => '内容',
			'shows' => '1',
			'widths' => '',
			'sorts' => '0',
			'models' => '',
			'sortname' => 'content',
			'sortnum' => '4',
			'issearch' => '0',
			'isexport' => '1',
			'searchField' => '',
			'table' => '',
			'field' => '',
			'conditions' => '',
			'type' => '',
			'isallsearch' => '0',
			'searchsortnum' => '0',
			'status' => '1',
			'rules' => '1',
			'message' => '0',
			'helpvalue' => '',
	),
		'4' => array(
				'name' => 'remindcreateid',
				'showname' => '创建人',
				'shows' => '1',
				'widths' => '',
				'sorts' => '0',
				'models' => '',
				'sortname' => 'remindcreateid',
				'sortnum' => '5',
				'issearch' => '0',
				'isexport' => '1',
				'searchField' => '',
				'func' => array(
						'0' => array(
								'0' => 'getFieldBy',
						),
				),
				'funcdata' => array(
						'0' => array(
								'0' => array(
										'0' => '###',
										'1' => 'id',
										'2' => 'name',
										'3' => 'user',
								),
						),
				),
				'table' => '',
				'field' => '',
				'conditions' => '',
				'type' => '',
				'isallsearch' => '0',
				'searchsortnum' => '0',
				'status' => '1',
				'rules' => '1',
				'message' => '0',
				'helpvalue' => '',
		),
		'5' => array(
				'name' => 'remindcreatetime',
				'showname' => '首次阅读时间',
				'shows' => '1',
				'widths' => '',
				'sorts' => '0',
				'models' => '',
				'sortname' => 'remindcreatetime',
				'sortnum' => '6',
				'issearch' => '0',
				'isexport' => '1',
				'searchField' => '',
				'table' => '',
				'field' => '',
				'conditions' => '',
				'type' => '',
				'isallsearch' => '0',
				'searchsortnum' => '0',
				'func' => array(
						'0' => array(
								'0' => 'transTime',
						),
				),
				'funcdata' => array(
					'0' => array(
						'0' => array(
							'0' => '###',
							'1' => 'Y-m-d H:i',
						),
					),
				),
				'status' => '1',
				'rules' => '1',
				'message' => '0',
				'helpvalue' => '',
		),
		'10' => array(
				'name' => 'userid',
				'showname' => '用户id',
				'shows' => '0',
				'widths' => '',
				'sorts' => '0',
				'models' => '',
				'sortname' => 'userid',
				'sortnum' => '10',
				'issearch' => '0',
				'isexport' => '1',
				'searchField' => '',
				'table' => '',
				'field' => '',
				'conditions' => '',
				'type' => '',
				'isallsearch' => '0',
				'searchsortnum' => '0',
				'status' => '1',
				'rules' => '1',
				'message' => '0',
				'helpvalue' => '',
		),
		
	'6' => array(
		'name' => 'createid',
		'showname' => '操作员',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'createid',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'user',
				),
			),
		),
		'sortnum' => '8',
		'status' => '1',
		'isexport' => '0',
		'rules' => '1',
		'message' => '0',
		'searchField' => 'mis_system_sysremind.createid',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '1',
		'isallsearch' => '0',
		'searchsortnum' => '0',
		'helpvalue' => '',
	),
		'12' => array(
				'name' => 'readcount',
				'showname' => '阅读次数',
				'shows' => '1',
				'widths' => '',
				'sorts' => '0',
				'models' => '',
				'sortname' => 'readcount',
				'sortnum' => '10',
				'issearch' => '0',
				'isexport' => '1',
				'searchField' => '',
				'table' => '',
				'field' => '',
				'conditions' => '',
				'type' => '',
				'isallsearch' => '0',
				'searchsortnum' => '0',
				'status' => '1',
				'rules' => '1',
				'message' => '0',
				'helpvalue' => '',
		),
		'11' => array(
				'name' => 'isread',
				'showname' => '是否阅读',
				'shows' => '0',
				'widths' => '',
				'sorts' => '0',
				'models' => '',
				'sortname' => 'isread',
				'sortnum' => '11',
				'issearch' => '1',
				'searchField' => 'mis_system_unit.isread',
				'table' => '',
				'field' => '',
				'conditions' => '',
				'type' => '',
				'isallsearch' => '1',
				'searchsortnum' => '7',
				'func' => array(
						'0' => array(
								'0' => 'getSelectlistValue',
						),
				),
				'funcdata' => array(
						'0' => array(
								'0' => array(
										'0' => '###',
										'1' => 'YesOrNo',
								),
						),
				),
				'status' => '1',
				'rules' => '1',
				'message' => '0',
		),
	'8' => array(
		'name' => 'updatetime',
		'showname' => '最近阅读时间',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'updatetime',
		'sortnum' => '10',
		'func' => array(
			'0' => array(
				'0' => 'transTime',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'Y-m-d H:i',
				),
			),
		),
		'issearch' => '1',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'time',
		'isallsearch' => '0',
		'status' => '1',
		'isexport' => '0',
		'rules' => '1',
		'message' => '0',
		'searchField' => 'mis_system_sysremind.createtime',
		'searchsortnum' => '0',
		'helpvalue' => '',
	),
	'9' => array(
		'name' => 'action',
		'showname' => '操作',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'status',
		'func' => array(
			'0' => array(
				'0' => 'getOperateStatus',
			),
			'1' => array(
				'0' => 'getStatus',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '#createid#',
					'1' => '#auditState#',
					'2' => 'id/#id#',
					'3' => '',
					'4' => '',
					'5' => 'dialog',
					'6' => '修改',
					'7' => '450',
					'8' => '320',
				),
			),
			'1' => array(
				'0' => array(
					'0' => '#status#',
				),
			),
		),
		'sortnum' => '11',
		'issearch' => '0',
		'status' => '1',
		'isexport' => '0',
		'rules' => '1',
		'message' => '0',
		'searchField' => '',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'isallsearch' => '0',
		'searchsortnum' => '0',
		'helpvalue' => '',
	),
);

?>