<?php 
return array(
	'0' => array(
		'name' => 'name',
		'showname' => '法定代表人',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'name',
		'sortnum' => '1',
		'searchField' => 'crm_cust_employee.name',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '0',
		'status' => '1',
	),
	'1' => array(
		'name' => 'linktel',
		'showname' => '法定代表人联系方式',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'linktel',
		'sortnum' => '2',
		'searchField' => 'crm_cust_employee.linktel',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '1',
		'status' => '1',
	),
	'2' => array(
		'name' => 'gdlinkman',
		'showname' => '指定联系人',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'gdlinkman',
		'sortnum' => '4',
		'searchField' => 'crm_cust_employee.gdlinkman',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '2',
		'status' => '1',
	),
	'3' => array(
		'name' => 'gdlinktel',
		'showname' => '指定联系人联系方式',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'gdlinktel',
		'sortnum' => '4',
		'searchField' => 'crm_cust_employee.gdlinktel',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '3',
		'status' => '1',
	),
	'4' => array(
		'name' => 'telphone',
		'showname' => '座机',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'telphone',
		'sortnum' => '5',
		'searchField' => 'crm_cust_employee.telphone',
		'table' => '',
		'field' => 'id',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '1',
		'isallsearch' => '0',
		'searchsortnum' => '4',
		'status' => '1',
	),
	'5' => array(
		'name' => 'fax',
		'showname' => '传真',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'fax',
		'sortnum' => '6',
		'searchField' => 'crm_cust_employee.fax',
		'table' => '',
		'field' => 'id',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '5',
		'status' => '1',
	),
	'6' => array(
		'name' => 'email',
		'showname' => '联系邮箱',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'email',
		'sortnum' => '7',
		'searchField' => 'crm_cust_employee.email',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '6',
		'status' => '1',
	),
	'7' => array(
		'name' => 'customercode',
		'showname' => '客户编号',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'customerid',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '#customerid#',
					'1' => 'id',
					'2' => 'code',
					'3' => 'MisSalesCustomer',
				),
			),
		),
		'sortnum' => '11',
		'searchField' => 'crm_cust_employee.customercode',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '7',
		'status' => '-1',
	),
	'8' => array(
		'name' => 'customername',
		'showname' => '客户名称',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'customerid',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '#customerid#',
					'1' => 'id',
					'2' => 'name',
					'3' => 'MisSalesCustomer',
				),
			),
		),
		'sortnum' => '13',
		'searchField' => 'crm_cust_employee.customername',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '8',
		'status' => '-1',
	),
	'9' => array(
		'name' => 'remark',
		'showname' => '备注',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'remark',
		'sortnum' => '17',
		'searchField' => 'crm_cust_employee.remark',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '9',
		'status' => '1',
	),
	'10' => array(
		'name' => 'qq',
		'showname' => 'QQ',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'qq',
		'sortnum' => '18',
		'searchField' => 'crm_cust_employee.qq',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '10',
		'status' => '1',
	),
	'11' => array(
		'name' => 'action',
		'showname' => '操作',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'status',
		'sortnum' => '19',
		'issearch' => '0',
		'searchField' => '',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'isallsearch' => '0',
		'searchsortnum' => '0',
		'status' => '1',
		'extention_html_end' => array(
			'0' => ' ',
		),
		'func' => array(
			'0' => array(
				'0' => 'getOperateStatus',
			),
			'1' => array(
				'0' => 'getStatus',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '#createid#',
					'1' => '#auditState#',
					'2' => 'id/#id#',
					'3' => '',
					'4' => '',
					'5' => 'dialog',
					'6' => '组织结构',
					'7' => '762',
					'8' => '400',
				),
			),
			'1' => array(
				'0' => array(
					'0' => '#status#',
				),
			),
		),
	),
);

?>