<?php 
return array(
	'id' => array(
		'name' => 'id',
		'showname' => 'ID',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'title',
		'sortnum' => '1',
		'issearch' => '1',
		'searchField' => 'mis_system_data_update_manage.id',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '1',
		'searchsortnum' => '1',
		'status' => '1',
		'rules' => '0',
		'message' => '0',
	),
	'modelname' => array(
		'name' => 'modelname',
		'showname' => '数据模型',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'modelname',
		'sortnum' => '2',
		'issearch' => '1',
		'searchField' => 'mis_system_data_update_manage.modelname',
		'func' => array(
				'0' => array(
						'0' => 'getFieldBy',
				),
		),
		'funcdata' => array(
				'0' => array(
						'0' => array(
								'0' => '###',
								'1' => 'name',
								'2'=>'title',
								'3'=>'node',
						),
				),
		),
		'table' => 'node',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '1',
		'searchsortnum' => '3',
		'status' => '1',
		'rules' => '0',
		'message' => '0',
	),
	'tablename' => array(
		'name' => 'tablename',
		'showname' => '数据表',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'sourcename',
		'sortnum' => '3',
		'issearch' => '1',
		'searchField' => 'mis_system_data_update_manage.tablename',
			
		'table' => 'mis_system_data_update_manage',
		'field' => 'sourcename',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '1',
		'searchsortnum' => '3',
		'status' => '1',
		'rules' => '0',
		'message' => '0',
	),
	'tabledataid' => array(
		'name' => 'tabledataid',
		'showname' => '修改数据主表id',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'tabledataid',
		'sortnum' => '4',
		'issearch' => '1',
		'searchField' => 'mis_system_data_update_manage.tabledataid',
		'table' => 'mis_system_data_update_manage',
		'field' => 'tabledataid',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '1',
		'searchsortnum' => '3',
		'status' => '1',
		'rules' => '0',
		'message' => '0',
	),
	'tabletype' => array(
		'name' => 'tabletype',
		'showname' => '表类型',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'tabletype',
		'sortnum' => '5',
		'func' => array(
				'0' => array(
						'0' => 'excelTplselected',
				),
		),
		'funcdata' => array(
				'0' => array(
						'0' => array(
								'0' => '###',
								'1' => '1:主表,2:内嵌表',
						),
				),
		),
		'issearch' => '1',
		'searchField' => 'mis_system_data_update_manage.tabletype',
		'table' => 'excelTplselected',
		'field' => 'tabletype',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '1',
		'searchsortnum' => '3',
		'status' => '1',
		'rules' => '0',
		'message' => '0',
 	),
	'createid' => array(
		'name' => 'createid',
		'showname' => '修改人',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'createid',
		'sortnum' => '5',
		'issearch' => '1',
		'searchField' => 'mis_system_data_update_manage.createid',
			'func' => array(
					'0' => array(
							'0' => 'getFieldBy',
					),
			),
			'funcdata' => array(
					'0' => array(
							'0' => array(
									'0' => '###',
									'1' => 'id',
									'2'=>'name',
									'3'=>'user',
							),
					),
			),
		
		'table' => 'user',
		'field' => 'createid',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '1',
		'searchsortnum' => '3',
		'status' => '1',
		'rules' => '0',
		'message' => '0',
	),
// 	'5' => array(
// 		'name' => 'targettype',
// 		'showname' => '目标动作',
// 		'shows' => '1',
// 		'widths' => '',
// 		'sorts' => '0',
// 		'models' => '',
// 		'sortname' => 'tragettype',
// 		'sortnum' => '6',
// 		'issearch' => '1',
// 		'searchField' => 'mis_system_data_update_manage.targettype',
// 		'table' => 'excelTplselected',
// 		'field' => 'targettype',
// 		'conditions' => '',
// 		'type' => 'text',
// 		'isallsearch' => '1',
// 		'searchsortnum' => '3',
// 		'status' => '1',
// 		'rules' => '0',
// 		'message' => '0',
// 		'func' => array(
// 			'0' => array(
// 				'0' => 'excelTplselected',
// 			),
// 		),
// 		'funcdata' => array(
// 			'0' => array(
// 				'0' => array(
// 					'0' => '###',
// 					'1' => '1:新增,2:修改,3:删除,4:生成表单',
// 				),
// 			),
// 		),
// 	),
// 	'9' => array(
// 		'name' => 'action',
// 		'showname' => '操作',
// 		'shows' => '1',
// 		'widths' => '',
// 		'sorts' => '0',
// 		'models' => '',
// 		'sortname' => 'status',
// 		'func' => array(
// 			'0' => array(
// 				'0' => 'showStatus',
// 			),
// 		),
// 		'funcdata' => array(
// 			'0' => array(
// 				'0' => array(
// 					'0' => '#status#',
// 					'1' => '#id#',
// 				),
// 			),
// 		),
// 		'sortnum' => '7',
// 		'searchField' => '',
// 		'table' => '',
// 		'field' => '',
// 		'conditions' => '',
// 		'type' => '',
// 		'issearch' => '0',
// 		'isallsearch' => '0',
// 		'searchsortnum' => '0',
// 	),
);

?>