<?php 
return array(
	'1' => array(
		'name' => 'id',
		'showname' => '编号',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'id',
		'sortnum' => '1',
		'issearch' => '',
		'searchField' => '',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'isallsearch' => '',
		'searchsortnum' => '',
	),
	'0' => array(
		'name' => 'code',
		'showname' => '科目代码',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'code',
		'sortnum' => '2',
		'issearch' => '1',
		'searchField' => 'mis_finance_amount_title.code',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '1',
		'searchsortnum' => '2',
	),
	'11' => array(
		'name' => 'levels',
		'showname' => '级别',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'levels',
		'sortnum' => '3',
		'issearch' => '1',
		'searchField' => 'mis_finance_amount_title.levels',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '1',
		'searchsortnum' => '3',
	),
	'2' => array(
		'name' => 'name',
		'showname' => '科目名称',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'name',
		'sortnum' => '4',
		'issearch' => '1',
		'searchField' => 'mis_finance_amount_title.name',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '1',
		'searchsortnum' => '4',
	),
	'3' => array(
		'name' => 'sname',
		'showname' => '科目搜索名称',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'sname',
		'sortnum' => '5',
		'issearch' => '1',
		'searchField' => 'mis_finance_amount_title.sname',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '1',
		'searchsortnum' => '5',
	),
	'4' => array(
		'name' => 'atype',
		'showname' => '科目类型',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'atype',
		'sortnum' => '6',
		'func' => array(
			'0' => array(
				'0' => 'excelTplselected',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => '资产,负债,所有者权益,成本,损益',
				),
			),
		),
		'issearch' => '1',
		'searchField' => 'mis_finance_amount_title.atype',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '1',
		'searchsortnum' => '6',
	),
	'5' => array(
		'name' => 'debit',
		'showname' => '借方',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'debit',
		'sortnum' => '7',
		'func' => array(
			'0' => array(
				'0' => 'isDefault',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => '',
				),
			),
		),
		'issearch' => '1',
		'searchField' => 'mis_finance_amount_title.debit',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'radio|debit',
		'isallsearch' => '1',
		'searchsortnum' => '7',
	),
	'6' => array(
		'name' => 'credit',
		'showname' => '贷放',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'credit',
		'sortnum' => '8',
		'func' => array(
			'0' => array(
				'0' => 'isDefault',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
				),
			),
		),
		'issearch' => '1',
		'searchField' => 'mis_finance_amount_title.credit',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'radio|credit',
		'isallsearch' => '1',
		'searchsortnum' => '8',
	),
	'7' => array(
		'name' => 'balance',
		'showname' => '余额',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'balance',
		'sortnum' => '9',
		'extention_html_end' => array(
			'0' => 'RMB',
		),
		'func' => array(
			'0' => array(
				'0' => 'getDigits',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
				),
			),
		),
		'issearch' => '',
		'searchField' => 'mis_finance_amount_title.balance',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '',
		'searchsortnum' => '9',
	),
	'8' => array(
		'name' => 'employeeid',
		'showname' => '员工',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'employeeid',
		'sortnum' => '10',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'mis_hr_personnel_person_info',
				),
			),
		),
		'issearch' => '1',
		'searchField' => 'mis_finance_amount_title.employeeid',
		'table' => 'mis_hr_personnel_person_info',
		'field' => 'id',
		'conditions' => '',
		'type' => 'db',
		'isallsearch' => '1',
		'searchsortnum' => '10',
	),
		'12' => array(
				'name' => 'projectid',
				'showname' => '项目',
				'shows' => '1',
				'widths' => '',
				'sorts' => '0',
				'models' => '',
				'sortname' => 'projectid',
				'sortnum' => '11',
				'func' => array(
						'0' => array(
								'0' => 'getFieldBy',
						),
				),
				'funcdata' => array(
						'0' => array(
								'0' => array(
										'0' => '###',
										'1' => 'id',
										'2' => 'name',
										'3' => 'mis_sales_project',
								),
						),
				),
				'issearch' => '1',
				'searchField' => 'mis_finance_amount_title.projectid',
				'table' => 'mis_sales_project',
				'field' => 'id',
				'conditions' => '',
				'type' => 'db',
				'isallsearch' => '1',
				'searchsortnum' => '11',
		),
	'9' => array(
		'name' => 'action',
		'showname' => '操作',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'status',
		'sortnum' => '12',
		'issearch' => '',
		'searchField' => '',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'isallsearch' => '',
		'searchsortnum' => '',
		'status' => '1',
		'extention_html_end' => array(
			'0' => ' ',
		),
		'func' => array(
			'0' => array(
				'0' => 'getOperateStatus',
			),
			'1' => array(
				'0' => 'getStatus',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '#createid#',
					'1' => '#auditState#',
					'2' => 'id/#id#',
					'3' => '',
					'4' => '',
					'5' => 'dialog',
					'6' => '会计科目',
				),
			),
			'1' => array(
				'0' => array(
					'0' => '#status#',
				),
			),
		),
	),
	/* '10' => array(
		'name' => 'action',
		'showname' => '操作',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'status',
		'func' => array(
			'0' => array(
				'0' => 'showStatus',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '#status#',
					'1' => '#id#',
				),
			),
		),
		'sortnum' => '12',
		'issearch' => '',
		'searchField' => '',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'isallsearch' => '',
		'searchsortnum' => '',
	), */
);

?>