<?php 
return array(
	'0' => array(
		'name' => 'id',
		'showname' => 'ID',
		'shows' => '0',
		'widths' => '30',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'id',
		'sortnum' => '1',
		'issearch' => '0',
		'searchField' => '',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'isallsearch' => '0',
		'searchsortnum' => '0',
		'status' => '1',
	),
	'1' => array(
		'name' => 'orderno',
		'showname' => '员工编号',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'orderno',
		'sortnum' => '2',
		'issearch' => '1',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_person_info.orderno',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '1',
		'searchsortnum' => '1',
		'status' => '1',
	),
	'2' => array(
		'name' => 'name',
		'showname' => '姓名',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'name',
		'sortnum' => '3',
		'issearch' => '1',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_person_info.name',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '1',
		'searchsortnum' => '2',
		'status' => '1',
	),
	'5' => array(
		'name' => 'education',
		'showname' => '学历',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'education',
		'sortnum' => '3',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'mis_hr_typeinfo',
				),
			),
		),
		'issearch' => '1',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_person_info.education',
		'table' => 'mis_hr_typeinfo',
		'field' => 'id',
		'conditions' => 'typeid=2,pid=44',
		'type' => 'group',
		'isallsearch' => '0',
		'searchsortnum' => '5',
		'status' => '1',
	),
	'3' => array(
		'name' => 'sex',
		'showname' => '性别',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'sex',
		'sortnum' => '4',
		'func' => array(
			'0' => array(
				'0' => 'getS',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
				),
			),
		),
		'issearch' => '1',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_person_info.sex',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'radio|sex',
		'isallsearch' => '0',
		'searchsortnum' => '3',
		'status' => '1',
	),
	'4' => array(
		'name' => 'age',
		'showname' => '年龄',
		'shows' => '1',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'age',
		'sortnum' => '5',
		'issearch' => '0',
		'searchField' => 'mis_hr_personnel_person_info.age',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'isallsearch' => '0',
		'searchsortnum' => '4',
		'status' => '1',
		'widths' => '',
		'func' => array(
			'0' => array(
				'0' => 'getAgeByToCarIdForList',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '#chinaid#',
					'1' => '',
				),
			),
		),
	),
	'6' => array(
		'name' => 'deptid',
		'showname' => '部门',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'deptid',
		'sortnum' => '7',
		'issearch' => '1',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_person_info.deptid',
		'table' => 'mis_system_department',
		'field' => 'id',
		'conditions' => '',
		'type' => 'db',
		'isallsearch' => '1',
		'searchsortnum' => '6',
		'status' => '1',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'mis_system_department',
				),
			),
		),
	),
	'7' => array(
		'name' => 'dutyid',
		'showname' => '职级',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'dutyid',
		'sortnum' => '8',
		'issearch' => '1',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_person_info.dutyid',
		'table' => 'duty',
		'field' => 'id',
		'conditions' => '',
		'isallsearch' => '1',
		'searchsortnum' => '8',
		'status' => '1',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'duty',
				),
			),
		),
		'type' => 'db',
	),
	'8' => array(
		'name' => 'worktype',
		'showname' => '岗位',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'worktype',
		'sortnum' => '9',
		'issearch' => '1',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_person_info.worktype',
		'table' => 'mis_hr_job_info',
		'field' => 'id',
		'conditions' => '',
		'type' => 'db',
		'isallsearch' => '1',
		'searchsortnum' => '8',
		'status' => '1',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'mis_hr_job_info',
				),
			),
		),
	),
	'9' => array(
		'name' => 'indate',
		'showname' => '入职时间',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'indate',
		'sortnum' => '10',
		'func' => array(
			'0' => array(
				'0' => 'transTime',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
				),
			),
		),
		'issearch' => '1',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_person_info.indate',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'time',
		'isallsearch' => '0',
		'searchsortnum' => '9',
		'status' => '1',
	),
	'10' => array(
		'name' => 'chinaid',
		'showname' => '身份证号',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'chinaid',
		'sortnum' => '11',
		'issearch' => '1',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_person_info.chinaid',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '1',
		'searchsortnum' => '10',
		'status' => '1',
	),
	'11' => array(
		'name' => 'remark',
		'showname' => '备注',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'chinaid',
		'sortnum' => '12',
		'issearch' => '0',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_person_info.chinaid',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '11',
		'status' => '1',
	),
	'22' => array(
		'name' => 'weibo',
		'showname' => '微博',
		'shows' => '0',
		'widths' => '30',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'weibo',
		'sortnum' => '13',
		'issearch' => '0',
		'searchField' => 'mis_hr_personnel_person_info.weibo',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'isallsearch' => '0',
		'searchsortnum' => '0',
		'status' => '1',
	),
	'23' => array(
		'name' => 'maritalstatus',
		'showname' => '婚姻状况',
		'shows' => '0',
		'widths' => '30',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'maritalstatus',
		'sortnum' => '14',
		'issearch' => '0',
		'searchField' => 'mis_hr_personnel_person_info.maritalstatus',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'isallsearch' => '0',
		'searchsortnum' => '0',
		'status' => '1',
	),
	'24' => array(
		'name' => 'householdregister',
		'showname' => '户籍所在地',
		'shows' => '0',
		'widths' => '30',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'householdregister',
		'sortnum' => '15',
		'issearch' => '0',
		'searchField' => 'mis_hr_personnel_person_info.householdregister',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'isallsearch' => '0',
		'searchsortnum' => '0',
		'status' => '1',
	),
	'21' => array(
		'name' => 'qq',
		'showname' => 'QQ',
		'shows' => '0',
		'widths' => '30',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'qq',
		'sortnum' => '16',
		'issearch' => '0',
		'searchField' => 'mis_hr_personnel_person_info.qq',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'isallsearch' => '0',
		'searchsortnum' => '0',
		'status' => '1',
	),
	'20' => array(
		'name' => 'email',
		'showname' => '联系邮箱',
		'shows' => '0',
		'widths' => '30',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'email',
		'sortnum' => '17',
		'issearch' => '0',
		'searchField' => 'mis_hr_personnel_person_info.email',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'isallsearch' => '0',
		'searchsortnum' => '0',
		'status' => '1',
	),
	'18' => array(
		'name' => 'mobilephone',
		'showname' => '联系电话',
		'shows' => '0',
		'widths' => '30',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'mobilephone',
		'sortnum' => '18',
		'issearch' => '0',
		'searchField' => 'mis_hr_personnel_person_info.mobilephone',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'isallsearch' => '0',
		'searchsortnum' => '0',
		'status' => '1',
	),
	'19' => array(
		'name' => 'urgentphone',
		'showname' => '紧急联系电话',
		'shows' => '0',
		'widths' => '30',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'urgentphone',
		'sortnum' => '19',
		'issearch' => '0',
		'searchField' => 'mis_hr_personnel_person_info.urgentphone',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'isallsearch' => '0',
		'searchsortnum' => '0',
		'status' => '1',
	),
	'25' => array(
		'name' => 'address',
		'showname' => '现居地',
		'shows' => '0',
		'widths' => '30',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'address',
		'sortnum' => '20',
		'issearch' => '0',
		'searchField' => 'mis_hr_personnel_person_info.address',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'isallsearch' => '0',
		'searchsortnum' => '0',
		'status' => '1',
	),
	'26' => array(
		'name' => 'politicsstatus',
		'showname' => '政治面貌',
		'shows' => '0',
		'widths' => '30',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'politicsstatus',
		'sortnum' => '21',
		'issearch' => '0',
		'searchField' => 'mis_hr_personnel_person_info.politicsstatus',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'isallsearch' => '0',
		'searchsortnum' => '0',
		'status' => '1',
	),
	'31' => array(
		'name' => 'probationCycle',
		'showname' => '试用周期',
		'shows' => '0',
		'widths' => '30',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'probationCycle',
		'sortnum' => '22',
		'issearch' => '0',
		'searchField' => 'mis_hr_personnel_person_info.probationCycle',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'isallsearch' => '0',
		'searchsortnum' => '0',
		'status' => '1',
	),
	'32' => array(
		'name' => 'transferdate',
		'showname' => '转正日期',
		'shows' => '0',
		'widths' => '30',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'transferdate',
		'sortnum' => '23',
		'issearch' => '0',
		'searchField' => 'mis_hr_personnel_person_info.transferdate',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'isallsearch' => '0',
		'searchsortnum' => '0',
		'status' => '1',
	),
	'30' => array(
		'name' => 'probationdate',
		'showname' => '试用日期',
		'shows' => '0',
		'widths' => '30',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'probationdate',
		'sortnum' => '24',
		'issearch' => '0',
		'searchField' => 'mis_hr_personnel_person_info.probationdate',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'isallsearch' => '0',
		'searchsortnum' => '0',
		'status' => '1',
	),
	'29' => array(
		'name' => 'specialskill',
		'showname' => '特长',
		'shows' => '0',
		'widths' => '30',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'specialskill',
		'sortnum' => '25',
		'issearch' => '0',
		'searchField' => 'mis_hr_personnel_person_info.specialskill',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'isallsearch' => '0',
		'searchsortnum' => '0',
		'status' => '1',
	),
	'27' => array(
		'name' => 'picture',
		'showname' => '相片',
		'shows' => '0',
		'widths' => '30',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'picture',
		'sortnum' => '26',
		'issearch' => '0',
		'searchField' => 'mis_hr_personnel_person_info.picture',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'isallsearch' => '0',
		'searchsortnum' => '0',
		'status' => '1',
	),
	'28' => array(
		'name' => 'workstatus',
		'showname' => '在职状态',
		'shows' => '0',
		'widths' => '30',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'workstatus',
		'sortnum' => '27',
		'issearch' => '0',
		'searchField' => 'mis_hr_personnel_person_info.workstatus',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'isallsearch' => '0',
		'searchsortnum' => '0',
		'status' => '1',
	),
	'17' => array(
		'name' => 'graduation',
		'showname' => '毕业院校',
		'shows' => '0',
		'widths' => '30',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'graduation',
		'sortnum' => '28',
		'issearch' => '0',
		'searchField' => 'mis_hr_personnel_person_info.graduation',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'isallsearch' => '0',
		'searchsortnum' => '0',
		'status' => '1',
	),
	'13' => array(
		'name' => 'major',
		'showname' => '专业',
		'shows' => '0',
		'widths' => '30',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'major',
		'sortnum' => '29',
		'issearch' => '0',
		'searchField' => 'mis_hr_personnel_person_info.major',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'isallsearch' => '0',
		'searchsortnum' => '0',
		'status' => '1',
	),
	'16' => array(
		'name' => 'birthday',
		'showname' => '出生年月',
		'shows' => '0',
		'widths' => '30',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'birthday',
		'sortnum' => '30',
		'issearch' => '0',
		'searchField' => 'mis_hr_personnel_person_info.birthday',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'isallsearch' => '0',
		'searchsortnum' => '0',
		'status' => '1',
	),
	'14' => array(
		'name' => 'picture',
		'showname' => '相片',
		'shows' => '0',
		'widths' => '30',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'picture',
		'sortnum' => '31',
		'issearch' => '0',
		'searchField' => 'mis_hr_personnel_person_info.picture',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'isallsearch' => '0',
		'searchsortnum' => '0',
		'status' => '1',
	),
	'15' => array(
		'name' => 'nation',
		'showname' => '民族',
		'shows' => '0',
		'widths' => '30',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'nation',
		'sortnum' => '32',
		'issearch' => '0',
		'searchField' => 'mis_hr_personnel_person_info.nation',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'isallsearch' => '0',
		'searchsortnum' => '0',
		'status' => '1',
	),
	'12' => array(
		'name' => 'action',
		'showname' => '查看详情',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'status',
		'sortnum' => '33',
		'issearch' => '0',
		'searchField' => '',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'isallsearch' => '0',
		'searchsortnum' => '0',
		'status' => '1',
		'extention_html_end' => array(
			'0' => ' ',
		),
		'func' => array(
			'0' => array(
				'0' => 'showhtml',
			),
			'1' => array(
				'0' => 'showhtml',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '<a href="__URL__/edit/id/#id#" title="查看详情" rel="MisHrProbationEmployee_edit" target="dialog" mask="true" height="500" width="800"><span style="color:red">查看</span></a>',
				),
			),
			'1' => array(
				'0' => array(
					'0' => '<a href="__URL__/editgeneral/id/#id#" title="员工档案" rel="MisHrPersonnelManagement_editgeneral" target="navTab" mask="true"  ><span style="color:red">修改</span></a>',
				),
			),
		),
	),
	'36' => array(
		'name' => 'chinaidaddress',
		'showname' => '身高',
		'shows' => '0',
		'widths' => '30',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'chinaidaddress',
		'sortnum' => '34',
		'issearch' => '0',
		'searchField' => 'mis_hr_personnel_person_info.chinaidaddress',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'isallsearch' => '0',
		'searchsortnum' => '0',
		'status' => '1',
	),
	'35' => array(
		'name' => 'eyesight',
		'showname' => '视力',
		'shows' => '0',
		'widths' => '30',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'eyesight',
		'sortnum' => '34',
		'issearch' => '0',
		'searchField' => 'mis_hr_personnel_person_info.eyesight',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'isallsearch' => '0',
		'searchsortnum' => '0',
		'status' => '1',
	),
	'33' => array(
		'name' => 'employeeheight',
		'showname' => '身高',
		'shows' => '0',
		'widths' => '30',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'employeeheight',
		'sortnum' => '34',
		'issearch' => '0',
		'searchField' => 'mis_hr_personnel_person_info.employeeheight',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'isallsearch' => '0',
		'searchsortnum' => '0',
		'status' => '1',
	),
	'34' => array(
		'name' => 'weight',
		'showname' => '体重',
		'shows' => '0',
		'widths' => '30',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'weight',
		'sortnum' => '35',
		'issearch' => '0',
		'searchField' => 'mis_hr_personnel_person_info.weight',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'isallsearch' => '0',
		'searchsortnum' => '0',
		'status' => '1',
	),
);

?>