<?php 
return array(
	'0' => array(
		'name' => 'id',
		'showname' => 'ID',
		'shows' => '0',
		'widths' => '30',
		'sorts' => '1',
		'models' => '',
		'sortname' => 'id',
		'sortnum' => '1',
		'issearch' => '0',
		'searchField' => '',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'isallsearch' => '0',
		'searchsortnum' => '0',
		'status' => '1',
	),
	'1' => array(
		'name' => 'orderno',
		'showname' => '员工编号',
		'shows' => '0',
		'widths' => '',
		'sorts' => '1',
		'models' => '',
		'sortname' => 'orderno',
		'sortnum' => '2',
		'issearch' => '0',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_address_book.orderno',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '2',
		'status' => '1',
	),
	'18' => array(
		'name' => 'workkind',
		'showname' => '工种',
		'shows' => '0',
		'widths' => '',
		'sorts' => '1',
		'models' => '',
		'sortname' => 'workkind',
		'sortnum' => '3',
		'func' => array(
			'0' => array(
				'0' => 'excelTplselected',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => '1:技术,2:非技,3:实习,4:普工',
				),
			),
		),
		'issearch' => '0',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_address_book.workkind',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'select|yuangongBz',
		'isallsearch' => '0',
		'searchsortnum' => '3',
		'status' => '1',
	),
	'2' => array(
		'name' => 'itemid',
		'showname' => '档案号',
		'shows' => '0',
		'widths' => '',
		'sorts' => '1',
		'models' => '',
		'sortname' => 'itemid',
		'sortnum' => '4',
		'issearch' => '1',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_person_info.itemid',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '1',
		'searchsortnum' => '4',
		'status' => '1',
	),
	'3' => array(
		'name' => 'name',
		'showname' => '姓名',
		'shows' => '1',
		'widths' => '',
		'sorts' => '1',
		'models' => '',
		'sortname' => 'name',
		'sortnum' => '5',
		'issearch' => '1',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_person_info.name',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '1',
		'searchsortnum' => '5',
		'status' => '1',
	),
	'4' => array(
		'name' => 'sex',
		'showname' => '性别',
		'shows' => '1',
		'widths' => '',
		'sorts' => '1',
		'models' => '',
		'sortname' => 'sex',
		'sortnum' => '6',
		'func' => array(
			'0' => array(
				'0' => 'getS',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
				),
			),
		),
		'issearch' => '1',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_person_info.sex',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'radio|sex',
		'isallsearch' => '0',
		'searchsortnum' => '6',
		'status' => '1',
	),
	'5' => array(
		'name' => 'profession',
		'showname' => '专业',
		'shows' => '0',
		'widths' => '',
		'sorts' => '1',
		'models' => '',
		'sortname' => 'profession',
		'sortnum' => '7',
		'issearch' => '0',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_address_book.profession',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '7',
		'status' => '1',
	),
	'6' => array(
		'name' => 'deptid',
		'showname' => '所属部门',
		'shows' => '1',
		'widths' => '',
		'sorts' => '1',
		'models' => '',
		'sortname' => 'deptid',
		'sortnum' => '8',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'mis_system_department',
				),
			),
		),
		'issearch' => '1',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_person_info.deptid',
		'table' => 'mis_system_department',
		'field' => 'id',
		'conditions' => '',
		'type' => 'db',
		'isallsearch' => '0',
		'searchsortnum' => '8',
		'status' => '1',
	),
	'8' => array(
		'name' => 'dutyname',
		'showname' => '职级',
		'shows' => '1',
		'widths' => '',
		'sorts' => '1',
		'models' => '',
		'sortname' => 'dutyname',
		'sortnum' => '9',
		'issearch' => '0',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_address_book.dutyname',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '9',
		'status' => '1',
	),
	'7' => array(
		'name' => 'dutylevelid',
		'showname' => '职级',
		'shows' => '0',
		'widths' => '',
		'sorts' => '1',
		'models' => '',
		'sortname' => 'dutylevelid',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'duty',
				),
			),
		),
		'sortnum' => '10',
		'issearch' => '0',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_address_book.dutylevelid',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '10',
		'status' => '1',
	),
	'9' => array(
		'name' => 'indate',
		'showname' => '入职时间',
		'shows' => '0',
		'widths' => '',
		'sorts' => '1',
		'models' => '',
		'sortname' => 'indate',
		'sortnum' => '11',
		'func' => array(
			'0' => array(
				'0' => 'transTime',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
				),
			),
		),
		'issearch' => '0',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_address_book.indate',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'time',
		'isallsearch' => '0',
		'searchsortnum' => '11',
		'status' => '1',
	),
	'10' => array(
		'name' => 'transferprobationdate',
		'showname' => '转试用时间',
		'shows' => '0',
		'widths' => '',
		'sorts' => '1',
		'models' => '',
		'sortname' => 'transferprobationdate',
		'sortnum' => '12',
		'func' => array(
			'0' => array(
				'0' => 'transTime',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
				),
			),
		),
		'issearch' => '0',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_address_book.transferprobationdate',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '12',
		'status' => '1',
	),
	'11' => array(
		'name' => 'transferdate',
		'showname' => '转正时间',
		'shows' => '0',
		'widths' => '',
		'sorts' => '1',
		'models' => '',
		'sortname' => 'transferdate',
		'sortnum' => '13',
		'func' => array(
			'0' => array(
				'0' => 'transTime',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
				),
			),
		),
		'issearch' => '0',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_address_book.transferdate',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'time',
		'isallsearch' => '0',
		'searchsortnum' => '13',
		'status' => '1',
	),
	'20' => array(
		'name' => 'positivestatus',
		'showname' => '是否转正',
		'shows' => '0',
		'widths' => '',
		'sorts' => '1',
		'models' => '',
		'sortname' => 'positivestatus',
		'sortnum' => '14',
		'issearch' => '0',
		'func' => array(
			'0' => array(
				'0' => 'isDefault',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
				),
			),
		),
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_address_book.positivestatus',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'select|positivestatus',
		'isallsearch' => '0',
		'searchsortnum' => '14',
		'status' => '1',
	),
	'12' => array(
		'name' => 'leavedate',
		'showname' => '离职时间',
		'shows' => '0',
		'widths' => '',
		'sorts' => '1',
		'models' => '',
		'sortname' => 'leavedate',
		'sortnum' => '15',
		'func' => array(
			'0' => array(
				'0' => 'transTime',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
				),
			),
		),
		'issearch' => '0',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_address_book.leavedate',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '15',
		'status' => '1',
	),
	'13' => array(
		'name' => 'phone',
		'showname' => '联系电话',
		'shows' => '1',
		'widths' => '',
		'sorts' => '1',
		'models' => '',
		'sortname' => 'phone',
		'sortnum' => '16',
		'issearch' => '0',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_address_book.phone',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '16',
		'status' => '1',
	),
	'14' => array(
		'name' => 'urgentphone',
		'showname' => '紧急联系电话',
		'shows' => '0',
		'widths' => '',
		'sorts' => '1',
		'models' => '',
		'sortname' => 'urgentphone',
		'sortnum' => '17',
		'issearch' => '0',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_address_book.urgentphone',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '17',
		'status' => '1',
	),
	'15' => array(
		'name' => 'birthday',
		'showname' => '出生日期',
		'shows' => '0',
		'widths' => '',
		'sorts' => '1',
		'models' => '',
		'sortname' => 'birthday',
		'sortnum' => '18',
		'issearch' => '0',
		'isexport' => '1',
		'func' => array(
			'0' => array(
				'0' => 'transTime',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
				),
			),
		),
		'searchField' => 'mis_hr_personnel_address_book.birthday',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '18',
		'status' => '1',
	),
	'16' => array(
		'name' => 'chinaid',
		'showname' => '身份证',
		'shows' => '0',
		'widths' => '',
		'sorts' => '1',
		'models' => '',
		'sortname' => 'chinaid',
		'sortnum' => '19',
		'issearch' => '0',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_address_book.chinaid',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '19',
		'status' => '1',
	),
	'19' => array(
		'name' => 'working',
		'showname' => '职位状态',
		'shows' => '0',
		'widths' => '',
		'sorts' => '1',
		'models' => '',
		'sortname' => 'working',
		'sortnum' => '21',
		'issearch' => '0',
		'func' => array(
			'0' => array(
				'0' => 'getLeavestatus',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
				),
			),
		),
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_address_book.working',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'select|working',
		'isallsearch' => '0',
		'searchsortnum' => '25',
		'status' => '1',
	),
	'23' => array(
		'name' => 'politicsstatus',
		'showname' => '政治面貌',
		'shows' => '0',
		'widths' => '',
		'sorts' => '1',
		'models' => '',
		'sortname' => 'politicsstatus',
		'sortnum' => '24',
		'issearch' => '0',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_address_book.politicsstatus',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'select|politicsstatus',
		'isallsearch' => '0',
		'searchsortnum' => '24',
		'status' => '1',
	),
	'24' => array(
		'name' => 'leavestatus',
		'showname' => '离职状态',
		'shows' => '0',
		'widths' => '',
		'sorts' => '1',
		'models' => '',
		'sortname' => 'leavestatus',
		'sortnum' => '25',
		'func' => array(
			'0' => array(
				'0' => 'excelTplselected',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => '0:否,1:是',
				),
			),
		),
		'issearch' => '0',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_address_book.leavestatus',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'select|leavestatus',
		'isallsearch' => '0',
		'searchsortnum' => '25',
		'status' => '1',
	),
	'25' => array(
		'name' => 'personcertificate',
		'showname' => '资格证书',
		'shows' => '0',
		'widths' => '',
		'sorts' => '1',
		'models' => '',
		'sortname' => 'personcertificate',
		'sortnum' => '26',
		'issearch' => '0',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_address_book.personcertificate',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '26',
		'status' => '1',
	),
	'26' => array(
		'name' => 'messagesource',
		'showname' => '招聘渠道',
		'shows' => '0',
		'widths' => '',
		'sorts' => '1',
		'models' => '',
		'sortname' => 'messagesource',
		'sortnum' => '27',
		'issearch' => '0',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_address_book.messagesource',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '27',
		'status' => '1',
	),
	'27' => array(
		'name' => 'infomationstatus',
		'showname' => '欠资料',
		'shows' => '0',
		'widths' => '',
		'sorts' => '1',
		'models' => '',
		'sortname' => 'infomationstatus',
		'sortnum' => '28',
		'issearch' => '0',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_address_book.infomationstatus',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '28',
		'status' => '1',
	),
	'28' => array(
		'name' => 'staffhandbook',
		'showname' => '员工手册',
		'shows' => '0',
		'widths' => '',
		'sorts' => '1',
		'models' => '',
		'sortname' => 'staffhandbook',
		'sortnum' => '29',
		'issearch' => '0',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_address_book.staffhandbook',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '29',
		'status' => '1',
	),
	'29' => array(
		'name' => 'school',
		'showname' => '毕业院校',
		'shows' => '0',
		'widths' => '',
		'sorts' => '1',
		'models' => '',
		'sortname' => 'school',
		'sortnum' => '30',
		'issearch' => '0',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_address_book.school',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '30',
		'status' => '1',
	),
	'30' => array(
		'name' => 'education',
		'showname' => '学历',
		'shows' => '0',
		'widths' => '',
		'sorts' => '1',
		'models' => '',
		'sortname' => 'education',
		'sortnum' => '31',
		'issearch' => '0',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_address_book.education',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '31',
		'status' => '1',
	),
	'31' => array(
		'name' => 'nativeaddress',
		'showname' => '户籍地址',
		'shows' => '0',
		'widths' => '',
		'sorts' => '1',
		'models' => '',
		'sortname' => 'nativeaddress',
		'sortnum' => '32',
		'issearch' => '0',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_address_book.nativeaddress',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '32',
		'status' => '1',
	),
	'34' => array(
		'name' => 'remark',
		'showname' => '备注信息',
		'shows' => '0',
		'widths' => '',
		'sorts' => '1',
		'models' => '',
		'sortname' => 'remark',
		'sortnum' => '35',
		'issearch' => '0',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_address_book.remark',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '35',
		'status' => '1',
	),
	'35' => array(
		'name' => 'createid',
		'showname' => '制单人',
		'shows' => '0',
		'widths' => '',
		'sorts' => '1',
		'models' => '',
		'sortname' => 'createid',
		'sortnum' => '36',
		'issearch' => '0',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_address_book.createid',
		'table' => 'user',
		'field' => 'id',
		'conditions' => '',
		'type' => 'db',
		'isallsearch' => '0',
		'searchsortnum' => '36',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'User',
				),
			),
		),
		'status' => '1',
	),
	'36' => array(
		'name' => 'createtime',
		'showname' => '制单时间',
		'shows' => '0',
		'widths' => '',
		'sorts' => '1',
		'models' => '',
		'sortname' => 'createtime',
		'sortnum' => '37',
		'issearch' => '0',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_address_book.createtime',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'time',
		'isallsearch' => '0',
		'searchsortnum' => '37',
		'func' => array(
			'0' => array(
				'0' => 'transTime',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
				),
			),
		),
		'status' => '1',
	),
	'37' => array(
		'name' => 'action',
		'showname' => '操作',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'status',
		'sortnum' => '38',
		'issearch' => '0',
		'searchField' => '',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'isallsearch' => '0',
		'searchsortnum' => '0',
		'status' => '1',
		'extention_html_end' => array(
			'0' => ' ',
		),
		'func' => array(
			'0' => array(
				'0' => 'getOperateStatus',
			),
			'1' => array(
				'0' => 'getStatus',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '#createid#',
					'1' => '#auditState#',
					'2' => 'id/#id#',
					'3' => '',
					'4' => '',
					'5' => 'dialog',
					'6' => '员工资料',
					'7' => '770',
					'8' => '580',
				),
			),
			'1' => array(
				'0' => array(
					'0' => '#status#',
				),
			),
		),
	),
	'38' => array(
		'name' => 'stringSort',
		'showname' => '字母排序',
		'shows' => '0',
		'widths' => '',
		'sorts' => '1',
		'models' => '',
		'sortname' => 'stringSort',
		'sortnum' => '39',
		'issearch' => '1',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_person_info.stringSort',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '35',
		'status' => '1',
	),
	'39' => array(
		'name' => 'shortNumber',
		'showname' => '短号码',
		'shows' => '1',
		'widths' => '',
		'sorts' => '1',
		'models' => '',
		'sortname' => 'shortNumber',
		'sortnum' => '40',
		'issearch' => '1',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_person_info.shortNumber',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '1',
		'searchsortnum' => '35',
		'status' => '1',
	),
	'40' => array(
		'name' => 'officeNumber',
		'showname' => '分机',
		'shows' => '1',
		'widths' => '',
		'sorts' => '1',
		'models' => '',
		'sortname' => 'officeNumber',
		'sortnum' => '41',
		'issearch' => '1',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_person_info.officeNumber',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '35',
		'status' => '1',
	),
	'41' => array(
		'name' => 'faxNumber',
		'showname' => '传真号',
		'shows' => '1',
		'widths' => '',
		'sorts' => '1',
		'models' => '',
		'sortname' => 'faxNumber',
		'sortnum' => '42',
		'issearch' => '0',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_person_info.faxNumber',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '35',
		'status' => '1',
	),
	'33' => array(
		'name' => 'qq',
		'showname' => 'QQ',
		'shows' => '1',
		'widths' => '',
		'sorts' => '1',
		'models' => '',
		'sortname' => 'qq',
		'sortnum' => '43',
		'issearch' => '1',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_person_info.qq',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '33',
		'status' => '1',
	),
	'32' => array(
		'name' => 'email',
		'showname' => '邮箱',
		'shows' => '1',
		'widths' => '',
		'sorts' => '1',
		'models' => '',
		'sortname' => 'email',
		'sortnum' => '45',
		'issearch' => '0',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_person_info.email',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '33',
		'status' => '1',
	),
);

?>