<?php 
return array(
	'0' => array(
		'name' => 'id',
		'showname' => 'ID',
		'shows' => '０',
		'widths' => '18',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'id',
		'sortnum' => '1',
		'issearch' => '0',
		'isexport' => '1',
		'searchField' => '',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'isallsearch' => '0',
		'searchsortnum' => '0',
		'status' => '1',
		'helpvalue' => '',
	),
	'25' => array(
		'name' => 'disposestage',
		'showname' => '处理阶段',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'disposestage',
		'sortnum' => '4',
		'issearch' => '1',
		'func' => array(
			'0' => array(
				'0' => 'getSelectByname',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => 'disposestage',
					'1' => '###',
					'2' => '',
				),
			),
		),
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_industrial_injury_info.disposestage',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'select|disposestage',
		'isallsearch' => '0',
		'searchsortnum' => '2',
		'status' => '1',
		'helpvalue' => '',
	),
	'1' => array(
		'name' => 'orderno',
		'showname' => '工伤编号',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'orderno',
		'sortnum' => '2',
		'issearch' => '1',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_industrial_injury_info.orderno',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '1',
		'searchsortnum' => '2',
		'status' => '1',
		'helpvalue' => '',
	),
	'2' => array(
		'name' => 'name',
		'showname' => '伤者姓名',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'name',
		'sortnum' => '3',
		'issearch' => '1',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_industrial_injury_info.name',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '1',
		'searchsortnum' => '3',
		'status' => '1',
		'helpvalue' => '',
	),
	'3' => array(
		'name' => 'indate',
		'showname' => '入职日期',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'indate',
		'sortnum' => '5',
		'func' => array(
			'0' => array(
				'0' => 'transTime',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
				),
			),
		),
		'issearch' => '1',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_industrial_injury_info.indate',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'time',
		'isallsearch' => '0',
		'searchsortnum' => '4',
		'status' => '1',
		'helpvalue' => '',
	),
	'4' => array(
		'name' => 'chinaid',
		'showname' => '身份证',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'chinaid',
		'sortnum' => '6',
		'issearch' => '1',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_industrial_injury_info.chinaid',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '5',
		'status' => '1',
		'helpvalue' => '',
	),
	'5' => array(
		'name' => 'address',
		'showname' => '家庭地址',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'address',
		'sortnum' => '7',
		'issearch' => '0',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_industrial_injury_info.address',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '6',
		'status' => '1',
		'helpvalue' => '',
	),
	'8' => array(
		'name' => 'projectid',
		'showname' => '所属工地',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'projectid',
		'sortnum' => '8',
		'issearch' => '0',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_industrial_injury_info.projectid',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '7',
		'status' => '1',
		'helpvalue' => '',
	),
	'7' => array(
		'name' => 'linkmin',
		'showname' => '工地联系人',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'linkmin',
		'sortnum' => '9',
		'issearch' => '0',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_industrial_injury_info.linkmin',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '8',
		'status' => '1',
		'helpvalue' => '',
	),
	'6' => array(
		'name' => 'linktel',
		'showname' => '联系人电话',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'linktel',
		'sortnum' => '10',
		'issearch' => '0',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_industrial_injury_info.linktel',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '9',
		'status' => '1',
		'helpvalue' => '',
	),
	'9' => array(
		'name' => 'accidenttype',
		'showname' => '事故性质',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'accidenttype',
		'sortnum' => '11',
		'issearch' => '0',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_industrial_injury_info.accidenttype',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '10',
		'status' => '1',
		'helpvalue' => '',
	),
	'10' => array(
		'name' => 'accidenttime',
		'showname' => '事故时间',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'accidenttime',
		'sortnum' => '12',
		'func' => array(
			'0' => array(
				'0' => 'transTime',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'Y-m-d H:i',
				),
			),
		),
		'issearch' => '1',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_industrial_injury_info.accidenttime',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'time',
		'isallsearch' => '0',
		'searchsortnum' => '11',
		'status' => '1',
		'helpvalue' => '',
	),
	'11' => array(
		'name' => 'accidentway',
		'showname' => '事故路段',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'accidentway',
		'sortnum' => '13',
		'issearch' => '0',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_industrial_injury_info.accidentway',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '12',
		'status' => '1',
		'helpvalue' => '',
	),
	'12' => array(
		'name' => 'eyewitness',
		'showname' => '事故见证人',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'eyewitness',
		'sortnum' => '14',
		'issearch' => '0',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_industrial_injury_info.eyewitness',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '13',
		'status' => '1',
		'helpvalue' => '',
	),
	'15' => array(
		'name' => 'firstinfirmary',
		'showname' => '首次就医地点',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'firstinfirmary',
		'sortnum' => '15',
		'issearch' => '0',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_industrial_injury_info.firstinfirmary',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '14',
		'status' => '1',
		'helpvalue' => '',
	),
	'14' => array(
		'name' => 'hurtcondition',
		'showname' => '伤势情况',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'hurtcondition',
		'sortnum' => '16',
		'issearch' => '1',
		'func' => array(
			'0' => array(
				'0' => 'getSelectByname',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => 'hurtcondition',
					'1' => '###',
					'2' => '',
				),
			),
		),
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_industrial_injury_info.hurtcondition',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'select|hurtcondition',
		'isallsearch' => '0',
		'searchsortnum' => '15',
		'status' => '1',
		'helpvalue' => '',
	),
	'13' => array(
		'name' => 'hurtpart',
		'showname' => '伤害部位',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'hurtpart',
		'sortnum' => '17',
		'issearch' => '0',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_industrial_injury_info.hurtpart',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '16',
		'status' => '1',
		'helpvalue' => '',
	),
	'16' => array(
		'name' => 'referralone',
		'showname' => '转诊就医地点1',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'referralone',
		'sortnum' => '18',
		'issearch' => '0',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_industrial_injury_info.referralone',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '17',
		'status' => '1',
		'helpvalue' => '',
	),
	'17' => array(
		'name' => 'referraltwo',
		'showname' => '伤者岗位',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'referraltwo',
		'sortnum' => '19',
		'issearch' => '0',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_industrial_injury_info.referraltwo',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '18',
		'status' => '1',
		'helpvalue' => '',
	),
	'18' => array(
		'name' => 'reportcutdate',
		'showname' => '申报工伤截止日期',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'reportcutdate',
		'sortnum' => '20',
		'func' => array(
			'0' => array(
				'0' => 'transTime',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
				),
			),
		),
		'issearch' => '0',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_industrial_injury_info.reportcutdate',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'time',
		'isallsearch' => '0',
		'searchsortnum' => '19',
		'status' => '1',
		'helpvalue' => '',
	),
	'19' => array(
		'name' => 'prosubdate',
		'showname' => '工地上报时间',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'prosubdate',
		'sortnum' => '21',
		'func' => array(
			'0' => array(
				'0' => 'transTime',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
				),
			),
		),
		'issearch' => '0',
		'findtype' => 'time',
		'findtable' => '',
		'findfield' => '',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_industrial_injury_info.prosubdate',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'time',
		'isallsearch' => '0',
		'searchsortnum' => '20',
		'status' => '1',
		'helpvalue' => '',
	),
	'20' => array(
		'name' => 'databjdate',
		'showname' => '资料备齐时间',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'databjdate',
		'sortnum' => '22',
		'func' => array(
			'0' => array(
				'0' => 'transTime',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
				),
			),
		),
		'issearch' => '0',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_industrial_injury_info.databjdate',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '21',
		'status' => '1',
		'helpvalue' => '',
	),
	'21' => array(
		'name' => 'reportinfo',
		'showname' => '报工伤情况',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'reportinfo',
		'sortnum' => '23',
		'issearch' => '0',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_industrial_injury_info.reportinfo',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '22',
		'status' => '1',
		'helpvalue' => '',
	),
	'22' => array(
		'name' => 'reportmaintain',
		'showname' => '工伤认定',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'reportmaintain',
		'sortnum' => '24',
		'issearch' => '0',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_industrial_injury_info.reportmaintain',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '23',
		'status' => '1',
		'helpvalue' => '',
	),
	'23' => array(
		'name' => 'elcomercioreport',
		'showname' => '商保报案',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'elcomercioreport',
		'sortnum' => '25',
		'issearch' => '0',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_industrial_injury_info.elcomercioreport',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '24',
		'status' => '1',
		'helpvalue' => '',
	),
	'24' => array(
		'name' => 'elcomercioreportcode',
		'showname' => '商保报案号',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'elcomercioreportcode',
		'sortnum' => '26',
		'issearch' => '0',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_industrial_injury_info.elcomercioreportcode',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '25',
		'status' => '1',
		'helpvalue' => '',
	),
	'26' => array(
		'name' => 'sumcost',
		'showname' => '共计医疗费用',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'sumcost',
		'sortnum' => '27',
		'issearch' => '0',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_industrial_injury_info.sumcost',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '27',
		'status' => '1',
		'helpvalue' => '',
	),
	'27' => array(
		'name' => 'bxcost',
		'showname' => '社保报销',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'bxcost',
		'sortnum' => '28',
		'issearch' => '0',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_industrial_injury_info.bxcost',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '28',
		'status' => '1',
		'helpvalue' => '',
	),
	'28' => array(
		'name' => 'businesscost',
		'showname' => '商保报销',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'businesscost',
		'sortnum' => '29',
		'issearch' => '0',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_industrial_injury_info.businesscost',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '29',
		'status' => '1',
		'helpvalue' => '',
	),
	'29' => array(
		'name' => 'companycost',
		'showname' => '公司支付',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'companycost',
		'sortnum' => '30',
		'issearch' => '0',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_industrial_injury_info.companycost',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '30',
		'status' => '1',
		'helpvalue' => '',
	),
	'30' => array(
		'name' => 'socialsecurity',
		'showname' => '社保申报时间',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'socialsecurity',
		'sortnum' => '31',
		'func' => array(
			'0' => array(
				'0' => 'transTime',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
				),
			),
		),
		'issearch' => '0',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_industrial_injury_info.socialsecurity',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'time',
		'isallsearch' => '0',
		'searchsortnum' => '31',
		'status' => '1',
		'helpvalue' => '',
	),
	'31' => array(
		'name' => 'collecteddate',
		'showname' => '社保预计到账时间',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'collecteddate',
		'sortnum' => '32',
		'func' => array(
			'0' => array(
				'0' => 'transTime',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
				),
			),
		),
		'issearch' => '0',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_industrial_injury_info.collecteddate',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '32',
		'status' => '1',
		'helpvalue' => '',
	),
	'32' => array(
		'name' => 'financeok',
		'showname' => '财务到账确认',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'financeok',
		'sortnum' => '33',
		'issearch' => '0',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_industrial_injury_info.financeok',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '33',
		'status' => '1',
		'helpvalue' => '',
	),
	'33' => array(
		'name' => 'businestime',
		'showname' => '商保申报时间',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'businestime',
		'sortnum' => '34',
		'func' => array(
			'0' => array(
				'0' => 'transTime',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
				),
			),
		),
		'issearch' => '0',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_industrial_injury_info.businestime',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '34',
		'status' => '1',
		'helpvalue' => '',
	),
	'34' => array(
		'name' => 'businescolltime',
		'showname' => '商保预计到账时间',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'businescolltime',
		'sortnum' => '35',
		'func' => array(
			'0' => array(
				'0' => 'transTime',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
				),
			),
		),
		'issearch' => '0',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_industrial_injury_info.businescolltime',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '35',
		'status' => '1',
		'helpvalue' => '',
	),
	'35' => array(
		'name' => 'maimidentify',
		'showname' => '伤残鉴定',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'maimidentify',
		'sortnum' => '36',
		'issearch' => '0',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_industrial_injury_info.maimidentify',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '36',
		'status' => '1',
		'helpvalue' => '',
	),
	'36' => array(
		'name' => 'manmlevel',
		'showname' => '伤残等级',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'manmlevel',
		'sortnum' => '37',
		'issearch' => '0',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_industrial_injury_info.manmlevel',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '37',
		'status' => '1',
		'helpvalue' => '',
	),
	'37' => array(
		'name' => 'socialselipei',
		'showname' => '社保理赔',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'socialselipei',
		'sortnum' => '38',
		'issearch' => '0',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_industrial_injury_info.socialselipei',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '38',
		'status' => '1',
		'helpvalue' => '',
	),
	'38' => array(
		'name' => 'busineslipei',
		'showname' => '商保理赔',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'busineslipei',
		'sortnum' => '39',
		'issearch' => '0',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_industrial_injury_info.busineslipei',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '39',
		'status' => '1',
		'helpvalue' => '',
	),
	'39' => array(
		'name' => 'companylipei',
		'showname' => '公司理赔',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'companylipei',
		'sortnum' => '40',
		'issearch' => '0',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_industrial_injury_info.companylipei',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '40',
		'status' => '1',
		'helpvalue' => '',
	),
	'40' => array(
		'name' => 'accidentpass',
		'showname' => '事故简要经过',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'accidentpass',
		'sortnum' => '41',
		'issearch' => '0',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_industrial_injury_info.accidentpass',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '41',
		'status' => '1',
		'helpvalue' => '',
	),
	'41' => array(
		'name' => 'remark',
		'showname' => '备注',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'remark',
		'sortnum' => '42',
		'issearch' => '0',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_industrial_injury_info.remark',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '42',
		'status' => '1',
		'helpvalue' => '',
	),
	'42' => array(
		'name' => 'createtime',
		'showname' => '创建时间',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'createtime',
		'sortnum' => '43',
		'func' => array(
			'0' => array(
				'0' => 'transTime',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
				),
			),
		),
		'issearch' => '0',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_industrial_injury_info.createtime',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '43',
		'status' => '1',
		'helpvalue' => '',
	),
	'43' => array(
		'name' => 'createid',
		'showname' => '创建人',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'createid',
		'sortnum' => '44',
		'issearch' => '1',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_industrial_injury_info.createid',
		'table' => 'user',
		'field' => 'id',
		'conditions' => '',
		'type' => 'db',
		'isallsearch' => '0',
		'searchsortnum' => '44',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'User',
				),
			),
		),
		'status' => '1',
		'helpvalue' => '',
	),
	'44' => array(
		'name' => 'updatetime',
		'showname' => '修改时间',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'updatetime',
		'sortnum' => '45',
		'func' => array(
			'0' => array(
				'0' => 'transTime',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
				),
			),
		),
		'issearch' => '0',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_industrial_injury_info.updatetime',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '45',
		'status' => '1',
		'helpvalue' => '',
	),
	'45' => array(
		'name' => 'updateid',
		'showname' => '修改人',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'updateid',
		'sortnum' => '46',
		'issearch' => '0',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_industrial_injury_info.updateid',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '46',
		'status' => '1',
		'helpvalue' => '',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'User',
				),
			),
		),
	),
	'47' => array(
		'name' => 'thirdpay',
		'showname' => '第三方支付',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'thirdpay',
		'sortnum' => '47',
		'issearch' => '0',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_industrial_injury_info.thirdpay',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '46',
		'status' => '1',
		'helpvalue' => '',
	),
	'48' => array(
		'name' => 'thirdpay',
		'showname' => '路标级别',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'thirdpay',
		'sortnum' => '48',
		'issearch' => '0',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_industrial_injury_info.thirdpay',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '46',
		'status' => '1',
		'helpvalue' => '',
	),
	'49' => array(
		'name' => 'companylipeitime',
		'showname' => '公司理赔时间',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'companylipeitime',
		'sortnum' => '49',
		'issearch' => '0',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_industrial_injury_info.companylipeitime',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '46',
		'status' => '1',
		'helpvalue' => '',
	),
	'50' => array(
		'name' => 'busineslipeitime',
		'showname' => '商业理赔时间',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'busineslipeitime',
		'sortnum' => '50',
		'issearch' => '0',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_industrial_injury_info.busineslipeitime',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '46',
		'status' => '1',
		'helpvalue' => '',
	),
	'51' => array(
		'name' => 'persioncost',
		'showname' => '员工个人支付',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'persioncost',
		'sortnum' => '51',
		'issearch' => '0',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_industrial_injury_info.persioncost',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '46',
		'status' => '1',
		'helpvalue' => '',
	),
	'53' => array(
		'name' => 'depaid',
		'showname' => '部门',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'depaid',
		'sortnum' => '52',
		'issearch' => '0',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_industrial_injury_info.depaid',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '54',
		'status' => '1',
		'helpvalue' => '',
	),
	'56' => array(
		'name' => 'phone',
		'showname' => '联系电话',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'phone',
		'sortnum' => '53',
		'issearch' => '1',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_industrial_injury_info.phone',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '57',
		'status' => '1',
		'helpvalue' => '',
	),
	'70' => array(
		'name' => 'action',
		'showname' => '操作',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'status',
		'sortnum' => '54',
		'issearch' => '0',
		'searchField' => '',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'isallsearch' => '0',
		'searchsortnum' => '0',
		'status' => '1',
		'extention_html_end' => array(
			'0' => ' ',
		),
		'func' => array(
			'0' => array(
				'0' => 'getOperateStatus',
			),
			'1' => array(
				'0' => 'getStatus',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '#createid#',
					'1' => '#auditState#',
					'2' => 'id/#id#',
					'3' => '',
					'4' => '',
					'5' => 'navTab',
					'6' => '人事工伤',
				),
			),
			'1' => array(
				'0' => array(
					'0' => '#status#',
				),
			),
		),
		'helpvalue' => '',
	),
);

?>