<?php 
return array(
	'0' => array(
		'name' => 'nd',
		'showname' => '序号',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'nd',
		'sortnum' => '1',
		'searchField' => '',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '0',
	),
	'1' => array(
		'name' => 'prodid',
		'showname' => '物料编号',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'prodid',
		'sortnum' => '2',
		'searchField' => 'prodid',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '0',
	),
	'2' => array(
		'name' => 'pcode',
		'showname' => '物料代码',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'pcode',
		'sortnum' => '3',
		'searchField' => 'mis_product_code.code',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '0',
	),
	'3' => array(
		'name' => 'pname',
		'showname' => '物料名称',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'pname',
		'sortnum' => '4',
		'searchField' => 'mis_product_code.name',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '0',
	),
	'15' => array(
		'name' => 'baseunitid',
		'showname' => '产品主单位',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'baseunitid',
		'sortnum' => '5',
		'func' => array(
			'0' => array(
				'0' => 'getUnitsNames',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '#prodid#',
					'1' => '',
				),
			),
		),
		'searchField' => 'baseunitid',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '0',
	),
	'14' => array(
		'name' => 'transqty',
		'showname' => '主单位数量',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'qty',
		'sortnum' => '6',
		'func' => array(
			'0' => array(
				'0' => 'getAfterExchangeFormatQty',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '#unitid#',
					'1' => '#qty#',
					'2' => '#0#',
					'3' => '#prodid#',
				),
			),
		),
		'searchField' => 'transqty',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '0',
	),
	'4' => array(
		'name' => 'unitid',
		'showname' => '单位',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'unitid',
		'func' => array(
			'0' => array(
				'0' => 'getUnitsNames2',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '#prodid#',
					'1' => '###',
					'2' => '',
				),
			),
		),
		'sortnum' => '7',
		'searchField' => 'unitid',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '0',
	),
	'5' => array(
		'name' => 'qty',
		'showname' => '数量',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'qty',
		'sortnum' => '8',
		'func' => array(
			'0' => array(
				'0' => 'getDigits',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => '#true#',
					'2' => '#prodid#',
					'3' => '#unitid#',
				),
			),
		),
		'searchField' => 'qty',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '0',
	),
	'6' => array(
		'name' => 'price',
		'showname' => '单价',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'price',
		'func' => array(
			'0' => array(
				'0' => 'getDigits',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
				),
			),
		),
		'sortnum' => '9',
		'searchField' => 'price',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '0',
	),
	'7' => array(
		'name' => 'amount',
		'showname' => '金额',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'amount',
		'func' => array(
			'0' => array(
				'0' => 'getDigits',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
				),
			),
		),
		'sortnum' => '10',
		'searchField' => 'amount',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '0',
	),
	'8' => array(
		'name' => 'weight',
		'showname' => '重量',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'weight',
		'func' => array(
			'0' => array(
				'0' => 'getWeightOrCapacityAndUnit',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => '2',
				),
			),
		),
		'sortnum' => '11',
		'searchField' => 'weight',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '0',
	),
	'9' => array(
		'name' => 'capacity',
		'showname' => '体积',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'capacity',
		'func' => array(
			'0' => array(
				'0' => 'getWeightOrCapacityAndUnit',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => '1',
				),
			),
		),
		'sortnum' => '12',
		'searchField' => 'capacity',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '0',
	),
	'10' => array(
		'name' => 'whid',
		'showname' => '仓库',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'whid',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'mis_inventory_warehouse',
				),
			),
		),
		'sortnum' => '13',
		'searchField' => 'whid',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '0',
	),
	'11' => array(
		'name' => 'areaid',
		'showname' => '库区',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'areaid',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'mis_inventory_warehouse_area',
				),
			),
		),
		'sortnum' => '14',
		'searchField' => 'areaid',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '0',
	),
	'12' => array(
		'name' => 'shelfid',
		'showname' => '库位',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'shelfid',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'mis_inventory_warehouse_area',
				),
			),
		),
		'sortnum' => '15',
		'searchField' => 'shelfid',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '0',
	),
	'13' => array(
		'name' => 'ostatus',
		'showname' => '状态',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'ostatus',
		'func' => array(
			'0' => array(
				'0' => 'getTraceStatus',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
				),
			),
		),
		'sortnum' => '16',
		'searchField' => 'ostatus',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '0',
	),
);

?>