<?php 
return array(
	'modelname' => array(
		'name' => 'modelname',
		'showname' => '模型名称',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'modelname',
		'sortnum' => '0',
		'shows' => '1',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => '',
		'fieldcategory' => 'text',
		'searchField' => 'mis_system_client_change_role.modelname',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '0',
		'table' => 'node',
		'field' => 'orderno',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'name',
					'2' => 'title',
					'3' => 'node',
				),
			),
		),
	),
	'id' => array(
		'name' => 'id',
		'showname' => 'ID',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'id',
		'sortnum' => '0',
		'searchField' => '',
		'conditions' => '',
		'type' => '',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '0',
		'table' => '',
		'field' => '',
		'status' => '1',
		'rules' => '0',
		'message' => '0',
	),
	'userid' => array(
		'name' => 'userid',
		'showname' => '用户名称',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'userid',
		'sortnum' => '1',
		'shows' => '1',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'varchar',
		'fieldcategory' => 'lookup',
		'searchField' => 'mis_system_client_change_role.userid',
		'conditions' => '',
		'type' => 'db',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'user',
				),
			),
		),
		'table' => 'user',
		'field' => 'id',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '1',
	),
	'fieldname' => array(
		'name' => 'fieldname',
		'showname' => '授权字段',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'fieldname',
		'sortnum' => '2',
		'shows' => '0',
		'status' => '1',
		'rules' => '0',
		'message' => '0',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'varchar',
		'fieldcategory' => 'lookup',
		'searchField' => 'mis_system_client_change_role.fieldname',
		'conditions' => '',
		'type' => '',
		'table' => '',
		'field' => '',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '2',
	),
	'content' => array(
		'name' => 'content',
		'showname' => '授权内容',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'content',
		'sortnum' => '3',
		'shows' => '1',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'varchar',
		'fieldcategory' => 'text',
		'searchField' => 'mis_system_client_change_role.content',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '3',
		'table' => 'mis_system_client_change_role',
		'field' => 'content',
	),
	'createid' => array(
		'name' => 'createid',
		'showname' => '创建人',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'createid',
		'sortnum' => '4',
		'shows' => '1',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'decimal',
		'fieldcategory' => 'text',
		'searchField' => 'mis_system_client_change_role.createid',
		'conditions' => '',
		'type' => 'db',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'user',
				),
			),
		),
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '4',
		'table' => 'user',
		'field' => 'id',
	),
);

?>