<?php 
return array(
	'0' => array(
		'name' => 'id',
		'showname' => '编号',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'id',
		'sortnum' => '1',
		'issearch' => '',
		'isexport' => '1',
		'searchField' => '',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'isallsearch' => '',
		'searchsortnum' => '',
		'helpvalue' => '',
	),
	'1' => array(
		'name' => 'inviteresources',
		'showname' => '招聘渠道',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'inviteresources',
		'sortnum' => '2',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'mis_hr_typeinfo',
				),
			),
		),
		'issearch' => '1',
		'isexport' => '1',
		'searchField' => 'mis_hr_invitere_form.inviteresources',
		'table' => 'mis_hr_typeinfo',
		'field' => 'id',
		'conditions' => 'pid=41',
		'type' => 'group',
		'isallsearch' => '1',
		'searchsortnum' => '2',
		'helpvalue' => '',
	),
	'16' => array(
		'name' => 'introducemethod',
		'showname' => '招聘方式',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'interviewfirst',
		'sortnum' => '3',
		'issearch' => '1',
		'isexport' => '1',
		'searchField' => 'mis_hr_invitere_form.introducemethod',
		'table' => 'mis_hr_typeinfo',
		'field' => 'id',
		'conditions' => 'pid=100',
		'type' => 'group',
		'isallsearch' => '',
		'searchsortnum' => '3',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'mis_hr_typeinfo',
				),
			),
		),
		'helpvalue' => '',
	),
	'2' => array(
		'name' => 'datetime',
		'showname' => '预约时间',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'datetime',
		'sortnum' => '4',
		'issearch' => '1',
		'isexport' => '1',
		'searchField' => 'mis_hr_invitere_form.datetime',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'time',
		'isallsearch' => '',
		'searchsortnum' => '4',
		'func' => array(
			'0' => array(
				'0' => 'transTime',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'Y-m-d H:i',
				),
			),
		),
		'helpvalue' => '',
	),
	'3' => array(
		'name' => 'interviewposition',
		'showname' => '应聘岗位',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'interviewposition',
		'sortnum' => '5',
		'issearch' => '1',
		'isexport' => '1',
		'searchField' => 'mis_hr_invitere_form.interviewposition',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '1',
		'searchsortnum' => '5',
		'helpvalue' => '',
	),
	'4' => array(
		'name' => 'name',
		'showname' => '姓名',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'name',
		'sortnum' => '6',
		'issearch' => '1',
		'isexport' => '1',
		'searchField' => 'mis_hr_invitere_form.name',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '1',
		'searchsortnum' => '6',
		'helpvalue' => '',
	),
	'5' => array(
		'name' => 'sex',
		'showname' => '性别',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'sex',
		'sortnum' => '7',
		'func' => array(
			'0' => array(
				'0' => 'excelTplselected',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => '1:男,0:女',
				),
			),
		),
		'issearch' => '1',
		'isexport' => '1',
		'searchField' => 'mis_hr_invitere_form.sex',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'select|sex',
		'isallsearch' => '',
		'searchsortnum' => '7',
		'helpvalue' => '',
	),
	'6' => array(
		'name' => 'age',
		'showname' => '年龄',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'age',
		'sortnum' => '8',
		'issearch' => '1',
		'isexport' => '1',
		'searchField' => 'mis_hr_invitere_form.age',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '',
		'searchsortnum' => '8',
		'helpvalue' => '',
	),
	'7' => array(
		'name' => 'education',
		'showname' => '学历',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'education',
		'sortnum' => '9',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'mis_hr_typeinfo',
				),
			),
		),
		'issearch' => '',
		'isexport' => '1',
		'searchField' => 'mis_hr_invitere_form.education',
		'table' => 'mis_hr_typeinfo',
		'field' => 'id',
		'conditions' => '',
		'type' => 'db',
		'isallsearch' => '',
		'searchsortnum' => '9',
		'helpvalue' => '',
	),
	'8' => array(
		'name' => 'professional',
		'showname' => '专业',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'professional',
		'sortnum' => '10',
		'issearch' => '',
		'isexport' => '1',
		'searchField' => 'mis_hr_invitere_form.professional',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '',
		'searchsortnum' => '10',
		'helpvalue' => '',
	),
	'9' => array(
		'name' => 'nativeplace',
		'showname' => '籍贯',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'nativeplace',
		'sortnum' => '11',
		'issearch' => '',
		'isexport' => '1',
		'searchField' => 'mis_hr_invitere_form.nativeplace',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '',
		'searchsortnum' => '11',
		'helpvalue' => '',
	),
	'10' => array(
		'name' => 'senioritypay',
		'showname' => '工作年限',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'senioritypay',
		'sortnum' => '12',
		'issearch' => '1',
		'isexport' => '1',
		'searchField' => 'mis_hr_invitere_form.senioritypay',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '',
		'searchsortnum' => '12',
		'helpvalue' => '',
	),
	'11' => array(
		'name' => 'contacttel',
		'showname' => '联系方式',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'contacttel',
		'sortnum' => '13',
		'issearch' => '1',
		'isexport' => '1',
		'searchField' => 'mis_hr_invitere_form.contacttel',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '',
		'searchsortnum' => '13',
		'helpvalue' => '',
	),
	'12' => array(
		'name' => 'interviewtime',
		'showname' => '面试时间',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'interviewtime',
		'sortnum' => '14',
		'issearch' => '1',
		'isexport' => '1',
		'searchField' => 'mis_hr_invitere_form.interviewtime',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'time',
		'isallsearch' => '',
		'searchsortnum' => '14',
		'func' => array(
			'0' => array(
				'0' => 'transTime',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'Y-m-d H:i',
				),
			),
		),
		'helpvalue' => '',
	),
	'13' => array(
		'name' => 'interviewfirst',
		'showname' => '初试结果',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'interviewfirst',
		'sortnum' => '15',
		'issearch' => '1',
		'isexport' => '1',
		'searchField' => 'mis_hr_invitere_form.interviewfirst',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'select|interviewfirst',
		'isallsearch' => '',
		'searchsortnum' => '15',
		'func' => array(
			'0' => array(
				'0' => 'excelTplselected',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => '1:合格,0:不合格,2:放入人才库,3:待定,4:未面试',
				),
			),
		),
		'helpvalue' => '',
	),
	'14' => array(
		'name' => 'interviewagain',
		'showname' => '复式结果',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'interviewagain',
		'sortnum' => '16',
		'issearch' => '1',
		'isexport' => '1',
		'searchField' => 'mis_hr_invitere_form.interviewagain',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'select|interviewfirst',
		'isallsearch' => '',
		'searchsortnum' => '16',
		'func' => array(
			'0' => array(
				'0' => 'excelTplselected',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => '1:合格,0:不合格,2:放入人才库,3:待定,4:未面试',
				),
			),
		),
		'helpvalue' => '',
	),
	'15' => array(
		'name' => 'joinedtime',
		'showname' => '待入职时间',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'joinedtime',
		'sortnum' => '17',
		'issearch' => '1',
		'func' => array(
			'0' => array(
				'0' => 'transTime',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
				),
			),
		),
		'isexport' => '1',
		'searchField' => 'mis_hr_invitere_form.joinedtime',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'time',
		'isallsearch' => '',
		'searchsortnum' => '17',
		'helpvalue' => '',
	),
	'17' => array(
		'name' => 'remark',
		'showname' => '备注',
		'shows' => '0',
		'widths' => '200',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'remark',
		'sortnum' => '18',
		'issearch' => '1',
		'func' => array(
			'0' => array(
				'0' => 'missubstr',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => '20',
					'2' => 'true',
				),
			),
		),
		'isexport' => '1',
		'searchField' => 'mis_hr_invitere_form.remark',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '',
		'searchsortnum' => '18',
		'helpvalue' => '',
	),
	'19' => array(
		'name' => 'isinjob',
		'showname' => '入职',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'isinjob',
		'sortnum' => '19',
		'issearch' => '1',
		'isexport' => '1',
		'searchField' => 'mis_hr_invitere_form.isinjob',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'select|isinjob',
		'isallsearch' => '',
		'searchsortnum' => '20',
		'helpvalue' => '',
	),
	'18' => array(
		'name' => 'action',
		'showname' => '状态',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'status',
		'sortnum' => '20',
		'issearch' => '',
		'searchField' => '',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'isallsearch' => '',
		'searchsortnum' => '',
		'status' => '1',
		'extention_html_end' => array(
			'0' => ' ',
		),
		'func' => array(
			'0' => array(
				'0' => 'getStatus',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '#status#',
				),
			),
		),
		'helpvalue' => '',
	),
);

?>