<?php 
return array(
	'0' => array(
		'name' => 'id',
		'showname' => '编号',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'id',
		'sortnum' => '1',
		'issearch' => '',
		'searchField' => '',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'isallsearch' => '',
		'searchsortnum' => '',
	),
	'16' => array(
		'name' => 'fnum',
		'showname' => '证明号',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'fnum',
		'sortnum' => '2',
		'issearch' => '',
		'searchField' => 'mis_finance_orgcertif_mas.fnum',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '',
		'searchsortnum' => '2',
	),
	'2' => array(
		'name' => 'unitname',
		'showname' => '单位名称',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'unitname',
		'sortnum' => '3',
		'issearch' => '1',
		'searchField' => 'mis_finance_orgcertif_mas.unitname',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '1',
		'searchsortnum' => '3',
	),
	'1' => array(
		'name' => 'handledate',
		'showname' => '单据日期',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'handledate',
		'sortnum' => '4',
		'func' => array(
			'0' => array(
				'0' => 'transTime',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
				),
			),
		),
		'issearch' => '1',
		'searchField' => 'mis_finance_orgcertif_mas.handledate',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'time',
		'isallsearch' => '',
		'searchsortnum' => '4',
	),
	'3' => array(
		'name' => 'summary',
		'showname' => '摘要',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'summary',
		'sortnum' => '5',
		'issearch' => '1',
		'searchField' => 'mis_finance_orgcertif_mas.summary',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '1',
		'searchsortnum' => '5',
	),
	'4' => array(
		'name' => 'totalamount',
		'showname' => '总金额',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'totalamount',
		'sortnum' => '6',
		'issearch' => '',
		'func' => array(
			'0' => array(
				'0' => 'getDigits',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
				),
			),
		),
		'searchField' => 'mis_finance_orgcertif_mas.totalamount',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '',
		'searchsortnum' => '6',
	),
	'6' => array(
		'name' => 'typeid',
		'showname' => '类型',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'typeid',
		'sortnum' => '7',
		'issearch' => '1',
		'func' => array(
			'0' => array(
				'0' => 'getFieldby',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'mis_finance_order_types',
				),
			),
		),
		'searchField' => 'mis_finance_orgcertif_mas.typeid',
		'table' => 'mis_finance_order_types',
		'field' => 'id',
		'conditions' => 'type=MisFinanceOrgcertifMas',
		'type' => 'group',
		'isallsearch' => '',
		'searchsortnum' => '7',
	),
	'8' => array(
		'name' => 'projectid',
		'showname' => '项目',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'projectid',
		'sortnum' => '8',
		'issearch' => '1',
		'func' => array(
			'0' => array(
				'0' => 'getFieldby',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'mis_sales_project',
				),
			),
		),
		'searchField' => 'mis_finance_orgcertif_mas.projectid',
		'table' => 'mis_sales_project',
		'field' => 'id',
		'conditions' => '',
		'type' => 'db',
		'isallsearch' => '1',
		'searchsortnum' => '8',
	),
	'9' => array(
		'name' => 'deptid',
		'showname' => '部门',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'deptid',
		'sortnum' => '9',
		'issearch' => '1',
		'func' => array(
			'0' => array(
				'0' => 'getFieldby',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'mis_system_department',
				),
			),
		),
		'searchField' => 'mis_finance_orgcertif_mas.deptid',
		'table' => 'mis_system_department',
		'field' => 'id',
		'conditions' => '',
		'type' => 'db',
		'isallsearch' => '',
		'searchsortnum' => '9',
	),
	'10' => array(
		'name' => 'userid',
		'showname' => '用户',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'userid',
		'sortnum' => '10',
		'issearch' => '1',
		'func' => array(
			'0' => array(
				'0' => 'getFieldby',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'user',
				),
			),
		),
		'searchField' => 'mis_finance_orgcertif_mas.userid',
		'table' => 'user',
		'field' => 'id',
		'conditions' => '',
		'type' => 'db',
		'isallsearch' => '',
		'searchsortnum' => '10',
	),
	'11' => array(
		'name' => 'remittee',
		'showname' => '汇款对象',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'remittee',
		'sortnum' => '11',
		'issearch' => '1',
		'searchField' => 'mis_finance_orgcertif_mas.remittee',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '',
		'searchsortnum' => '11',
	),
	'12' => array(
		'name' => 'bankname',
		'showname' => '收款方开户行',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'bankname',
		'sortnum' => '12',
		'issearch' => '1',
		'searchField' => 'mis_finance_orgcertif_mas.bankname',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '',
		'searchsortnum' => '12',
	),
	'13' => array(
		'name' => 'bankaccount',
		'showname' => '收款方账号',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'bankaccount',
		'sortnum' => '13',
		'issearch' => '1',
		'searchField' => 'mis_finance_orgcertif_mas.bankaccount',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '',
		'searchsortnum' => '13',
	),
	'14' => array(
		'name' => 'auditState',
		'showname' => '审核状态',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'auditState',
		'func' => array(
			'0' => array(
				'0' => 'getAuditState',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => '#id#',
					'2' => '#ptmptid#',
				),
			),
		),
		'sortnum' => '15',
		'issearch' => '',
		'searchField' => 'mis_finance_orgcertif_mas.auditState',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '',
		'searchsortnum' => '15',
	),
	'15' => array(
		'name' => 'action',
		'showname' => '操作',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'status',
		'sortnum' => '16',
		'issearch' => '',
		'searchField' => '',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'isallsearch' => '',
		'searchsortnum' => '',
		'status' => '1',
		'extention_html_end' => array(
			'0' => ' ',
		),
		'func' => array(
			'0' => array(
				'0' => 'getOperateStatus',
			),
			'1' => array(
				'0' => 'getStatus',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '#createid#',
					'1' => '#auditState#',
					'2' => 'id/#id#',
					'3' => '',
					'4' => '',
					'5' => 'navTab',
					'6' => '支出证明',
				),
			),
			'1' => array(
				'0' => array(
					'0' => '#status#',
				),
			),
		),
	),
);

?>