<?php 
return array(
	'0' => array(
		'name' => 'id',
		'showname' => 'ID',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'id',
		'sortnum' => '1',
		'searchField' => '',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'issearch' => '',
		'isallsearch' => '',
		'searchsortnum' => '',
	),
	'1' => array(
		'name' => 'orderno',
		'showname' => '课程编号',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'orderno',
		'sortnum' => '2',
		'searchField' => 'mis_hr_evaluation_train.orderno',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '2',
	),
	'2' => array(
		'name' => 'name',
		'showname' => '课程名称',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'name',
		'sortnum' => '3',
		'searchField' => 'mis_hr_evaluation_train.name',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '3',
	),
	'3' => array(
		'name' => 'type',
		'showname' => '课程类型',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'type',
		'sortnum' => '4',
		'searchField' => 'mis_hr_evaluation_train.type',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'select|bxkctype',
		'issearch' => '1',
		'isallsearch' => '',
		'searchsortnum' => '4',
	),
	'4' => array(
		'name' => 'classsource',
		'showname' => '课程来源',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'classsource',
		'sortnum' => '5',
		'searchField' => 'mis_hr_evaluation_train.classsource',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'select|bxkcclasssource',
		'issearch' => '1',
		'isallsearch' => '',
		'searchsortnum' => '5',
	),
	'5' => array(
		'name' => 'lecturer',
		'showname' => '培训讲师',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'lecturer',
		'sortnum' => '6',
		'searchField' => 'mis_hr_evaluation_train.lecturer',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '6',
	),
	'6' => array(
		'name' => 'level',
		'showname' => '讲师等级',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'level',
		'sortnum' => '7',
		'searchField' => 'mis_hr_evaluation_train.level',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'select|bxkclevel',
		'issearch' => '1',
		'isallsearch' => '',
		'searchsortnum' => '7',
	),
	'7' => array(
		'name' => 'traintime',
		'showname' => '培训时间',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'traintime',
		'sortnum' => '8',
		'func' => array(
			'0' => array(
				'0' => 'transTime',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'Y-m-d H:i',
				),
			),
		),
		'searchField' => 'mis_hr_evaluation_train.traintime',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'time',
		'issearch' => '1',
		'isallsearch' => '',
		'searchsortnum' => '8',
	),
	'8' => array(
		'name' => 'site',
		'showname' => '培训地点',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'site',
		'sortnum' => '9',
		'searchField' => 'mis_hr_evaluation_train.site',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '1',
		'isallsearch' => '',
		'searchsortnum' => '9',
	),
	'9' => array(
		'name' => 'classhour',
		'showname' => '培训课时',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'classhour',
		'sortnum' => '10',
		'searchField' => 'mis_hr_evaluation_train.classhour',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '',
		'isallsearch' => '',
		'searchsortnum' => '10',
	),
	'10' => array(
		'name' => 'trainform',
		'showname' => '培训形式',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'trainform',
		'sortnum' => '11',
		'searchField' => 'mis_hr_evaluation_train.trainform',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'select|bxkctrainform',
		'issearch' => '1',
		'isallsearch' => '',
		'searchsortnum' => '11',
	),
	'11' => array(
		'name' => 'assessment',
		'showname' => '考核方式',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'assessment',
		'sortnum' => '12',
		'searchField' => 'mis_hr_evaluation_train.assessment',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'select|bxkcassessment',
		'issearch' => '1',
		'isallsearch' => '',
		'searchsortnum' => '12',
	),
	'12' => array(
		'name' => 'traincost',
		'showname' => '培训费用',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'traincost',
		'sortnum' => '13',
		'searchField' => 'mis_hr_evaluation_train.traincost',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '',
		'isallsearch' => '',
		'searchsortnum' => '13',
	),
	'13' => array(
		'name' => 'curriculumvalue',
		'showname' => '课程分值',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'curriculumvalue',
		'sortnum' => '14',
		'searchField' => 'mis_hr_evaluation_train.curriculumvalue',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '',
		'isallsearch' => '',
		'searchsortnum' => '14',
	),
	'14' => array(
		'name' => 'syllabus',
		'showname' => '课程大纲',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'syllabus',
		'sortnum' => '15',
		'searchField' => 'mis_hr_evaluation_train.syllabus',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '',
		'isallsearch' => '',
		'searchsortnum' => '15',
	),
	'15' => array(
		'name' => 'action',
		'showname' => '审核',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'status',
		'sortnum' => '16',
		'issearch' => '',
		'searchField' => '',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'isallsearch' => '',
		'searchsortnum' => '',
		'status' => '1',
		'func' => array(
			'1' => array(
				'0' => 'getStatusWithRel',
			),
		),
		'funcdata' => array(
			'1' => array(
				'0' => array(
					'0' => '#status#',
					'1' => '#id#',
					'2' => '',
					'3' => '',
					'4' => 'mishrevaluationtrainmodel',
				),
			),
		),
	),
	'16' => array(
		'name' => 'year_date',
		'showname' => '操作',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'status',
		'sortnum' => '17',
		'issearch' => '',
		'searchField' => '',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'isallsearch' => '',
		'searchsortnum' => '',
		'status' => '1',
		'extention_html_end' => array(
			'0' => ' ',
		),
		'func' => array(
			'0' => array(
				'0' => 'getOperateStatus',
			),
			'1' => array(
				'0' => 'getStatusWithRel',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '#createid#',
					'1' => '#auditState#',
					'2' => 'id/#id#',
					'3' => '',
					'4' => '',
					'5' => 'dialog',
					'6' => '培训课程',
					'7' => '620',
					'8' => '400',
				),
			),
			'1' => array(
				'0' => array(
					'0' => '#status#',
					'1' => '#id#',
					'2' => '',
					'3' => '',
					'4' => 'mishrevaluationtrainmodel',
				),
			),
		),
	),
);

?>