<?php 
return array(
	'0' => array(
		'name' => 'id',
		'showname' => '编号',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'id',
		'sortnum' => '1',
		'issearch' => '',
		'searchField' => '',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'isallsearch' => '',
		'searchsortnum' => '',
	),
	'7' => array(
		'name' => 'content',
		'showname' => '操作SQL内容',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'content',
		'sortnum' => '2',
		'issearch' => '1',
		'func' => array(
			'0' => array(
				'0' => 'missubstr',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => '20',
					'2' => 'true',
				),
			),
		),
		'searchField' => 'mis_system_log.content',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '',
		'searchsortnum' => '2',
	),
	'1' => array(
		'name' => 'name',
		'showname' => '表名',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'name',
		'sortnum' => '3',
		'issearch' => '',
		'searchField' => 'mis_system_log.name',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '',
		'searchsortnum' => '3',
	),
	'2' => array(
		'name' => 'logtype',
		'showname' => '日志类型',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'logtype',
		'sortnum' => '4',
		'issearch' => '1',
		'searchField' => 'mis_system_log.logtype',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'select|SystemLogSelect',
		'isallsearch' => '',
		'searchsortnum' => '4',
	),
	'3' => array(
		'name' => 'createid',
		'showname' => '创建人ID',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'createid',
		'sortnum' => '5',
		'issearch' => '1',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'user',
				),
			),
		),
		'searchField' => 'mis_system_log.createid',
		'table' => 'user',
		'field' => 'id',
		'conditions' => '',
		'type' => 'db',
		'isallsearch' => '',
		'searchsortnum' => '5',
	),
	'4' => array(
		'name' => 'actionip',
		'showname' => '操作的IP地址',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'actionip',
		'sortnum' => '6',
		'issearch' => '',
		'searchField' => 'mis_system_log.actionip',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '',
		'searchsortnum' => '6',
	),
	'5' => array(
		'name' => 'createtime',
		'showname' => '创建时间',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'createtime',
		'sortnum' => '7',
		'issearch' => '',
		'func' => array(
			'0' => array(
				'0' => 'transTime',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
				),
			),
		),
		'searchField' => 'mis_system_log.create_time',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '',
		'searchsortnum' => '7',
	),
	'6' => array(
			'name' => 'companyid',
			'showname' => '公司',
			'shows' => '1',
			'widths' => '',
			'sorts' => '0',
			'models' => '',
			'sortname' => 'companyid',
			'sortnum' => '5',
			'issearch' => '1',
			'func' => array(
					'0' => array(
							'0' => 'getFieldBy',
					),
			),
			'funcdata' => array(
					'0' => array(
							'0' => array(
									'0' => '###',
									'1' => 'id',
									'2' => 'name',
									'3' => 'mis_system_company',
							),
					),
			),
			'searchField' => 'mis_system_log.companyid',
			'table' => 'user',
			'field' => 'id',
			'conditions' => '',
			'type' => 'db',
			'isallsearch' => '',
			'searchsortnum' => '5',
	),
	'7' => array(
			'name' => 'departmentid',
			'showname' => '部门',
			'shows' => '1',
			'widths' => '',
			'sorts' => '0',
			'models' => '',
			'sortname' => 'createid',
			'sortnum' => '5',
			'issearch' => '1',
			'func' => array(
					'0' => array(
							'0' => 'getFieldBy',
					),
			),
			'funcdata' => array(
					'0' => array(
							'0' => array(
									'0' => '###',
									'1' => 'id',
									'2' => 'name',
									'3' => 'mis_system_departmentid',
							),
					),
			),
			'searchField' => 'mis_system_log.departmentid',
			'table' => 'user',
			'field' => 'id',
			'conditions' => '',
			'type' => 'db',
			'isallsearch' => '',
			'searchsortnum' => '5',
	),		
);

?>