<?php 
return array(
	'name' => array(
		'name' => 'name',
		'showname' => '名称',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'name',
		'sortnum' => '2',
		'fieldtype' => 'tinyint',
		'fieldcategory' => 'text',
		'searchField' => 'mis_system_templete_manage.name',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '0',
		'helpvalue' => '',
	),
	'zhuangtai' => array(
		'name' => 'zhuangtai',
		'showname' => '状态',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'zhuangtai',
		'sortnum' => '3',
		'fieldtype' => 'tinyint',
		'fieldcategory' => 'select',
		'searchField' => 'mis_system_templete_manage.zhuangtai',
		'conditions' => '',
		'type' => 'db',
		'func' => array(
			'0' => array(
				'0' => 'getSelectlistValue',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'StartOrForbidden',
				),
			),
		),
		'issearch' => '1',
		'isallsearch' => '0',
		'searchsortnum' => '1',
		'helpvalue' => '',
	),
	'upload3' => array(
		'name' => 'upload3',
		'showname' => 'word上传',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'upload3',
		'sortnum' => '4',
		'fieldtype' => 'varchar',
		'fieldcategory' => 'upload',
		'searchField' => 'mis_system_templete_manage.upload3',
		'conditions' => '',
		'type' => 'upload',
		'ischosice' => '1',
		'helpvalue' => '',
	),
	'upload4' => array(
		'name' => 'upload4',
		'showname' => 'html上传',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'upload4',
		'sortnum' => '5',
		'fieldtype' => 'varchar',
		'fieldcategory' => 'upload',
		'searchField' => 'mis_system_templete_manage.upload4',
		'conditions' => '',
		'type' => 'upload',
		'ischosice' => '1',
		'helpvalue' => '',
	),
		'upload5' => array(
				'name' => 'upload5',
				'showname' => 'Excel上传',
				'shows' => '0',
				'widths' => '',
				'sorts' => '0',
				'models' => '',
				'sortname' => 'upload5',
				'sortnum' => '6',
				'fieldtype' => 'varchar',
				'fieldcategory' => 'upload',
				'searchField' => 'mis_system_templete_manage.upload5',
				'conditions' => '',
				'type' => 'upload',
				'ischosice' => '1',
				'helpvalue' => '',
		),
	'modelname' => array(
		'name' => 'modelname',
		'showname' => '模型名称',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'modelname',
		'sortnum' => '7',
		'fieldtype' => 'varchar',
		'fieldcategory' => 'hiddens',
		'searchField' => 'mis_system_templete_manage.modelname',
		'conditions' => '',
		'type' => 'text',
		'helpvalue' => '',
	),
	'orderno' => array(
		'name' => 'orderno',
		'showname' => '编号',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'orderno',
		'sortnum' => '1',
		'searchField' => 'mis_system_templete_manage.orderno',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '0',
		'helpvalue' => '',
	),
	'action' => array(
		'name' => 'action',
		'showname' => '操作',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'status',
		'func' => array(
			'0' => array(
				'0' => 'showStatus',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '#status#',
					'1' => '#id#',
				),
			),
		),
		'sortnum' => '8',
		'helpvalue' => '',
	),
);

?>