<?php 
return array(
	'name' => array(
		'name' => 'name',
		'showname' => '名称',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'name',
		'sortnum' => '1',
		'shows' => '1',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => '',
		'fieldcategory' => 'text',
		'searchField' => 'mis_auto_oyljp.name',
		'conditions' => '',
		'type' => 'text',
		'validate' => '',
		'unique' => '1',
		'required' => '0',
		'transform' => '0',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '0',
		'table' => '',
		'field' => '',
	),
	'id' => array(
		'name' => 'id',
		'showname' => 'ID',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'status' => '1',
		'sortname' => 'id',
		'sortnum' => '0',
		'searchField' => '',
		'conditions' => '',
		'type' => '',
		'issearch' => '0',
		'message' => '1',
		'isallsearch' => '0',
		'searchsortnum' => '0',
		'table' => '',
		'field' => '',
	),
	'danjutablechina' => array(
		'name' => 'danjutablechina',
		'showname' => '单据表单',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'danjutablechina',
		'sortnum' => '2',
		'shows' => '1',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'varchar',
		'fieldcategory' => 'text',
		'searchField' => 'mis_auto_oyljp.danjutablechina',
		'conditions' => '',
		'type' => 'text',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '0',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '1',
		'table' => '',
		'field' => '',
	),
	'danjumingchen' => array(
		'name' => 'danjumingchen',
		'showname' => '单据名称',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'danjumingchen',
		'sortnum' => '3',
		'shows' => '1',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'varchar',
		'fieldcategory' => 'text',
		'searchField' => 'mis_auto_oyljp.danjumingchen',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'name',
					'2' => 'title',
					'3' => 'node',
				),
			),
		),
		'conditions' => '',
		'type' => 'text',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '0',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '1',
		'table' => '',
		'field' => '',
	),
	'tixingtiaojian' => array(
		'name' => 'tixingtiaojian',
		'showname' => '提醒条件',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'tixingtiaojian',
		'sortnum' => '4',
		'shows' => '1',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'varchar',
		'fieldcategory' => 'text',
		'searchField' => 'mis_auto_oyljp.tixingtiaojian',
		'conditions' => '',
		'type' => 'text',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '0',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '2',
		'table' => '',
		'field' => '',
	),
	'tixingnarong' => array(
		'name' => 'tixingnarong',
		'showname' => '提醒内容',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'tixingnarong',
		'sortnum' => '5',
		'shows' => '1',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'varchar',
		'fieldcategory' => 'text',
		'searchField' => 'mis_auto_oyljp.tixingnarong',
		'conditions' => '',
		'type' => 'text',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '0',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '3',
		'table' => '',
		'field' => '',
	),

		'type' => array(
				'name' => 'type',
				'showname' => '类型',
				'widths' => '',
				'sorts' => '0',
				'models' => '',
				'sortname' => '类型',
				'sortnum' => '6',
				'shows' => '1',
				'status' => '1',
				'rules' => '1',
				'message' => '1',
				'isexport' => '1',
				'methods' => '',
				'relation' => '',
				'fieldtype' => 'varchar',
				'fieldcategory' => 'text',
				'searchField' => 'mis_auto_oyljp.type',
				'func' => array(
						'0' => array(
								'0' => 'excelTplselected',
						),
				),
				'funcdata' => array(
						'0' => array(
								'0' => array(
										'0' => '###',
										'1' => '1:单据提醒,2:定时任务',
								),
						),
				),
				'conditions' => '',
				'type' => 'text',
				'validate' => '',
				'unique' => '0',
				'required' => '0',
				'transform' => '0',
				'issearch' => '1',
				'isallsearch' => '1',
				'searchsortnum' => '3',
				'table' => '',
				'field' => '',
		),
	'action' => array(
		'name' => 'action',
		'showname' => '操作',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'status',
		'func' => array(
			'0' => array(
				'0' => 'showStatus',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '#status#',
					'1' => '#id#',
				),
			),
		),
		'sortnum' => '16',
		'transform' => '0',
		'unique' => '0',
		'validate' => '0',
		'required' => '0',
		'searchField' => '',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '0',
	),
);

?>