<?php 
return array(
	'0' => array(
		'name' => 'id',
		'showname' => '序号',
		'shows' => '1',
		'widths' => '33',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'id',
		'sortnum' => '1',
		'issearch' => '0',
		'searchField' => '',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'isallsearch' => '0',
		'searchsortnum' => '0',
		'status' => '1',
		'isexport' => '0',
	),
	'1' => array(
		'name' => 'orderno',
		'showname' => '编号',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'orderno',
		'sortnum' => '2',
		'issearch' => '1',
		'searchField' => 'mis_oa_archives_manage_mas.orderno',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '1',
		'searchsortnum' => '2',
		'status' => '1',
		'isexport' => '0',
	),
	'2' => array(
		'name' => 'fondsnum',
		'showname' => '全宗号',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'fondsnum',
		'sortnum' => '3',
		'issearch' => '1',
		'searchField' => 'mis_oa_archives_manage_mas.fondsnum',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '1',
		'searchsortnum' => '3',
		'status' => '1',
		'isexport' => '0',
	),
	'3' => array(
		'name' => 'typenum',
		'showname' => '类别',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'typenum',
		'sortnum' => '4',
		'issearch' => '1',
		'searchField' => 'mis_oa_archives_manage_mas.typenum',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '1',
		'searchsortnum' => '4',
		'status' => '1',
		'isexport' => '0',
	),
	'4' => array(
		'name' => 'catnum',
		'showname' => '目录号',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'catnum',
		'sortnum' => '5',
		'issearch' => '0',
		'searchField' => 'mis_oa_archives_manage_mas.catnum',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '5',
		'status' => '1',
		'isexport' => '0',
	),
	'5' => array(
		'name' => 'year',
		'showname' => '年度',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'year',
		'sortnum' => '6',
		'issearch' => '1',
		'searchField' => 'mis_oa_archives_manage_mas.year',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '1',
		'searchsortnum' => '6',
		'status' => '1',
		'isexport' => '0',
	),
	'6' => array(
		'name' => 'casenum',
		'showname' => '卷名',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'casenum',
		'sortnum' => '7',
		'issearch' => '1',
		'searchField' => 'mis_oa_archives_manage_mas.casenum',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '1',
		'searchsortnum' => '7',
		'status' => '1',
		'isexport' => '0',
	),
	'7' => array(
		'name' => 'retentionperiod',
		'showname' => '保管期限',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'retentionperiod',
		'sortnum' => '8',
		'issearch' => '1',
		'searchField' => 'mis_oa_archives_manage_mas.retentionperiod',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '1',
		'searchsortnum' => '8',
		'status' => '1',
		'isexport' => '0',
	),
	'8' => array(
		'name' => 'begindate',
		'showname' => '案件开始时间',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'func' => array(
			'0' => array(
				'0' => 'transTime',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
				),
			),
		),
		'sortname' => 'begindate',
		'sortnum' => '9',
		'issearch' => '1',
		'searchField' => 'mis_oa_archives_manage_mas.begindate',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '1',
		'searchsortnum' => '9',
		'status' => '1',
		'isexport' => '0',
	),
	'9' => array(
		'name' => 'enddate',
		'showname' => '案件结束时间',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'func' => array(
			'0' => array(
				'0' => 'transTime',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
				),
			),
		),
		'sortname' => 'enddate',
		'sortnum' => '10',
		'issearch' => '1',
		'searchField' => 'mis_oa_archives_manage_mas.enddate',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '1',
		'searchsortnum' => '10',
		'status' => '1',
		'isexport' => '0',
	),
	'10' => array(
		'name' => 'remark',
		'showname' => '备注',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'remark',
		'sortnum' => '11',
		'issearch' => '0',
		'searchField' => 'mis_oa_archives_manage_mas.remark',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '11',
		'status' => '-1',
		'isexport' => '0',
	),
	'11' => array(
		'name' => 'title',
		'showname' => '标题',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'id',
		'sortnum' => '12',
		'issearch' => '1',
		'searchField' => 'mis_oa_archives_manage_mas.id',
		'table' => 'mis_oa_archives_manage_sub',
		'field' => 'masid',
		'conditions' => '',
		'type' => 'db|title',
		'isallsearch' => '1',
		'searchsortnum' => '12',
		'status' => '1',
		'isexport' => '0',
	),
	'56' => array(
		'name' => 'status',
		'showname' => '状态',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'status',
		'func' => array(
			'0' => array(
				'0' => 'getStatus',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
				),
			),
		),
		'sortnum' => '57',
		'status' => '1',
		'isexport' => '0',
	),
);

?>