<?php 
return array(
	'id' => array(
		'name' => 'id',
		'showname' => 'ID',
		'shows' => '0',
		'widths' => '',
		'sorts' => '1',
		'models' => '',
		'sortname' => 'id',
		'sortnum' => '1',
		'issearch' => '0',
		'searchField' => '',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'isallsearch' => '0',
		'searchsortnum' => '0',
		'status' => '1',
		'rules' => '0',
		'isexport' => '0',
		'helpvalue' => '',
		'message' => '0',
	),
	'orderno' => array(
		'name' => 'orderno',
		'showname' => '员工编号',
		'shows' => '1',
		'widths' => '',
		'sorts' => '1',
		'models' => '',
		'sortname' => 'orderno',
		'sortnum' => '2',
		'issearch' => '1',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_person_info.orderno',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '1',
		'searchsortnum' => '1',
		'status' => '1',
		'rules' => '0',
		'helpvalue' => '',
		'message' => '0',
	),
	'itemid' => array(
		'name' => 'itemid',
		'showname' => '档案号',
		'shows' => '0',
		'widths' => '',
		'sorts' => '1',
		'models' => '',
		'sortname' => 'itemid',
		'sortnum' => '3',
		'issearch' => '1',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_person_info.itemid',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '1',
		'searchsortnum' => '2',
		'status' => '1',
		'rules' => '0',
		'helpvalue' => '',
		'message' => '0',
	),
	'name' => array(
		'name' => 'name',
		'showname' => '姓名',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'name',
		'sortnum' => '4',
		'issearch' => '1',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_person_info.name',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '1',
		'searchsortnum' => '3',
		'status' => '1',
		'rules' => '0',
		'helpvalue' => '',
		'message' => '0',
	),
	'education' => array(
		'name' => 'education',
		'showname' => '学历',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'education',
		'sortnum' => '5',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'mis_hr_typeinfo',
				),
			),
		),
		'issearch' => '1',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_person_info.education',
		'table' => 'mis_hr_typeinfo',
		'field' => 'id',
		'conditions' => 'typeid=2,pid=44',
		'type' => 'group',
		'isallsearch' => '0',
		'searchsortnum' => '4',
		'status' => '1',
		'rules' => '0',
		'helpvalue' => '',
		'message' => '0',
	),
	'sex' => array(
		'name' => 'sex',
		'showname' => '性别',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'sex',
		'sortnum' => '6',
		'func' => array(
			'0' => array(
				'0' => 'getS',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
				),
			),
		),
		'issearch' => '1',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_person_info.sex',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'radio|sex',
		'isallsearch' => '0',
		'searchsortnum' => '5',
		'status' => '1',
		'rules' => '0',
		'helpvalue' => '',
		'message' => '0',
	),
	'age' => array(
		'name' => 'age',
		'showname' => '年龄',
		'shows' => '0',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'age',
		'sortnum' => '7',
		'issearch' => '0',
		'searchField' => 'mis_hr_personnel_person_info.age',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'isallsearch' => '0',
		'searchsortnum' => '6',
		'status' => '1',
		'widths' => '',
		'func' => array(
			'0' => array(
				'0' => 'getAgeByToCarIdForList',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '#chinaid#',
					'1' => '',
				),
			),
		),
		'rules' => '0',
		'isexport' => '0',
		'helpvalue' => '',
		'message' => '0',
	),
	'deptid' => array(
		'name' => 'deptid',
		'showname' => '部门',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'deptid',
		'sortnum' => '8',
		'issearch' => '1',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_person_info.deptid',
		'table' => 'mis_system_department',
		'field' => 'id',
		'conditions' => '',
		'type' => 'db',
		'isallsearch' => '1',
		'searchsortnum' => '7',
		'status' => '1',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'mis_system_department',
				),
			),
		),
		'rules' => '0',
		'helpvalue' => '',
		'message' => '0',
	),
	'dutyid' => array(
		'name' => 'dutyid',
		'showname' => '职级',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'dutylevelid',
		'sortnum' => '10',
		'issearch' => '1',
		'isexport' => '1',
		'searchField' => 'dutyid',
		'table' => 'duty',
		'field' => 'id',
		'conditions' => '',
		'isallsearch' => '1',
		'searchsortnum' => '8',
		'status' => '1',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'mis_system_duty',
				),
			),
		),
		'type' => 'db',
		'rules' => '0',
		'helpvalue' => '',
		'message' => '0',
	),
	'worktype' => array(
		'name' => 'worktype',
		'showname' => '岗位',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'worktype',
		'sortnum' => '9',
		'issearch' => '1',
		'isexport' => '1',
		'searchField' => 'worktype',
		'table' => 'mis_hr_job_info',
		'field' => 'id',
		'conditions' => '',
		'type' => 'group',
		'isallsearch' => '1',
		'searchsortnum' => '9',
		'status' => '1',
		'rules' => '0',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'mis_hr_job_info',
				),
			),
		),
		'helpvalue' => '',
		'message' => '0',
	),
	'indate' => array(
		'name' => 'indate',
		'showname' => '入职时间',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'indate',
		'sortnum' => '11',
		'func' => array(
			'0' => array(
				'0' => 'transTime',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
				),
			),
		),
		'issearch' => '1',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_person_info.indate',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'time',
		'isallsearch' => '0',
		'searchsortnum' => '10',
		'status' => '1',
		'rules' => '0',
		'helpvalue' => '',
		'message' => '0',
	),
	'transferdate' => array(
		'name' => 'transferdate',
		'showname' => '转正时间',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'transferdate',
		'sortnum' => '12',
		'func' => array(
			'0' => array(
				'0' => 'transTime',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
				),
			),
		),
		'issearch' => '1',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_person_info.transferdate',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'time',
		'isallsearch' => '0',
		'searchsortnum' => '11',
		'status' => '1',
		'rules' => '0',
		'helpvalue' => '',
		'message' => '0',
	),
	'chinaid' => array(
		'name' => 'chinaid',
		'showname' => '身份证号',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'chinaid',
		'sortnum' => '13',
		'issearch' => '1',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_person_info.chinaid',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '1',
		'searchsortnum' => '12',
		'status' => '1',
		'rules' => '0',
		'helpvalue' => '',
		'message' => '0',
	),
	'remark' => array(
		'name' => 'remark',
		'showname' => '备注',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'chinaid',
		'sortnum' => '14',
		'issearch' => '0',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_person_info.remark',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '13',
		'status' => '1',
		'rules' => '0',
		'helpvalue' => '',
		'message' => '0',
	),
	'accounttype' => array(
		'name' => 'accounttype',
		'showname' => '户口性质',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'accounttype',
		'sortnum' => '15',
		'issearch' => '1',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_person_info.accounttype',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'select|accounttype',
		'isallsearch' => '0',
		'searchsortnum' => '14',
		'status' => '1',
		'rules' => '0',
		'func' => array(
			'0' => array(
				'0' => 'getSelectByName',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => 'accounttype',
					'1' => '###',
				),
			),
		),
		'helpvalue' => '',
		'message' => '0',
	),
	'agreetypeid' => array(
		'name' => 'agreetypeid',
		'showname' => '合约性质',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'agreetypeid',
		'sortnum' => '16',
		'issearch' => '1',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_person_info.agreetypeid',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'select|agreetypeid',
		'isallsearch' => '0',
		'searchsortnum' => '15',
		'status' => '1',
		'rules' => '0',
		'func' => array(
			'0' => array(
				'0' => 'getSelectByName',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => 'agreetypeid',
					'1' => '###',
				),
			),
		),
		'helpvalue' => '',
		'message' => '0',
	),
	'phone' => array(
		'name' => 'phone',
		'showname' => '联系电话',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'phone',
		'sortnum' => '17',
		'issearch' => '1',
		'searchField' => 'mis_hr_personnel_person_info.phone',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '1',
		'searchsortnum' => '16',
		'status' => '1',
		'rules' => '0',
		'isexport' => '1',
		'helpvalue' => '',
		'message' => '0',
	),
	'leavereason' => array(
		'name' => 'leavereason',
		'showname' => '操作',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'leavereason',
		'sortnum' => '18',
		'issearch' => '0',
		'isexport' => '1',
		'searchField' => 'mis_hr_leave_employee.leavereason',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '14',
		'status' => '1',
		'func' => array(
			'0' => array(
				'0' => 'showhtml',
			),
			'1' => array(
				'0' => 'showhtml',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '<a href="__URL__/edit/id/#id#" title="查看详情" rel="MisHrPersonnelManagement_view" target="dialog" mask="true" height="500" width="800"><span style="color:red">  查看   </span></a>',
				),
			),
			'1' => array(
				'0' => array(
					'0' => '<a href="__URL__/editgeneral/id/#id#" title="员工档案" rel="MisHrPersonnelManagement_editgeneral" target="navTab" mask="true"  ><span style="color:red">修改</span></a>',
					'1' => 'mishrpersonnelmanagement_editgeneral',
				),
			),
		),
		'rules' => '0',
		'helpvalue' => '',
		'message' => '0',
	),
	'employeeStatus' => array(
		'name' => 'employeeStatus',
		'showname' => '员工状态',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'employeeStatus',
		'sortnum' => '19',
		'issearch' => '1',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_person_info.employeeStatus',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'select|employeeStatus',
		'isallsearch' => '1',
		'searchsortnum' => '2',
		'status' => '1',
		'rules' => '0',
		'func' => array(
			'0' => array(
				'0' => 'getSelectByName',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => 'employeeStatus',
					'1' => '###',
				),
			),
		),
		'helpvalue' => '',
		'message' => '0',
	),
	'workage' => array(
		'name' => 'workage',
		'showname' => '工龄',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'workage',
		'sortnum' => '20',
		'issearch' => '0',
		'isexport' => '0',
		'searchField' => 'mis_hr_personnel_person_info.workage',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'isallsearch' => '0',
		'searchsortnum' => '2',
		'status' => '1',
		'rules' => '0',
		'helpvalue' => '',
		'message' => '0',
	),
);

?>