<?php 
return array(
	'0' => array(
		'name' => 'pos',
		'showname' => '排序',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'pos',
		'sortnum' => '1',
		'searchField' => 'mis_typeform_field.pos',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '1',
		'table' => '',
		'field' => '',
		'status' => '1',
		'isexport' => '1',
		'rules' => '0',
		'message' => '0',
		'helpvalue' => '',
	),
	'1' => array(
		'name' => 'name',
		'showname' => '字段名',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'name',
		'sortnum' => '2',
		'searchField' => 'mis_typeform_field.name',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '2',
		'table' => '',
		'field' => '',
		'status' => '1',
		'isexport' => '1',
		'rules' => '0',
		'message' => '0',
		'helpvalue' => '',
	),
	'4' => array(
		'name' => 'fieldtypeid',
		'showname' => '类型',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'fieldtypeid',
		'sortnum' => '3',
		'searchField' => 'mis_typeform_field.fieldtypeid',
		'conditions' => '',
		'type' => 'group',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '3',
		'table' => 'mis_typeform_field_type',
		'field' => 'id',
		'status' => '1',
		'isexport' => '1',
		'rules' => '0',
		'message' => '0',
		'helpvalue' => '',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'mis_typeform_field_type',
				),
			),
		),
	),
	'3' => array(
		'name' => 'ismust',
		'showname' => '是否必须',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'ismust',
		'sortnum' => '4',
		'searchField' => 'mis_typeform_field.ismust',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '4',
		'table' => '',
		'field' => '',
		'status' => '1',
		'isexport' => '1',
		'rules' => '0',
		'message' => '0',
		'helpvalue' => '',
	),
	'5' => array(
		'name' => 'action',
		'showname' => '状态',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'status',
		'func' => array(
			'0' => array(
				'0' => 'getStatus',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '#status#',
				),
			),
		),
		'sortnum' => '5',
		'searchField' => '',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '0',
		'status' => '1',
		'rules' => '0',
		'message' => '0',
		'helpvalue' => '',
	),
	'6' => array(
		'name' => 'remark',
		'showname' => '备注',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'remark',
		'sortnum' => '6',
		'issearch' => '1',
		'searchField' => 'mis_typeform_field.remark',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '1',
		'searchsortnum' => '5',
		'status' => '1',
		'helpvalue' => '',
		'rules' => '0',
		'message' => '0',
		'isexport' => '1',
	),
);

?>