<?php 
return array(
		'0' => array(
				'name' => 'name',
				'showname' => '年限',
				'shows' => '1',
				'widths' => '',
				'sorts' => '0',
				'models' => '',
				'sortname' => 'name',
				'sortnum' => '1',
				'issearch' => '1',
				'searchField' => 'mis_manage_status.name',
				'table' => '',
				'field' => '',
				'conditions' => '',
				'type' => 'text',
				'isallsearch' => '0',
				'searchsortnum' => '0',
				'status' => '1',
				'helpvalue' => '',
		),
		'1' => array(
				'name' => 'sellprice',
				'showname' => '销售收入',
				'shows' => '0',
				'widths' => '',
				'sorts' => '0',
				'models' => '',
				'sortname' => 'sellprice',
				'func' => array(
						'0' => array(
								'0' => 'getDigits',
						),
				),
				'funcdata' => array(
						'0' => array(
								'0' => array(
										'0' => '###',
								),
						),
				),
				'sortnum' => '2',
				'issearch' => '1',
				'searchField' => 'mis_manage_status.sellprice',
				'table' => '',
				'field' => '',
				'conditions' => '',
				'type' => 'text',
				'isallsearch' => '1',
				'searchsortnum' => '1',
				'status' => '1',
				'helpvalue' => '',
		),
		'2' => array(
				'name' => 'ratepaying',
				'showname' => '纳税总额',
				'shows' => '1',
				'widths' => '',
				'sorts' => '0',
				'models' => '',
				'sortname' => 'ratepaying',
				'func' => array(
						'0' => array(
								'0' => 'getDigits',
						),
				),
				'funcdata' => array(
						'0' => array(
								'0' => array(
										'0' => '###',
								),
						),
				),
				'sortnum' => '3',
				'issearch' => '1',
				'searchField' => 'mis_manage_status.ratepaying',
				'table' => '',
				'field' => '',
				'conditions' => '',
				'type' => 'text',
				'isallsearch' => '1',
				'searchsortnum' => '2',
				'status' => '1',
				'helpvalue' => '',
		),
		'20' => array(
				'name' => 'profit',
				'showname' => '纯利润',
				'shows' => '1',
				'widths' => '',
				'sorts' => '0',
				'models' => '',
				'sortname' => 'profit',
				'func' => array(
						'0' => array(
								'0' => 'getDigits',
						),
				),
				'funcdata' => array(
						'0' => array(
								'0' => array(
										'0' => '###',
								),
						),
				),
				'sortnum' => '4',
				'issearch' => '1',
				'searchField' => 'mis_manage_status.profit',
				'table' => '',
				'field' => '',
				'conditions' => '',
				'type' => 'text',
				'isallsearch' => '0',
				'searchsortnum' => '2',
				'status' => '1',
				'helpvalue' => '',
		),
		'12' => array(
				'name' => 'qyproperty',
				'showname' => '企业总资产',
				'shows' => '1',
				'widths' => '',
				'sorts' => '0',
				'models' => '',
				'sortname' => 'qyproperty',
				'func' => array(
						'0' => array(
								'0' => 'getDigits',
						),
				),
				'funcdata' => array(
						'0' => array(
								'0' => array(
										'0' => '###',
								),
						),
				),
				'sortnum' => '5',
				'issearch' => '1',
				'searchField' => 'mis_manage_status.qyproperty',
				'table' => '',
				'field' => '',
				'conditions' => '',
				'type' => 'text',
				'isallsearch' => '0',
				'searchsortnum' => '0',
				'status' => '1',
				'helpvalue' => '',
		),
		'3' => array(
				'name' => 'inventory',
				'showname' => '存货总额',
				'shows' => '1',
				'widths' => '',
				'sorts' => '0',
				'models' => '',
				'sortname' => 'inventory',
				'func' => array(
						'0' => array(
								'0' => 'getDigits',
						),
				),
				'funcdata' => array(
						'0' => array(
								'0' => array(
										'0' => '###',
								),
						),
				),
				'sortnum' => '6',
				'issearch' => '1',
				'searchField' => 'mis_manage_status.inventory',
				'table' => '',
				'field' => '',
				'conditions' => '',
				'type' => 'text',
				'isallsearch' => '0',
				'searchsortnum' => '3',
				'status' => '1',
				'helpvalue' => '',
		),
		'22' => array(
				'name' => 'facilityprice',
				'showname' => '设备总价值',
				'shows' => '1',
				'widths' => '',
				'sorts' => '0',
				'models' => '',
				'sortname' => 'facilityprice',
				'func' => array(
						'0' => array(
								'0' => 'getDigits',
						),
				),
				'funcdata' => array(
						'0' => array(
								'0' => array(
										'0' => '###',
								),
						),
				),
				'sortnum' => '7',
				'issearch' => '1',
				'searchField' => 'mis_manage_status.facilityprice',
				'table' => '',
				'field' => '',
				'conditions' => '',
				'type' => 'text',
				'isallsearch' => '0',
				'searchsortnum' => '0',
				'status' => '1',
				'helpvalue' => '',
		),
		'4' => array(
				'name' => 'paymentday',
				'showname' => '应收账款平均账期',
				'shows' => '1',
				'widths' => '',
				'sorts' => '0',
				'models' => '',
				'sortname' => 'paymentday',
				'sortnum' => '8',
				'issearch' => '1',
				'searchField' => 'mis_manage_status.paymentday',
				'table' => '',
				'field' => '',
				'conditions' => '',
				'type' => 'text',
				'isallsearch' => '1',
				'searchsortnum' => '4',
				'status' => '1',
				'helpvalue' => '',
		),
		'8' => array(
				'name' => 'balance',
				'showname' => '应收账款余额',
				'shows' => '0',
				'widths' => '',
				'sorts' => '0',
				'models' => '',
				'sortname' => 'balance',
				'func' => array(
						'0' => array(
								'0' => 'getDigits',
						),
				),
				'funcdata' => array(
						'0' => array(
								'0' => array(
										'0' => '###',
								),
						),
				),
				'sortnum' => '9',
				'issearch' => '1',
				'searchField' => 'mis_manage_status.balance',
				'table' => '',
				'field' => '',
				'conditions' => '',
				'type' => 'text',
				'isallsearch' => '0',
				'searchsortnum' => '0',
				'status' => '1',
				'helpvalue' => '',
		),
		'5' => array(
				'name' => 'liabilitiescase',
				'showname' => '企业负债情况',
				'shows' => '1',
				'widths' => '',
				'sorts' => '0',
				'models' => '',
				'sortname' => 'liabilitiescase',
				'sortnum' => '10',
				'issearch' => '1',
				'searchField' => 'mis_manage_status.liabilitiescase',
				'table' => '',
				'field' => '',
				'conditions' => '',
				'type' => 'text',
				'isallsearch' => '0',
				'searchsortnum' => '0',
				'status' => '1',
				'helpvalue' => '',
		),
		'16' => array(
				'name' => 'propertycase',
				'showname' => '企业资产情况',
				'shows' => '1',
				'widths' => '',
				'sorts' => '0',
				'models' => '',
				'sortname' => 'propertycase',
				'sortnum' => '11',
				'issearch' => '1',
				'searchField' => 'mis_manage_status.propertycase',
				'table' => '',
				'field' => '',
				'conditions' => '',
				'type' => 'text',
				'isallsearch' => '0',
				'searchsortnum' => '0',
				'status' => '1',
				'helpvalue' => '',
		),
		'17' => array(
				'name' => 'servicecase',
				'showname' => '企业服务跟踪情况',
				'shows' => '1',
				'widths' => '',
				'sorts' => '0',
				'models' => '',
				'sortname' => 'servicecase',
				'sortnum' => '12',
				'issearch' => '1',
				'searchField' => 'mis_manage_status.servicecase',
				'table' => '',
				'field' => '',
				'conditions' => '',
				'type' => 'text',
				'isallsearch' => '0',
				'searchsortnum' => '0',
				'status' => '1',
				'helpvalue' => '',
		),
		'18' => array(
				'name' => 'organization',
				'showname' => '最终服务机构',
				'shows' => '1',
				'widths' => '',
				'sorts' => '0',
				'models' => '',
				'sortname' => 'organization',
				'sortnum' => '13',
				'issearch' => '0',
				'searchField' => 'mis_manage_status.organization',
				'table' => '',
				'field' => '',
				'conditions' => '',
				'type' => 'text',
				'isallsearch' => '0',
				'searchsortnum' => '0',
				'status' => '1',
				'helpvalue' => '',
		),
		'9' => array(
				'name' => 'loan',
				'showname' => '放款额度',
				'shows' => '0',
				'widths' => '',
				'sorts' => '0',
				'models' => '',
				'sortname' => 'loan',
				'sortnum' => '14',
				'issearch' => '0',
				'searchField' => 'mis_manage_status.loan',
				'table' => '',
				'field' => '',
				'conditions' => '',
				'type' => 'text',
				'isallsearch' => '0',
				'searchsortnum' => '0',
				'status' => '1',
				'helpvalue' => '',
		),
		'14' => array(
				'name' => 'loandate',
				'showname' => '放货日期',
				'shows' => '0',
				'widths' => '',
				'sorts' => '0',
				'models' => '',
				'sortname' => 'loandate',
				'sortnum' => '15',
				'issearch' => '0',
				'searchField' => 'mis_manage_status.loandate',
				'table' => '',
				'field' => '',
				'conditions' => '',
				'type' => 'text',
				'isallsearch' => '0',
				'searchsortnum' => '0',
				'status' => '1',
				'helpvalue' => '',
		),
		'10' => array(
				'name' => 'action',
				'showname' => '状态',
				'shows' => '1',
				'widths' => '',
				'sorts' => '0',
				'models' => '',
				'sortname' => 'status',
				'sortnum' => '18',
				'issearch' => '0',
				'searchField' => '',
				'table' => '',
				'field' => '',
				'conditions' => '',
				'type' => '',
				'isallsearch' => '0',
				'searchsortnum' => '0',
				'status' => '1',
				'func' => array(
						'0' => array(
								'0' => 'getStatus',
						)
				),
				'funcdata' => array(
						'0' => array(
								'0' => array(
										'0' => '#status#',
								),
						),
				),
				'helpvalue' => '',
		),
);

?>