<?php 
return array(
	'5' => array(
		'name' => 'name',
		'showname' => '视图英文名称',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'name',
		'sortnum' => '1',
		'searchField' => 'mis_system_dataview_mas.name',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '0',
		'helpvalue' => '',
		'status' => '1',
		'rules' => '0',
		'message' => '0',
		'table' => '',
		'field' => '',
	),
	'0' => array(
		'name' => 'modelname',
		'showname' => '模型名称',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'modelname',
		'sortnum' => '2',
		'searchField' => 'mis_system_dataview_mas.modelname',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '0',
		'helpvalue' => '',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'name',
					'2' => 'title',
					'3' => 'node',
				),
			),
		),
		'status' => '1',
		'rules' => '0',
		'message' => '0',
		'table' => '',
		'field' => '',
	),
	'1' => array(
		'name' => 'title',
		'showname' => '视图中文名',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'title',
		'sortnum' => '3',
		'searchField' => 'mis_system_dataview_mas.title',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '1',
		'helpvalue' => '',
		'status' => '1',
		'rules' => '0',
		'message' => '0',
		'table' => '',
		'field' => '',
	),
	'2' => array(
		'name' => 'datatable2',
		'showname' => '内嵌数据表格_2',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'datatable2',
		'sortnum' => '4',
		'searchField' => 'mis_system_dataview_mas0.datatable2',
		'conditions' => '',
		'type' => 'datatable',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '2',
		'ischosice' => '1',
		'helpvalue' => '',
		'status' => '1',
		'rules' => '0',
		'message' => '0',
		'table' => '',
		'field' => '',
	),
	'3' => array(
		'name' => 'orderno',
		'showname' => '编号',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'orderno',
		'sortnum' => '5',
		'searchField' => 'mis_system_dataview_mas.orderno',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '0',
		'helpvalue' => '',
		'status' => '1',
		'rules' => '0',
		'message' => '0',
		'table' => '',
		'field' => '',
	),
	'4' => array(
		'name' => 'action',
		'showname' => '操作',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'status',
		'func' => array(
			'0' => array(
				'0' => 'showStatus',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '#status#',
					'1' => '#id#',
				),
			),
		),
		'sortnum' => '6',
		'helpvalue' => '',
		'status' => '1',
		'rules' => '0',
		'message' => '0',
		'searchField' => '',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '0',
	),
	'6' => array(
		'name' => 'spellsql',
		'showname' => 'sql语句',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'spellsql',
		'sortnum' => '7',
		'searchField' => 'mis_system_dataview_mas.spellsql',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '0',
		'helpvalue' => '',
		'status' => '1',
		'rules' => '0',
		'message' => '0',
		'table' => '',
		'field' => '',
	),
);

?>