<?php 
return array(
	'0' => array(
		'name' => 'id',
		'showname' => '编号',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'id',
		'sortnum' => '0',
		'issearch' => '',
		'searchField' => '',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'isallsearch' => '',
		'searchsortnum' => '',
	),
	'1' => array(
		'name' => 'employe_id',
		'showname' => '员工姓名',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'employe_id',
		'sortnum' => '1',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'mis_hr_personnel_person_info',
				),
			),
		),
		'issearch' => '1',
		'searchField' => 'mis_hr_part_organization.employe_id',
		'table' => 'mis_hr_personnel_person_info',
		'field' => 'id',
		'conditions' => '',
		'type' => 'db',
		'isallsearch' => '1',
		'searchsortnum' => '1',
	),
	'2' => array(
		'name' => 'apply_time',
		'showname' => '入党时间',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'apply_time',
		'sortnum' => '2',
		'func' => array(
			'0' => array(
				'0' => 'transTime',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
				),
			),
		),
		'issearch' => '1',
		'searchField' => 'mis_hr_part_organization.apply_time',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'time',
		'isallsearch' => '',
		'searchsortnum' => '2',
	),
	'3' => array(
		'name' => 'approve_time',
		'showname' => '转正时间',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'approve_time',
		'sortnum' => '3',
		'func' => array(
			'0' => array(
				'0' => 'transTime',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
				),
			),
		),
		'issearch' => '1',
		'searchField' => 'mis_hr_part_organization.approve_time',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'time',
		'isallsearch' => '',
		'searchsortnum' => '3',
	),
	'4' => array(
		'name' => 'organization_ship',
		'showname' => '组织关系',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'organization_ship',
		'sortnum' => '4',
		'func' => array(
			'0' => array(
				'0' => 'excelTplselected',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => '1:正式,2:预备',
				),
			),
		),
		'issearch' => '1',
		'searchField' => 'mis_hr_part_organization.organization_ship',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'select|dyxxorganization',
		'isallsearch' => '',
		'searchsortnum' => '4',
	),
	'5' => array(
		'name' => 'organization_owner',
		'showname' => '组织关系隶属',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'organization_owner',
		'sortnum' => '5',
		'issearch' => '1',
		'searchField' => 'mis_hr_part_organization.organization_owner',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '1',
		'searchsortnum' => '5',
	),
	'6' => array(
		'name' => 'member',
		'showname' => '委员',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'member',
		'sortnum' => '6',
		'func' => array(
			'0' => array(
				'0' => 'excelTplselected',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => '1:是,2:后选,3:否',
				),
			),
		),
		'issearch' => '1',
		'searchField' => 'mis_hr_part_organization.member',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'select|dyxxadministration',
		'isallsearch' => '',
		'searchsortnum' => '6',
	),
	'7' => array(
		'name' => 'lnner_position',
		'showname' => '党内职务',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'lnner_position',
		'sortnum' => '7',
		'issearch' => '',
		'searchField' => 'mis_hr_part_organization.lnner_position',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '',
		'searchsortnum' => '7',
	),
	'8' => array(
		'name' => 'administration_position',
		'showname' => '行政职务',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'administration_position',
		'sortnum' => '8',
		'issearch' => '1',
		'searchField' => 'mis_hr_part_organization.administration_position',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '1',
		'searchsortnum' => '8',
	),
	'9' => array(
		'name' => 'ln_time',
		'showname' => '流入时间',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'ln_time',
		'sortnum' => '9',
		'func' => array(
			'0' => array(
				'0' => 'transTime',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
				),
			),
		),
		'issearch' => '1',
		'searchField' => 'mis_hr_part_organization.ln_time',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'time',
		'isallsearch' => '',
		'searchsortnum' => '9',
	),
	'10' => array(
		'name' => 'out_time',
		'showname' => '流出时间',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'out_time',
		'sortnum' => '10',
		'func' => array(
			'0' => array(
				'0' => 'transTime',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
				),
			),
		),
		'issearch' => '1',
		'searchField' => 'mis_hr_part_organization.out_time',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'time',
		'isallsearch' => '',
		'searchsortnum' => '10',
	),
	'11' => array(
		'name' => 'accessory_file',
		'showname' => '证明材料',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'accessory_file',
		'sortnum' => '11',
		'issearch' => '',
		'searchField' => 'mis_hr_part_organization.accessory_file',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '',
		'searchsortnum' => '11',
	),
	'12' => array(
		'name' => 'info',
		'showname' => '个人简介',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'info',
		'sortnum' => '12',
		'issearch' => '',
		'searchField' => 'mis_hr_part_organization.info',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '',
		'searchsortnum' => '12',
	),
	'13' => array(
		'name' => 'remark',
		'showname' => '备注',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'remark',
		'sortnum' => '13',
		'issearch' => '',
		'searchField' => 'mis_hr_part_organization.remark',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '',
		'searchsortnum' => '13',
	),
	'15' => array(
		'name' => 'sex',
		'showname' => '性别',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'sex',
		'sortnum' => '15',
		'func' => array(
			'0' => array(
				'0' => 'getS',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
				),
			),
		),
		'issearch' => '',
		'isexport' => '1',
		'searchField' => 'mis_hr_part_organization.sex',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '',
		'searchsortnum' => '15',
	),
	'16' => array(
		'name' => 'birthday',
		'showname' => '出生日期',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'birthday',
		'sortnum' => '16',
		'issearch' => '',
		'isexport' => '1',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
				'1' => 'transTime',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '#employe_id#',
					'1' => 'id',
					'2' => 'birthday',
					'3' => 'mis_hr_personnel_person_info',
				),
				'1' => array(
					'0' => '###',
				),
			),
		),
		'searchField' => 'mis_hr_part_organization.birthday',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '',
		'searchsortnum' => '16',
	),
	'18' => array(
		'name' => 'education',
		'showname' => '学历',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'education',
		'sortnum' => '18',
		'issearch' => '',
		'isexport' => '1',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '#employe_id#',
					'1' => 'id',
					'2' => 'education',
					'3' => 'mis_hr_personnel_person_info',
				),
			),
		),
		'searchField' => 'mis_hr_part_organization.education',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '',
		'searchsortnum' => '18',
	),
	'19' => array(
		'name' => 'nativeaddress',
		'showname' => '户籍地址',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'nativeaddress',
		'sortnum' => '19',
		'issearch' => '',
		'isexport' => '1',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '#employe_id#',
					'1' => 'id',
					'2' => 'nativeaddress',
					'3' => 'mis_hr_personnel_person_info',
				),
			),
		),
		'searchField' => 'mis_hr_part_organization.nativeaddress',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '',
		'searchsortnum' => '19',
	),
	'20' => array(
		'name' => 'chinaid',
		'showname' => '身份证',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'chinaid',
		'sortnum' => '20',
		'issearch' => '',
		'isexport' => '1',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '#employe_id#',
					'1' => 'id',
					'2' => 'chinaid',
					'3' => 'mis_hr_personnel_person_info',
				),
			),
		),
		'searchField' => 'mis_hr_part_organization.chinaid',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '',
		'searchsortnum' => '20',
	),
	'21' => array(
		'name' => 'companyid',
		'showname' => '公司名',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'companyid',
		'sortnum' => '21',
		'issearch' => '',
		'isexport' => '1',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '#employe_id#',
					'1' => 'id',
					'2' => 'companyid',
					'3' => 'mis_hr_personnel_person_info',
				),
			),
		),
		'searchField' => 'mis_hr_part_organization.companyid',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '',
		'searchsortnum' => '21',
	),
	'22' => array(
		'name' => 'phone',
		'showname' => '联系电话',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'phone',
		'sortnum' => '22',
		'issearch' => '',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '#employe_id#',
					'1' => 'id',
					'2' => 'phone',
					'3' => 'mis_hr_personnel_person_info',
				),
			),
		),
		'searchField' => 'mis_hr_part_organization.phone',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '',
		'searchsortnum' => '22',
	),
	'23' => array(
		'name' => 'national',
		'showname' => '民族',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'national',
		'sortnum' => '23',
		'issearch' => '',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '#employe_id#',
					'1' => 'id',
					'2' => 'national',
					'3' => 'mis_hr_personnel_person_info',
				),
			),
		),
		'searchField' => '',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'isallsearch' => '',
		'searchsortnum' => '',
	),
	'24' => array(
		'name' => 'work_time',
		'showname' => '工作时间',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'work_time',
		'sortnum' => '24',
		'issearch' => '',
		'func' => array(
			'0' => array(
				'0' => 'transTime',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
				),
			),
		),
		'searchField' => '',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'isallsearch' => '',
		'searchsortnum' => '',
	),
	'25' => array(
		'name' => 'type',
		'showname' => '类型',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'type',
		'sortnum' => '25',
		'issearch' => '',
		'searchField' => '',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'isallsearch' => '',
		'searchsortnum' => '',
	),
	'26' => array(
			'name' => 'action',
			'showname' => '操作',
			'shows' => '1',
			'widths' => '',
			'sorts' => '0',
			'models' => '',
			'sortname' => 'status',
			'sortnum' => '26',
			'issearch' => '',
			'searchField' => '',
			'table' => '',
			'field' => '',
			'conditions' => '',
			'type' => '',
			'isallsearch' => '',
			'searchsortnum' => '',
			'status' => '1',
			'extention_html_end' => array(
					'0' => ' ',
			),
			'func' => array(
					'0' => array(
							'0' => 'getOperateStatus',
					),
					'1' => array(
							'0' => 'getStatus',
					),
			),
			'funcdata' => array(
					'0' => array(
							'0' => array(
									'0' => '#createid#',
									'1' => '#auditState#',
									'2' => 'id/#id#',
									'3' => '',
									'4' => '',
									'5' => 'navTab',
									'6' => '党员信息',
							),
					),
					'1' => array(
							'0' => array(
									'0' => '#status#',
							),
					),
			),
	),
	
);

?>