<?php 
return array(
	'0' => array(
		'name' => 'id',
		'showname' => 'ID',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'id',
		'sortnum' => '1',
		'searchField' => '',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'issearch' => '',
		'isallsearch' => '',
		'searchsortnum' => '',
		'helpvalue' => '',
		'rules' => '0',
	),
	'1' => array(
		'name' => 'orderno',
		'showname' => '申请编号',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'orderno',
		'sortnum' => '2',
		'searchField' => 'mis_hr_personnel_applicationinfo.orderno',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '2',
		'helpvalue' => '',
		'rules' => '0',
	),
	'11' => array(
		'name' => 'dutylevelid',
		'showname' => '申请职级',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'dutylevelid',
		'sortnum' => '3',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'duty',
				),
			),
		),
		'searchField' => 'mis_hr_personnel_applicationinfo.dutylevelid',
		'processSelectField' => array(
			'left' => array(
				'0' => 'id',
				'1' => 'level',
				'2' => 'duty',
			),
			'right' => array(
				'0' => 'level',
				'1' => 'name',
				'2' => 'duty',
			),
		),
		'table' => 'duty',
		'field' => 'id',
		'conditions' => '',
		'type' => 'db|name',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '12',
		'helpvalue' => '',
		'rules' => '1',
	),
	'2' => array(
		'name' => 'deptid',
		'showname' => '申请部门',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'deptid',
		'sortnum' => '3',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'mis_system_department',
				),
			),
		),
		'searchField' => 'mis_hr_personnel_applicationinfo.deptid',
		'table' => 'mis_system_department',
		'field' => 'id',
		'conditions' => '',
		'type' => 'db|name',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '3',
		'helpvalue' => '',
		'rules' => '0',
	),
	'3' => array(
		'name' => 'sumpeople',
		'showname' => '共增补人数',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'sumpeople',
		'sortnum' => '4',
		'searchField' => 'mis_hr_personnel_applicationinfo.sumpeople',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '',
		'isallsearch' => '',
		'searchsortnum' => '4',
		'helpvalue' => '',
		'rules' => '1',
	),
	'4' => array(
		'name' => 'deptpeople',
		'showname' => '部门现有人数',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'deptpeople',
		'sortnum' => '5',
		'searchField' => 'mis_hr_personnel_applicationinfo.deptpeople',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '',
		'isallsearch' => '',
		'searchsortnum' => '5',
		'helpvalue' => '',
		'rules' => '0',
	),
	'5' => array(
		'name' => 'formationpeople',
		'showname' => '部门编制人数',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'formationpeople',
		'sortnum' => '6',
		'searchField' => 'mis_hr_personnel_applicationinfo.formationpeople',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '',
		'isallsearch' => '',
		'searchsortnum' => '6',
		'helpvalue' => '',
		'rules' => '0',
	),
	'6' => array(
		'name' => 'applicationdate',
		'showname' => '申请日期',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'applicationdate',
		'sortnum' => '7',
		'func' => array(
			'0' => array(
				'0' => 'transTime',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
				),
			),
		),
		'searchField' => 'mis_hr_personnel_applicationinfo.applicationdate',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'time',
		'issearch' => '0',
		'isallsearch' => '',
		'searchsortnum' => '7',
		'helpvalue' => '',
		'rules' => '0',
	),
	'7' => array(
		'name' => 'toworkdate',
		'showname' => '到职日期',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'toworkdate',
		'sortnum' => '8',
		'func' => array(
			'0' => array(
				'0' => 'transTime',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
				),
			),
		),
		'searchField' => 'mis_hr_personnel_applicationinfo.toworkdate',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'time',
		'issearch' => '1',
		'isallsearch' => '',
		'searchsortnum' => '8',
		'helpvalue' => '',
		'rules' => '0',
	),
	'8' => array(
		'name' => 'applicationtype',
		'showname' => '申请类型',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'applicationtype',
		'sortnum' => '9',
		'searchField' => 'mis_hr_personnel_applicationinfo.applicationtype',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'select|applicationtype',
		'issearch' => '1',
		'isallsearch' => '',
		'searchsortnum' => '9',
		'helpvalue' => '',
		'rules' => '0',
	),
	'9' => array(
		'name' => 'auditState',
		'showname' => '审核状态',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'auditState',
		'func' => array(
			'0' => array(
				'0' => 'getAuditState',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => '#id#',
					'2' => '#ptmptid#',
				),
			),
		),
		'sortnum' => '10',
		'searchField' => 'mis_hr_personnel_applicationinfo.auditState',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '',
		'isallsearch' => '',
		'searchsortnum' => '10',
		'helpvalue' => '',
		'rules' => '0',
	),
	'10' => array(
		'name' => 'action',
		'showname' => '操作',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'status',
		'sortnum' => '11',
		'issearch' => '',
		'searchField' => '',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'isallsearch' => '',
		'searchsortnum' => '',
		'status' => '1',
		'extention_html_end' => array(
			'0' => ' ',
		),
		'func' => array(
			'0' => array(
				'0' => 'getStatus',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '#status#',
				),
			),
		),
		'helpvalue' => '',
		'rules' => '0',
	),
);

?>