<?php 
return array(
	'0' => array(
		'name' => 'id',
		'showname' => 'ID',
		'shows' => '0',
		'widths' => '',
		'sorts' => '1',
		'models' => '',
		'sortname' => 'id',
		'sortnum' => '1',
		'issearch' => '0',
		'searchField' => '',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'isallsearch' => '0',
		'searchsortnum' => '0',
		'status' => '1',
		'helpvalue' => '',
		'rules' => '0',
		'message' => '0',
	),
	'2' => array(
		'name' => 'title',
		'showname' => '报告标题',
		'shows' => '1',
		'widths' => '',
		'sorts' => '1',
		'models' => '',
		'sortname' => 'title',
		'sortnum' => '2',
		'issearch' => '1',
		'searchField' => 'mis_work_statement.title',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '1',
		'searchsortnum' => '3',
		'status' => '1',
		'helpvalue' => '',
		'rules' => '0',
		'message' => '0',
	),
	'3' => array(
		'name' => 'typeid',
		'showname' => '报告类型',
		'shows' => '1',
		'widths' => '',
		'sorts' => '1',
		'models' => '',
		'sortname' => 'typeid',
		'sortnum' => '3',
		'issearch' => '1',
		'searchField' => 'mis_work_statement.typeid',
		'table' => 'mis_order_types',
		'field' => 'id',
		'conditions' => '',
		'type' => 'db',
		'isallsearch' => '0',
		'searchsortnum' => '4',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'mis_order_types',
				),
			),
		),
		'status' => '1',
		'helpvalue' => '',
		'rules' => '0',
		'message' => '0',
	),
	'4' => array(
		'name' => 'userid',
		'showname' => '查阅人',
		'shows' => '1',
		'widths' => '180',
		'sorts' => '1',
		'models' => '',
		'sortname' => 'userid',
		'sortnum' => '4',
		'issearch' => '1',
		'searchField' => 'mis_work_read_statement.userid',
		'table' => 'user',
		'field' => 'id',
		'conditions' => '',
		'type' => 'db',
		'isallsearch' => '1',
		'searchsortnum' => '5',
		'status' => '1',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'User',
				),
			),
		),
		'helpvalue' => '',
		'rules' => '0',
		'message' => '0',
	),
	'6' => array(
		'name' => 'content',
		'showname' => '汇报内容',
		'shows' => '1',
		'widths' => '',
		'sorts' => '1',
		'models' => '',
		'sortname' => 'content',
		'sortnum' => '5',
		'issearch' => '0',
		'searchField' => 'mis_work_statement.content',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '7',
		'status' => '1',
		'helpvalue' => '',
		'rules' => '0',
		'message' => '0',
	),
	'7' => array(
		'name' => 'createid',
		'showname' => '报告人',
		'shows' => '1',
		'widths' => '',
		'sorts' => '1',
		'models' => '',
		'sortname' => 'createid',
		'sortnum' => '6',
		'issearch' => '1',
		'isearch' => '0',
		'searchField' => 'mis_work_statement.createid',
		'type' => 'db',
		'isallsearch' => '1',
		'searchsortnum' => '8',
		'status' => '1',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'User',
				),
			),
		),
		'table' => 'user',
		'field' => 'id',
		'conditions' => '',
		'helpvalue' => '',
		'rules' => '0',
		'message' => '0',
	),
	'8' => array(
		'name' => 'createtime',
		'showname' => '报告时间',
		'shows' => '1',
		'widths' => '',
		'sorts' => '1',
		'models' => '',
		'sortname' => 'createtime',
		'sortnum' => '7',
		'issearch' => '1',
		'isearch' => '0',
		'searchField' => 'mis_work_statement.createtime',
		'type' => 'time',
		'isallsearch' => '1',
		'searchsortnum' => '9',
		'func' => array(
			'0' => array(
				'0' => 'transTime',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
				),
			),
		),
		'status' => '1',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'helpvalue' => '',
		'rules' => '0',
		'message' => '0',
	),
	'11' => array(
		'name' => 'iscomment',
		'showname' => '评论状态',
		'shows' => '1',
		'widths' => '',
		'sorts' => '1',
		'models' => '',
		'sortname' => 'iscomment',
		'sortnum' => '8',
		'issearch' => '0',
		'isearch' => '0',
		'searchField' => 'mis_work_read_statement.iscomment',
		'type' => 'text',
		'func' => array(
			'0' => array(
				'0' => 'excelTplselected',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => '1:<span class="green">已评</span>,0:<span class="blue">未评</span>',
				),
			),
		),
		'isallsearch' => '0',
		'searchsortnum' => '10',
		'status' => '1',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'helpvalue' => '',
		'rules' => '0',
		'message' => '0',
	),
	'9' => array(
		'name' => 'action',
		'showname' => '操作',
		'shows' => '1',
		'widths' => '',
		'sorts' => '1',
		'models' => '',
		'sortname' => 'status',
		'sortnum' => '9',
		'issearch' => '0',
		'searchField' => '',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'isallsearch' => '0',
		'searchsortnum' => '0',
		'status' => '1',
		'func' => array(
			'1' => array(
				'0' => 'getStatus',
			),
		),
		'funcdata' => array(
			'1' => array(
				'0' => array(
					'0' => '#status#',
				),
			),
		),
		'helpvalue' => '',
		'rules' => '0',
		'message' => '0',
	),
);

?>