<?php 
return array(
	'0' => array(
		'name' => 'orderno',
		'showname' => '编号',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'orderno',
		'sortnum' => '1',
		'searchField' => 'mis_system_project_templete.orderno',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '1',
		'table' => '',
		'field' => '',
		'status' => '1',
		'rules' => '0',
		'message' => '0',
		'isexport' => '1',
		'helpvalue' => '',
	),
	'1' => array(
		'name' => 'name',
		'showname' => '名称',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'name',
		'sortnum' => '2',
		'searchField' => 'mis_system_project_templete.name',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '2',
		'table' => '',
		'field' => '',
		'status' => '1',
		'rules' => '0',
		'message' => '0',
		'isexport' => '1',
		'helpvalue' => '',
	),
	'2' => array(
		'name' => 'category',
		'showname' => '业务阶段',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'category',
		'sortnum' => '3',
		'searchField' => 'mis_system_project_templete.category',
		'conditions' => '',
		'type' => 'db|name',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '3',
		'table' => 'mis_system_flow_type',
		'field' => 'id',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'mis_system_flow_type',
				),
			),
		),
		'status' => '1',
		'rules' => '0',
		'message' => '0',
		'isexport' => '1',
		'helpvalue' => '',
	),
	'3' => array(
		'name' => 'supcategory',
		'showname' => '业务类型',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'supcategory',
		'sortnum' => '4',
		'searchField' => 'mis_system_project_templete.supcategory',
		'conditions' => '',
		'type' => 'db|name',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '4',
		'table' => 'mis_system_flow_type',
		'field' => 'id',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'mis_system_flow_type',
				),
			),
		),
		'status' => '1',
		'rules' => '0',
		'message' => '0',
		'isexport' => '1',
		'helpvalue' => '',
	),
	'zhuangtai' => array(
			'name' => 'zhuangtai',
			'showname' => '状态',
			'shows' => '1',
			'widths' => '',
			'sorts' => '0',
			'models' => '',
			'sortname' => 'zhuangtai',
			'sortnum' => '11',
			'fieldtype' => 'tinyint',
			'fieldcategory' => 'select',
			'searchField' => 'mis_system_templete_manage.zhuangtai',
			'conditions' => '',
			'type' => 'db',
			'func' => array(
					'0' => array(
							'0' => 'getSelectlistValue',
					),
			),
			'funcdata' => array(
					'0' => array(
							'0' => array(
									'0' => '###',
									'1' => 'StartOrForbidden',
							),
					),
			),
			'issearch' => '1',
			'isallsearch' => '0',
			'searchsortnum' => '11',
			'helpvalue' => '',
	),
	'upload3' => array(
			'name' => 'upload3',
			'showname' => 'word上传',
			'shows' => '0',
			'widths' => '',
			'sorts' => '0',
			'models' => '',
			'sortname' => 'upload3',
			'sortnum' => '12',
			'fieldtype' => 'varchar',
			'fieldcategory' => 'upload',
			'searchField' => 'mis_system_templete_manage.upload3',
			'conditions' => '',
			'type' => 'upload',
			'ischosice' => '1',
			'helpvalue' => '',
	),
	'upload4' => array(
			'name' => 'upload4',
			'showname' => 'html上传',
			'shows' => '0',
			'widths' => '',
			'sorts' => '0',
			'models' => '',
			'sortname' => 'upload4',
			'sortnum' => '13',
			'fieldtype' => 'varchar',
			'fieldcategory' => 'upload',
			'searchField' => 'mis_system_templete_manage.upload4',
			'conditions' => '',
			'type' => 'upload',
			'ischosice' => '1',
			'helpvalue' => '',
	),
	'upload5' => array(
			'name' => 'upload5',
			'showname' => 'Excel上传',
			'shows' => '0',
			'widths' => '',
			'sorts' => '0',
			'models' => '',
			'sortname' => 'upload5',
			'sortnum' => '14',
			'fieldtype' => 'varchar',
			'fieldcategory' => 'upload',
			'searchField' => 'mis_system_templete_manage.upload5',
			'conditions' => '',
			'type' => 'upload',
			'ischosice' => '1',
			'helpvalue' => '',
	),
	'6' => array(
		'name' => 'notes',
		'showname' => '备注',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'notes',
		'sortnum' => '9',
		'searchField' => 'mis_system_project_templete.notes',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '1',
		'isallsearch' => '0',
		'searchsortnum' => '7',
		'table' => '',
		'field' => '',
		'status' => '1',
		'rules' => '0',
		'message' => '0',
		'isexport' => '1',
		'helpvalue' => '',
		'func' => array(
			'0' => array(
				'0' => 'missubstr',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => '30',
					'2' => 'true',
				),
			),
		),
	),
	'7' => array(
		'name' => 'action',
		'showname' => '操作',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'status',
		'func' => array(
			'0' => array(
				'0' => 'getStatus',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '#status#',
				),
			),
		),
		'sortnum' => '10',
		'searchField' => '',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '0',
		'status' => '1',
		'rules' => '0',
		'message' => '0',
		'helpvalue' => '',
	),
	'8' => array(
		'name' => 'custtypeid',
		'showname' => '客户主体',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'custtypeid',
		'sortnum' => '6',
		'searchField' => 'mis_system_project_templete.custtypeid',
		'conditions' => '',
		'type' => 'db|orderno',
		'issearch' => '1',
		'isallsearch' => '0',
		'searchsortnum' => '9',
		'table' => 'mis_sale_client_type',
		'field' => 'id',
		'helpvalue' => '',
		'status' => '1',
		'rules' => '0',
		'message' => '0',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'mis_sale_client_type',
				),
			),
		),
	),
	'9' => array(
		'name' => 'hyid',
		'showname' => '行业',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'hyid',
		'sortnum' => '7',
		'searchField' => 'mis_system_project_templete.hyid',
		'conditions' => '',
		'type' => 'db|orderno',
		'issearch' => '1',
		'isallsearch' => '0',
		'searchsortnum' => '10',
		'table' => 'mis_sale_profession',
		'field' => 'id',
		'helpvalue' => '',
		'status' => '1',
		'rules' => '0',
		'message' => '0',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'mis_sale_profession',
				),
			),
		),
	),
	'10' => array(
		'name' => 'cylid',
		'showname' => '产业链',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'cylid',
		'sortnum' => '8',
		'searchField' => 'mis_system_project_templete.cylid',
		'conditions' => '',
		'type' => 'db|orderno',
		'issearch' => '1',
		'isallsearch' => '0',
		'searchsortnum' => '11',
		'table' => 'mis_sale_industry',
		'field' => 'id',
		'helpvalue' => '',
		'status' => '1',
		'rules' => '0',
		'message' => '0',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'mis_sale_industry',
				),
			),
		),
	),
	'11' => array(
			'name' => 'xiangmuleixing',
			'showname' => '项目类型',
			'shows' => '1',
			'widths' => '',
			'sorts' => '0',
			'models' => '',
			'sortname' => 'xiangmuleixing',
			'sortnum' => '12',
			'searchField' => 'mis_system_project_templete.xiangmuleixing',
			'conditions' => '',
			'type' => 'db|name',
			'issearch' => '1',
			'isallsearch' => '1',
			'searchsortnum' => '4',
			'table' => 'mis_auto_ocqwl',
			'field' => 'id',
			'func' => array(
					'0' => array(
							'0' => 'getFieldBy',
					),
			),
			'funcdata' => array(
					'0' => array(
							'0' => array(
									'0' => '###',
									'1' => 'orderno',
									'2' => 'name',
									'3' => 'mis_auto_ocqwl',
							),
					),
			),
			'status' => '1',
			'rules' => '0',
			'message' => '0',
			'isexport' => '1',
			'helpvalue' => '',
	),
);

?>