<?php 
return array(
	'0' => array(
		'name' => 'id',
		'showname' => 'ID',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'id',
		'sortnum' => '1',
		'searchField' => '',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'issearch' => '',
		'isallsearch' => '',
		'searchsortnum' => '',
	),
	'1' => array(
		'name' => 'title',
		'showname' => '标题',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'title',
		'sortnum' => '2',
		'searchField' => 'system_announcement.title',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '2',
	),
	'2' => array(
		'name' => 'content',
		'showname' => '内容',
		'shows' => '0',
		'widths' => '200',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'content',
		'sortnum' => '3',
		'searchField' => 'system_announcement.content',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '3',
	),
	'3' => array(
		'name' => 'url',
		'showname' => '链接URL',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'url',
		'sortnum' => '4',
		'searchField' => 'system_announcement.url',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '4',
	),
	/* '4' => array(
		'name' => 'userid',
		'showname' => '操作员',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'userid',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'user',
				),
			),
		),
		'sortnum' => '5',
		'searchField' => 'system_announcement.userid',
		'table' => 'user',
		'field' => 'id',
		'conditions' => '',
		'type' => 'db',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '5',
	), */
	'5' => array(
		'name' => 'remark',
		'showname' => '备注',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'remark',
		'sortnum' => '6',
		'searchField' => 'system_announcement.remark',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '',
		'isallsearch' => '',
		'searchsortnum' => '6',
	),
	'14' => array(
		'name' => 'status',
		'showname' => '状态',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'status',
		'func' => array(
			'0' => array(
				'0' => 'getStatus',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
				),
			),
		),
		'sortnum' => '15',
		'searchField' => '',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'issearch' => '',
		'isallsearch' => '',
		'searchsortnum' => '',
	),
		'11' => array(
				'name' => 'createtime',
				'showname' => '创建时间',
				'shows' => '1',
				'widths' => '',
				'sorts' => '0',
				'models' => '',
				'sortname' => 'createtime',
				'sortnum' => '12',
				'func' => array(
						'0' => array(
								'0' => 'transTime',
						),
				),
				'funcdata' => array(
						'0' => array(
								'0' => array(
										'0' => '###',
								),
						),
				),
				'issearch' => '0',
				'searchField' => 'system_announcement.createtime',
				'table' => '',
				'field' => '',
				'conditions' => '',
				'type' => 'text',
				'isallsearch' => '0',
				'searchsortnum' => '12',
				'status' => '1',
				'rules' => '0',
				'isexport' => '0',
		),
		'10' => array(
				'name' => 'createid',
				'showname' => '创建人',
				'shows' => '1',
				'widths' => '',
				'sorts' => '0',
				'models' => '',
				'sortname' => 'createid',
				'sortnum' => '11',
				'func' => array(
						'0' => array(
								'0' => 'getFieldBy',
						),
				),
				'funcdata' => array(
						'0' => array(
								'0' => array(
										'0' => '###',
										'1' => 'id',
										'2' => 'name',
										'3' => 'user',
								),
						),
				),
				'issearch' => '0',
				'searchField' => 'system_announcement.createid',
				'table' => '',
				'field' => '',
				'conditions' => '',
				'type' => 'text',
				'isallsearch' => '0',
				'searchsortnum' => '11',
				'status' => '1',
				'rules' => '0',
				'isexport' => '0',
		),
	'13' => array(
		'name' => 'action',
		'showname' => '操作',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'status',
		'func' => array(
			'0' => array(
				'0' => 'showStatus',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '#status#',
					'1' => '#id#',
				),
			),
		),
		'sortnum' => '14',
		'searchField' => '',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'issearch' => '',
		'isallsearch' => '',
		'searchsortnum' => '',
	),
);

?>