<?php 
return array(
	'0' => array(
		'name' => 'id',
		'showname' => 'ID',
		'shows' => '0',
		'widths' => '22',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'id',
		'sortnum' => '1',
		'issearch' => '0',
		'searchField' => '',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'isallsearch' => '0',
		'searchsortnum' => '0',
		'status' => '1',
		'rules' => '0',
		'message' => '0',
		'helpvalue' => '',
	),
	'1' => array(
		'name' => 'code',
		'showname' => '编号',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'code',
		'sortnum' => '2',
		'issearch' => '0',
		'searchField' => 'mis_work_statement.code',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '2',
		'status' => '1',
		'rules' => '0',
		'message' => '0',
		'helpvalue' => '',
	),
	'2' => array(
		'name' => 'title',
		'showname' => '报告标题',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'title',
		'sortnum' => '3',
		'issearch' => '1',
		'searchField' => 'mis_work_statement.title',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '1',
		'searchsortnum' => '3',
		'status' => '1',
		'rules' => '0',
		'message' => '0',
		'helpvalue' => '',
	),
	'3' => array(
		'name' => 'summary',
		'showname' => '摘要',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'summary',
		'sortnum' => '4',
		'issearch' => '1',
		'searchField' => 'mis_work_statement.summary',
		'func' => array(
			'0' => array(
				'0' => 'missubstr',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => '50',
					'2' => true,
				),
			),
		),
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '1',
		'searchsortnum' => '4',
		'status' => '1',
		'rules' => '0',
		'message' => '0',
		'helpvalue' => '',
	),
	'4' => array(
		'name' => 'typeid',
		'showname' => '报告类型',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'typeid',
		'sortnum' => '5',
		'issearch' => '1',
		'searchField' => 'mis_work_statement.typeid',
		'table' => 'mis_order_types',
		'field' => 'id',
		'conditions' => '',
		'type' => 'db',
		'isallsearch' => '1',
		'searchsortnum' => '5',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'mis_order_types',
				),
			),
		),
		'status' => '1',
		'rules' => '0',
		'message' => '0',
		'helpvalue' => '',
	),
	'5' => array(
		'name' => 'lookpeoplename',
		'showname' => '查阅人',
		'shows' => '0',
		'widths' => '180',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'lookpeoplename',
		'sortnum' => '6',
		'issearch' => '1',
		'searchField' => 'mis_work_statement.lookpeoplename',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '1',
		'searchsortnum' => '6',
		'status' => '1',
		'rules' => '0',
		'message' => '0',
		'helpvalue' => '',
	),
	'6' => array(
		'name' => 'copytopeoplename',
		'showname' => '抄送人',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'copytopeoplename',
		'sortnum' => '7',
		'issearch' => '0',
		'searchField' => 'mis_work_statement.copytopeoplename',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '7',
		'status' => '1',
		'rules' => '0',
		'message' => '0',
		'helpvalue' => '',
	),
	'7' => array(
		'name' => 'content',
		'showname' => '汇报内容',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'content',
		'sortnum' => '8',
		'issearch' => '0',
		'searchField' => 'mis_work_statement.content',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '8',
		'status' => '1',
		'rules' => '0',
		'message' => '0',
		'helpvalue' => '',
	),
	'8' => array(
		'name' => 'createid',
		'showname' => '报告人',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'createid',
		'sortnum' => '9',
		'issearch' => '1',
		'isearch' => '0',
		'searchField' => 'mis_work_statement.createid',
		'type' => 'db',
		'isallsearch' => '1',
		'searchsortnum' => '9',
		'status' => '1',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'User',
				),
			),
		),
		'table' => 'user',
		'field' => 'id',
		'conditions' => '',
		'rules' => '0',
		'message' => '0',
		'helpvalue' => '',
	),
	'9' => array(
		'name' => 'createtime',
		'showname' => '报告时间',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'createtime',
		'sortnum' => '10',
		'issearch' => '1',
		'isearch' => '0',
		'searchField' => 'mis_work_statement.createtime',
		'type' => 'time',
		'isallsearch' => '1',
		'searchsortnum' => '10',
		'func' => array(
			'0' => array(
				'0' => 'transTime',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
				),
			),
		),
		'status' => '1',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'rules' => '0',
		'message' => '0',
		'helpvalue' => '',
	),
	'10' => array(
		'name' => 'readstatus',
		'showname' => '阅读状态',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'readstatus',
		'sortnum' => '11',
		'issearch' => '1',
		'isearch' => '0',
		'searchField' => 'mis_work_statement.readstatus',
		'type' => 'select|statementreadstatus',
		'isallsearch' => '1',
		'searchsortnum' => '11',
		'status' => '1',
		'func' => array(
			'0' => array(
				'0' => 'excelTplselected',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => '1:<span class="green">已读</span>,0:<span class="blue">未读</span>',
				),
			),
		),
		'table' => '',
		'field' => '',
		'conditions' => '',
		'rules' => '0',
		'message' => '0',
		'helpvalue' => '',
	),
	'11' => array(
		'name' => 'commentstatus',
		'showname' => '评论状态',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'commentstatus',
		'sortnum' => '12',
		'issearch' => '0',
		'isearch' => '0',
		'searchField' => 'mis_work_statement.commentstatus',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '12',
		'status' => '1',
		'func' => array(
			'0' => array(
				'0' => 'getCommentStatus',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '#id#',
					'1' => 'workid',
					'2' => 'MisWorkReadStatement',
					'3' => 'commentuserid',
					'4' => '1:<span class="green">已评</span>,0:<span class="blue">未评</span>',
				),
			),
		),
		'table' => '',
		'field' => '',
		'conditions' => '',
		'rules' => '0',
		'message' => '0',
		'helpvalue' => '',
	),
	'12' => array(
		'name' => 'action',
		'showname' => '操作',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'status',
		'sortnum' => '13',
		'issearch' => '0',
		'searchField' => '',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'isallsearch' => '0',
		'searchsortnum' => '0',
		'status' => '1',
		'extention_html_end' => array(
			'0' => ' ',
		),
		'func' => array(
			'0' => array(
				'0' => 'getOperateStatus',
			),
			'1' => array(
				'0' => 'getStatus',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '#createid#',
					'1' => '#auditState#',
					'2' => 'id/#id#',
					'3' => '#md#',
					'4' => '',
					'5' => 'navTab',
					'6' => '工作报告',
				),
			),
			'1' => array(
				'0' => array(
					'0' => '#status#',
				),
			),
		),
		'rules' => '0',
		'message' => '0',
		'helpvalue' => '',
	),
);

?>