<?php 
return array(
	'10' => array(
		'name' => 'orderno',
		'showname' => '申请编号',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'orderno',
		'sortnum' => '1',
		'searchField' => 'mis_hr_egress_register.orderno',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '2',
		'helpvalue' => '',
		'rules' => '0',
	),
	'0' => array(
		'name' => 'hrname',
		'showname' => '姓名',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'hrname',
		'sortnum' => '2',
		'searchField' => 'mis_hr_egress_register.hrname',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '0',
		'table' => '',
		'field' => '',
		'helpvalue' => '',
	),
	'1' => array(
		'name' => 'deptname',
		'showname' => '所属部门',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'deptname',
		'sortnum' => '3',
		'searchField' => 'mis_hr_egress_register.deptname',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '0',
		'table' => '',
		'field' => '',
		'helpvalue' => '',
	),
	'2' => array(
		'name' => 'starttime',
		'showname' => '外出起始时间',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'starttime',
		'sortnum' => '4',
		'searchField' => 'mis_hr_egress_register.starttime',
		'conditions' => '',
		'type' => 'time',
		'issearch' => '1',
		'isallsearch' => '0',
		'searchsortnum' => '0',
		'func' => array(
			'0' => array(
				'0' => 'transtime',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
				),
			),
		),
		'table' => '',
		'field' => '',
		'helpvalue' => '',
	),
	'3' => array(
		'name' => 'endtime',
		'showname' => '外出结束时间',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'endtime',
		'sortnum' => '5',
		'searchField' => 'mis_hr_egress_register.endtime',
		'conditions' => '',
		'type' => 'time',
		'issearch' => '1',
		'isallsearch' => '0',
		'searchsortnum' => '0',
		'func' => array(
			'0' => array(
				'0' => 'transtime',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
				),
			),
		),
		'table' => '',
		'field' => '',
		'helpvalue' => '',
	),
	'4' => array(
		'name' => 'returntime',
		'showname' => '回岗时间',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'returntime',
		'sortnum' => '6',
		'searchField' => 'mis_hr_egress_register.returntime',
		'conditions' => '',
		'type' => 'time',
		'issearch' => '1',
		'isallsearch' => '0',
		'searchsortnum' => '0',
		'func' => array(
			'0' => array(
				'0' => 'transtime',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
				),
			),
		),
		'table' => '',
		'field' => '',
		'helpvalue' => '',
	),
	'5' => array(
		'name' => 'result',
		'showname' => '外出事由',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'result',
		'sortnum' => '7',
		'searchField' => 'mis_hr_egress_register.result',
		'conditions' => '',
		'type' => 'textarea',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '0',
		'table' => '',
		'field' => '',
		'helpvalue' => '',
	),
	'6' => array(
		'name' => 'remark',
		'showname' => '备注',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'remark',
		'sortnum' => '8',
		'searchField' => 'mis_hr_egress_register.remark',
		'conditions' => '',
		'type' => 'textarea',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '0',
		'table' => '',
		'field' => '',
		'helpvalue' => '',
	),
	'7' => array(
		'name' => 'text10',
		'showname' => '申请人',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'text10',
		'sortnum' => '9',
		'searchField' => 'mis_hr_egress_register.text10',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '0',
		'table' => '',
		'field' => '',
		'helpvalue' => '',
	),
	'8' => array(
		'name' => 'text11',
		'showname' => '申请时间',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'text11',
		'sortnum' => '10',
		'searchField' => 'mis_hr_egress_register.text11',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '0',
		'table' => '',
		'field' => '',
		'helpvalue' => '',
	),
	'9' => array(
		'name' => 'auditState',
		'showname' => '审核状态',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'auditState',
		'func' => array(
			'0' => array(
				'0' => 'getAuditState',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => '#id#',
					'2' => '#ptmptid#',
				),
			),
		),
		'sortnum' => '11',
		'searchField' => 'mis_hr_egress_register.auditState',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '1',
		'isallsearch' => '0',
		'searchsortnum' => '0',
		'helpvalue' => '',
	),
);

?>