<?php 
return array(
	'0' => array(
		'name' => 'id',
		'showname' => '编号',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'id',
		'sortnum' => '1',
		'searchField' => '',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'issearch' => '',
		'isallsearch' => '',
		'searchsortnum' => '',
	),
	'1' => array(
		'name' => 'fdate',
		'showname' => '凭证日期',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'fdate',
		'sortnum' => '1',
		'func' => array(
			'0' => array(
				'0' => 'transTime',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
				),
			),
		),
		'searchField' => 'mis_finance_voucher_mas.fdate',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'time',
		'issearch' => '1',
		'isallsearch' => '',
		'searchsortnum' => '1',
	),
	'2' => array(
		'name' => 'fyear',
		'showname' => '会计年度',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'fyear',
		'sortnum' => '2',
		'searchField' => 'mis_finance_voucher_mas.fyear',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '2',
	),
	'3' => array(
		'name' => 'fperiod',
		'showname' => '会计期间',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'fperiod',
		'sortnum' => '3',
		'searchField' => 'mis_finance_voucher_mas.fperiod',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '3',
	),
	'4' => array(
		'name' => 'ftype',
		'showname' => '凭证字号',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'ftype',
		'sortnum' => '4',
		'func' => array(
			'0' => array(
				'0' => 'showhtml',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '#ftype#-#con_link#',
				),
			),
		),
		'searchField' => 'mis_finance_voucher_mas.ftype',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '1',
		'isallsearch' => '',
		'searchsortnum' => '4',
	),
	'6' => array(
		'name' => 'fnum',
		'showname' => '分录号',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'fnum',
		'sortnum' => '6',
		'searchField' => 'mis_finance_voucher_mas.fnum',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '',
		'isallsearch' => '',
		'searchsortnum' => '6',
	),
	'7' => array(
		'name' => 'faccountnum',
		'showname' => '科目代码',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'faccountnum',
		'sortnum' => '7',
		'searchField' => 'mis_finance_voucher_mas.faccountnum',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '1',
		'isallsearch' => '',
		'searchsortnum' => '7',
	),
	'8' => array(
		'name' => 'faccountname',
		'showname' => '科目名称',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'faccountname',
		'sortnum' => '8',
		'searchField' => 'mis_finance_voucher_mas.faccountname',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '1',
		'isallsearch' => '',
		'searchsortnum' => '8',
	),
	'9' => array(
		'name' => 'currencycode',
		'showname' => '币种代码',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'currencycode',
		'sortnum' => '9',
		'searchField' => 'mis_finance_voucher_mas.currencycode',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '9',
	),
	'10' => array(
		'name' => 'currencyname',
		'showname' => '币种名称',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'currencyname',
		'sortnum' => '10',
		'searchField' => 'mis_finance_voucher_mas.currencyname',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '10',
	),
	'11' => array(
		'name' => 'famount',
		'showname' => '原币金额',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'famount',
		'sortnum' => '11',
		'searchField' => 'mis_finance_voucher_mas.famount',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '',
		'isallsearch' => '',
		'searchsortnum' => '11',
	),
	'12' => array(
		'name' => 'fdebit',
		'showname' => '借方',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'fdebit',
		'sortnum' => '12',
		'searchField' => 'mis_finance_voucher_mas.fdebit',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '',
		'isallsearch' => '',
		'searchsortnum' => '12',
	),
	'13' => array(
		'name' => 'fcredit',
		'showname' => '贷方',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'fcredit',
		'sortnum' => '13',
		'searchField' => 'mis_finance_voucher_mas.fcredit',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '',
		'isallsearch' => '',
		'searchsortnum' => '13',
	),
	'15' => array(
		'name' => 'action',
		'showname' => '操作',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'status',
		'sortnum' => '15',
		'issearch' => '',
		'searchField' => '',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'isallsearch' => '',
		'searchsortnum' => '',
		'status' => '1',
		'extention_html_end' => array(
			'0' => ' ',
		),
		'func' => array(
			'0' => array(
				'0' => 'getOperateStatus',
			),
			'1' => array(
				'0' => 'getStatus',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '#createid#',
					'1' => '#auditState#',
					'2' => 'id/#id#',
					'3' => '',
					'4' => '',
					'5' => 'navTab',
					'6' => '凭证-分类账', 
				),
			),
			'1' => array(
				'0' => array(
					'0' => '#status#',
				),
			),
		),
	),
	'14' => array(
		'name' => 'fsummary',
		'showname' => '摘要',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'fsummary',
		'sortnum' => '14',
		'searchField' => 'mis_finance_voucher_mas.fsummary',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '',
		'isallsearch' => '',
		'searchsortnum' => '16',
	),
);

?>