<?php
return array(
		'0' => array(
				'name' => 'id',
				'showname' => 'ID',
				'shows' => '0',
				'widths' => '',
				'sorts' => '0',
				'models' => '',
				'sortname' => 'id',
				'sortnum' => '1',
				'findtype' => 'text',
				'findtable' => 'crm_cust_advanced_info',
				'findfield' => 'cust_advanced_info_count',
				'searchField' => '',
				'table' => '',
				'field' => '',
				'conditions' => '',
				'type' => '',
				'issearch' => '0',
				'isallsearch' => '0',
				'searchsortnum' => '0',
				'status' => '1',
		),
		'1' => array(
				'name' => 'code',
				'showname' => '编码',
				'shows' => '1',
				'widths' => '',
				'sorts' => '0',
				'models' => '',
				'sortname' => 'code',
				'sortnum' => '1',
				'searchField' => 'mis_expert_type.code',
				'table' => '',
				'field' => '',
				'conditions' => '',
				'type' => 'text',
				'issearch' => '1',
				'isallsearch' => '1',
				'searchsortnum' => '0',
				'status' => '1',
		),
		'2' => array(
				'name' => 'name',
				'showname' => '名称',
				'shows' => '1',
				'widths' => '',
				'sorts' => '0',
				'models' => '',
				'sortname' => 'name',
				'sortnum' => '2',
				'searchField' => 'mis_expert_type.name',
				'table' => '',
				'field' => '',
				'conditions' => '',
				'type' => 'text',
				'issearch' => '1',
				'isallsearch' => '1',
				'searchsortnum' => '0',
				'status' => '1',
		),
		'3' => array(
				'name' => 'createid',
				'showname' => '创建人',
				'shows' => '0',
				'widths' => '',
				'sorts' => '0',
				'models' => '',
				'sortname' => 'createid',
				'sortnum' => '3',
				'searchField' => 'mis_expert_type.createid',
				'table' => '',
				'field' => '',
				'conditions' => '',
				'type' => 'text',
				'issearch' => '0',
				'isallsearch' => '0',
				'searchsortnum' => '0',
				'status' => '1',
		),
		'4' => array(
				'name' => 'createtime',
				'showname' => '创建时间',
				'shows' => '0',
				'widths' => '',
				'sorts' => '0',
				'models' => '',
				'sortname' => 'createtime',
				'sortnum' => '4',
				'func' => array(
						'0' => array(
								'0' => 'transTime',
						),
				),
				'funcdata' => array(
						'0' => array(
								'0' => array(
										'0' => '###',
								),
						),
				),
				'searchField' => 'mis_expert_type.createtime',
				'table' => '',
				'field' => '',
				'conditions' => '',
				'type' => 'text',
				'issearch' => '0',
				'isallsearch' => '0',
				'searchsortnum' => '0',
				'status' => '1',
		),
		'5' => array(
				'name' => 'updateid',
				'showname' => '更新人',
				'shows' => '0',
				'widths' => '',
				'sorts' => '0',
				'models' => '',
				'sortname' => 'updateid',
				'sortnum' => '5',
				'searchField' => 'mis_expert_type.updateid',
				'table' => '',
				'field' => '',
				'conditions' => '',
				'type' => 'text',
				'issearch' => '0',
				'isallsearch' => '0',
				'searchsortnum' => '0',
				'status' => '1',
		),
		'6' => array(
				'name' => 'updatetime',
				'showname' => '更新时间',
				'shows' => '0',
				'widths' => '',
				'sorts' => '0',
				'models' => '',
				'sortname' => 'updatetime',
				'sortnum' => '6',
				'func' => array(
						'0' => array(
								'0' => 'date',
						),
				),
				'funcdata' => array(
						'0' => array(
								'0' => array(
										'0' => 'Y-m-d',
										'1' => '###',
								),
						),
				),
				'searchField' => 'mis_expert_type.updatetime',
				'table' => '',
				'field' => '',
				'conditions' => '',
				'type' => 'text',
				'issearch' => '0',
				'isallsearch' => '0',
				'searchsortnum' => '0',
				'status' => '1',
		),
// 		'7' => array(
// 				'name' => 'action',
// 				'showname' => '操作',
// 				'shows' => '1',
// 				'widths' => '',
// 				'sorts' => '0',
// 				'models' => '',
// 				'sortname' => 'status',
// 				'sortnum' => '8',
// 				'issearch' => '',
// 				'searchField' => '',
// 				'table' => '',
// 				'field' => '',
// 				'conditions' => '',
// 				'type' => '',
// 				'isallsearch' => '',
// 				'searchsortnum' => '',
// 				'status' => '1',
// 				'extention_html_end' => array(
// 						'0' => ' ',
// 				),
// 				'func' => array(
// 						'0' => array(
// 								'0' => 'getOperateStatus',
// 						),
// 						'1' => array(
// 								'0' => 'getStatus',
// 						),
// 				),
// 				'funcdata' => array(
// 						'0' => array(
// 								'0' => array(
// 										'0' => '#createid#',
// 										'1' => '#auditState#',
// 										'2' => 'id/#id#',
// 										'3' => '',
// 										'4' => '',
// 										'5' => 'dialog',
// 										'6' => '专家分类',
// 										'7' => '450',
// 										'8' => '230',
// 								),
// 						),
// 						'1' => array(
// 								'0' => array(
// 										'0' => '#status#',
// 								),
// 						),
// 				),
// 		),
		7=> array(
				'name' => 'action',
				'showname' => '操作',
				'shows' => '1',
				'widths' => '',
				'sorts' => '0',
				'models' => '',
				'sortname' => 'status',
				'sortnum' => '20',
				'issearch' => '',
				'searchField' => '',
				'table' => '',
				'field' => '',
				'conditions' => '',
				'type' => '',
				'isallsearch' => '',
				'searchsortnum' => '',
				'status' => '1',
				'extention_html_end' => array(
						'0' => ' ',
				),
				'func' => array(
						'0' => array(
								'0' => 'getOperateStatus',
						),
						'1' => array(
								'0' => 'getStatus',
						),
				),
				'funcdata' => array(
						'0' => array(
								'0' => array(
										'0' => '#createid#',
										'1' => '#auditState#',
										'2' => 'id/#id#',
										'3' => '',
										'4' => '',
										'5' => 'dialog',
										'6' => '专家信息',
										'7' => '600',
										'8' => '250',
								),
						),
						'1' => array(
								'0' => array(
										'0' => '#status#',
								),
						),
				),
		),
);

?>