<?php 
return array(
	'orderno' => array(
		'name' => 'orderno',
		'showname' => '编码',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'orderno',
		'sortnum' => '1',
		'searchField' => '',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '0',
		'status' => '1',
		'rules' => '0',
		'message' => '0',
		'helpvalue' => '',
	),
	'id' => array(
		'name' => 'id',
		'showname' => '编号',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'id',
		'sortnum' => '2',
		'searchField' => '',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '0',
		'status' => '1',
		'rules' => '0',
		'message' => '0',
		'helpvalue' => '',
	),
	'name' => array(
		'name' => 'name',
		'showname' => '部门名称',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'name',
		'sortnum' => '3',
		'searchField' => 'mis_system_department.name',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '1',
		'status' => '1',
		'rules' => '0',
		'message' => '0',
		'helpvalue' => '',
	),
	'siteid' => array(
		'name' => 'siteid',
		'showname' => '所属区域',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'siteid ',
		'sortnum' => '4',
		'searchField' => 'mis_system_department.siteid',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '0',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'mis_sales_site',
				),
			),
		),
		'status' => '1',
		'rules' => '0',
		'message' => '0',
		'helpvalue' => '',
	),
	'parentid' => array(
		'name' => 'parentid',
		'showname' => '上级部门',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'parentid ',
		'sortnum' => '5',
		'searchField' => 'mis_system_department.parentid',
		'table' => 'mis_system_department',
		'field' => 'id',
		'conditions' => '',
		'type' => 'db',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '2',
		'status' => '1',
		'rules' => '0',
		'message' => '0',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'mis_system_department',
				),
			),
		),
		'helpvalue' => '',
	),
	'manageid' => array(
		'name' => 'manageid',
		'showname' => '部门管理员',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'manageid ',
		'sortnum' => '6',
		'searchField' => 'mis_system_department.manageid',
		'table' => 'mis_hr_personnel_person_info',
		'field' => 'id',
		'conditions' => '',
		'type' => 'db',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '3',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'user',
				),
			),
		),
		'status' => '1',
		'rules' => '0',
		'message' => '0',
		'helpvalue' => '',
	),
	'quyu' => array(
			'name' => 'quyu',
			'showname' => '管理区域',
			'shows' => '1',
			'widths' => '',
			'sorts' => '0',
			'models' => '',
			'sortname' => 'quyu ',
			'sortnum' => '7',
			'searchField' => 'mis_system_department.quyu',
			'table' => 'mis_auto_jcztc',
			'field' => 'id',
			'conditions' => '',
			'type' => 'db',
			'issearch' => '1',
			'isallsearch' => '1',
			'searchsortnum' => '3',
			'func' => array(
					'0' => array(
							'0' => 'getFieldBy',
					),
			),
			'funcdata' => array(
					'0' => array(
							'0' => array(
									'0' => '###',
									'1' => 'orderno',
									'2' => 'name',
									'3' => 'mis_auto_jcztc',
							),
					),
			),
			'status' => '1',
			'rules' => '0',
			'message' => '0',
			'helpvalue' => '',
	),
	'action' => array(
		'name' => 'action',
		'showname' => '状态',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'status',
		'func' => array(
			'0' => array(
				'0' => 'getStatus',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '#status#',
				),
			),
		),
		'sortnum' => '8',
		'searchField' => '',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '0',
		'status' => '1',
		'rules' => '0',
		'message' => '0',
		'helpvalue' => '',
	),
);

?>