<?php 
return array(
	'0' => array(
		'name' => 'id',
		'showname' => '序号',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'id',
		'sortnum' => '1',
		'status' => '1',
		'isexport' => '1',
		'searchField' => '',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '0',
		'helpvalue' => '',
		'rules' => '0',
		'message' => '0',
	),
	'1' => array(
		'name' => 'title',
		'showname' => '标题',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'title',
		'sortnum' => '2',
		'status' => '1',
		'isexport' => '1',
		'searchField' => 'mis_oa_items.title',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '0',
		'helpvalue' => '',
		'rules' => '0',
		'message' => '0',
	),
	'2' => array(
		'name' => 'secretlevel',
		'showname' => '保密程度',
		'shows' => '1',
		'widths' => '100',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'secretlevel',
		'sortnum' => '3',
		'status' => '1',
		'isexport' => '1',
		'searchField' => 'mis_oa_items.secretlevel',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'select|secretlevel',
		'issearch' => '1',
		'isallsearch' => '0',
		'searchsortnum' => '1',
		'helpvalue' => '',
		'rules' => '0',
		'func' => array(
			'0' => array(
				'0' => 'getSelectByName',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => 'secretlevel',
					'1' => '###',
				),
			),
		),
		'message' => '0',
	),
	'3' => array(
		'name' => 'urgentlevel',
		'showname' => '紧急程度',
		'shows' => '1',
		'widths' => '100',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'urgentlevel',
		'sortnum' => '4',
		'status' => '1',
		'isexport' => '1',
		'searchField' => 'mis_oa_items.urgentlevel',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'select|urgentlevel',
		'issearch' => '1',
		'isallsearch' => '0',
		'searchsortnum' => '2',
		'helpvalue' => '',
		'rules' => '0',
		'func' => array(
			'0' => array(
				'0' => 'getSelectByName',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => 'urgentlevel',
					'1' => '###',
				),
			),
		),
		'message' => '0',
	),
	'4' => array(
		'name' => 'flowid',
		'showname' => '流程选择',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'flowid',
		'sortnum' => '5',
		'status' => '1',
		'isexport' => '1',
		'searchField' => 'mis_oa_items.flowid',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '3',
		'helpvalue' => '',
		'rules' => '0',
		'message' => '0',
	),
	'5' => array(
		'name' => 'relevanceitems',
		'showname' => '关联事项',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'relevanceitems',
		'sortnum' => '6',
		'status' => '1',
		'isexport' => '1',
		'searchField' => 'mis_oa_items.relevanceitems',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '4',
		'helpvalue' => '',
		'rules' => '0',
		'message' => '0',
	),
	'6' => array(
		'name' => 'content',
		'showname' => '内容',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'content',
		'sortnum' => '7',
		'status' => '1',
		'isexport' => '1',
		'searchField' => 'mis_oa_items.content',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '5',
		'helpvalue' => '',
		'rules' => '0',
		'message' => '0',
	),
	'7' => array(
		'name' => 'description',
		'showname' => '附言',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'description',
		'sortnum' => '8',
		'status' => '1',
		'isexport' => '1',
		'searchField' => 'mis_oa_items.description',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '6',
		'helpvalue' => '',
		'rules' => '0',
		'message' => '0',
	),
	'8' => array(
		'name' => 'updatetime',
		'showname' => '最后回复时间',
		'shows' => '1',
		'widths' => '120',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'updatetime',
		'sortnum' => '9',
		'status' => '1',
		'isexport' => '1',
		'searchField' => 'mis_oa_items.updatetime',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'time',
		'issearch' => '1',
		'isallsearch' => '0',
		'searchsortnum' => '8',
		'helpvalue' => '',
		'rules' => '0',
		'message' => '0',
		'func' => array(
			'0' => array(
				'0' => 'transTime',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'Y-m-d H:i',
				),
			),
		),
	),
);

?>