<?php 
return array(
	'0' => array(
		'name' => 'id',
		'showname' => 'ID',
		'shows' => '0',
		'widths' => '30',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'id',
		'sortnum' => '1',
		'issearch' => '0',
		'searchField' => '',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'isallsearch' => '0',
		'searchsortnum' => '0',
		'status' => '1',
		'rules' => '0',
		'isexport' => '0',
		'helpvalue' => '',
	),
	'1' => array(
		'name' => 'orderno',
		'showname' => '员工编号',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'orderno',
		'sortnum' => '2',
		'issearch' => '1',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_person_info.orderno',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '1',
		'searchsortnum' => '1',
		'status' => '1',
		'rules' => '0',
		'helpvalue' => '',
	),
	'14' => array(
		'name' => 'itemid',
		'showname' => '档案号',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'itemid',
		'sortnum' => '3',
		'issearch' => '1',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_person_info.itemid',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '1',
		'searchsortnum' => '2',
		'status' => '1',
		'rules' => '0',
		'helpvalue' => '',
	),
	'5' => array(
		'name' => 'education',
		'showname' => '学历',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'education',
		'sortnum' => '4',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'mis_hr_typeinfo',
				),
			),
		),
		'issearch' => '1',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_person_info.education',
		'table' => 'mis_hr_typeinfo',
		'field' => 'id',
		'conditions' => 'typeid=2,pid=44',
		'type' => 'group',
		'isallsearch' => '0',
		'searchsortnum' => '3',
		'status' => '1',
		'rules' => '0',
		'helpvalue' => '',
	),
	'2' => array(
		'name' => 'name',
		'showname' => '姓名',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'name',
		'sortnum' => '5',
		'issearch' => '1',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_person_info.name',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '1',
		'searchsortnum' => '4',
		'status' => '1',
		'rules' => '0',
		'helpvalue' => '',
	),
	'3' => array(
		'name' => 'sex',
		'showname' => '性别',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'sex',
		'sortnum' => '6',
		'func' => array(
			'0' => array(
				'0' => 'getS',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
				),
			),
		),
		'issearch' => '1',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_person_info.sex',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'radio|sex',
		'isallsearch' => '0',
		'searchsortnum' => '5',
		'status' => '1',
		'rules' => '0',
		'helpvalue' => '',
	),
	'4' => array(
		'name' => 'age',
		'showname' => '年龄',
		'shows' => '1',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'age',
		'sortnum' => '7',
		'issearch' => '0',
		'searchField' => 'mis_hr_personnel_person_info.age',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'isallsearch' => '0',
		'searchsortnum' => '6',
		'status' => '1',
		'widths' => '',
		'func' => array(
			'0' => array(
				'0' => 'getAgeByToCarIdForList',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '#chinaid#',
				),
			),
		),
		'rules' => '0',
		'isexport' => '0',
		'helpvalue' => '',
	),
	'6' => array(
		'name' => 'deptid',
		'showname' => '部门',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'deptid',
		'sortnum' => '8',
		'issearch' => '1',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_person_info.deptid',
		'table' => 'mis_system_department',
		'field' => 'id',
		'conditions' => '',
		'type' => 'db',
		'isallsearch' => '1',
		'searchsortnum' => '7',
		'status' => '1',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'MisSystemDepartment',
				),
			),
		),
		'rules' => '1',
		'helpvalue' => '',
	),
	'7' => array(
		'name' => 'dutylevelid',
		'showname' => '职级',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'dutylevelid',
		'sortnum' => '9',
		'issearch' => '1',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_person_info.dutylevelid',
		'table' => 'duty',
		'field' => 'id',
		'conditions' => '',
		'isallsearch' => '1',
		'searchsortnum' => '8',
		'status' => '1',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'mis_system_duty',
				),
			),
		),
		'type' => 'db',
		'rules' => '0',
		'helpvalue' => '',
	),
	'8' => array(
		'name' => 'worktype',
		'showname' => '岗位',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'worktype',
		'sortnum' => '10',
		'issearch' => '1',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_person_info.worktype',
		'table' => 'mis_hr_job_info',
		'field' => 'id',
		'conditions' => '',
		'type' => 'group',
		'isallsearch' => '1',
		'searchsortnum' => '9',
		'status' => '1',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
				'1' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '#employeeid#',
					'1' => 'id',
					'2' => 'worktype',
					'3' => 'mis_hr_personnel_person_info',
				),
				'1' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'mis_hr_job_info',
				),
			),
		),
		'rules' => '0',
		'helpvalue' => '',
	),
	'9' => array(
		'name' => 'leavedate',
		'showname' => '离职时间',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'leavedate',
		'sortnum' => '11',
		'func' => array(
			'0' => array(
				'0' => 'transTime',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
				),
			),
		),
		'issearch' => '1',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_person_info.leavedate',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'time',
		'isallsearch' => '0',
		'searchsortnum' => '10',
		'status' => '1',
		'rules' => '0',
		'helpvalue' => '',
	),
	'10' => array(
		'name' => 'chinaid',
		'showname' => '身份证号',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'chinaid',
		'sortnum' => '12',
		'issearch' => '1',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_person_info.chinaid',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '1',
		'searchsortnum' => '11',
		'status' => '1',
		'rules' => '0',
		'helpvalue' => '',
	),
	'11' => array(
		'name' => 'remark',
		'showname' => '备注',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'chinaid',
		'sortnum' => '13',
		'issearch' => '0',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_person_info.chinaid',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '12',
		'status' => '1',
		'rules' => '0',
		'helpvalue' => '',
	),
	'20' => array(
		'name' => 'accounttype',
		'showname' => '户口性质',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'accounttype',
		'sortnum' => '14',
		'issearch' => '1',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_person_info.accounttype',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'select|accounttype',
		'isallsearch' => '0',
		'searchsortnum' => '13',
		'status' => '1',
		'rules' => '0',
		'func' => array(
			'0' => array(
				'0' => 'getSelectByName',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => 'accounttype',
					'1' => '###',
				),
			),
		),
		'helpvalue' => '',
	),
	'19' => array(
		'name' => 'agreetypeid',
		'showname' => '合约性质',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'agreetypeid',
		'sortnum' => '15',
		'issearch' => '1',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_person_info.agreetypeid',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'select|agreetypeid',
		'isallsearch' => '0',
		'searchsortnum' => '14',
		'status' => '1',
		'rules' => '0',
		'func' => array(
			'0' => array(
				'0' => 'getSelectByName',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => 'agreetypeid',
					'1' => '###',
				),
			),
		),
		'helpvalue' => '',
	),
	'18' => array(
		'name' => 'phone',
		'showname' => '联系电话',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'phone',
		'sortnum' => '16',
		'issearch' => '1',
		'searchField' => 'mis_hr_personnel_person_info.phone',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '1',
		'searchsortnum' => '15',
		'status' => '1',
		'rules' => '0',
		'isexport' => '1',
		'helpvalue' => '',
	),
	'12' => array(
		'name' => 'leavereason',
		'showname' => '离职原因',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'leavereason',
		'sortnum' => '17',
		'issearch' => '0',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_person_info.leavereason',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '13',
		'status' => '1',
		'func' => array(
			'0' => array(
				'0' => 'showhtml',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '<a href="__APP__/MisHrPersonnelLeave/lookupviewresult/id/#id#" title="查看离职原因" rel="MisHrLeaveEmployee_view" target="dialog" mask="true" height="316" width="635"><span style="color:red">查看</span></a>',
				),
			),
		),
		'rules' => '0',
		'helpvalue' => '',
	),
	'13' => array(
		'name' => 'action',
		'showname' => '状态',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'status',
		'sortnum' => '19',
		'issearch' => '0',
		'searchField' => '',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'isallsearch' => '0',
		'searchsortnum' => '0',
		'status' => '1',
		'func' => array(
			'1' => array(
				'0' => 'getStatus',
			),
		),
		'funcdata' => array(
			'1' => array(
				'0' => array(
					'0' => '#status#',
				),
			),
		),
		'rules' => '0',
		'isexport' => '0',
		'helpvalue' => '',
	),
	'46' => array(
		'name' => 'workage',
		'showname' => '工龄',
		'shows' => '1',
		'widths' => '',
		'sorts' => '1',
		'models' => '',
		'sortname' => 'workage',
		'sortnum' => '18',
		'issearch' => '0',
		'isexport' => '0',
		'searchField' => 'mis_hr_personnel_person_info.workage',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'isallsearch' => '0',
		'searchsortnum' => '2',
		'status' => '1',
		'rules' => '0',
		'helpvalue' => '',
		
	),
);

?>