<?php 
return array(
	'0' => array(
		'name' => 'leaveid',
		'showname' => 'ID',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'leaveid',
		'sortnum' => '1',
		'issearch' => '0',
		'isexport' => '1',
		'searchField' => 'mis_hr_leave_employee.id',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'isallsearch' => '0',
		'searchsortnum' => '0',
		'status' => '1',
		'rules' => '0',
	),
	'1' => array(
		'name' => 'leaveorderno',
		'showname' => '离职编号',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'leaveorderno',
		'sortnum' => '2',
		'issearch' => '1',
		'isexport' => '1',
		'searchField' => 'mis_hr_leave_employee.orderno',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '1',
		'searchsortnum' => '2',
		'status' => '1',
		'rules' => '0',
	),
	'3' => array(
		'name' => 'name',
		'showname' => '员工姓名',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'name',
		'sortnum' => '4',
		'issearch' => '1',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_person_info.name',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '1',
		'searchsortnum' => '4',
		'func' => array(
			'0' => array(
				'0' => 'getSeparatedValue',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '#employeeid#',
					'1' => 'id',
					'2' => 'name',
					'3' => 'mis_hr_personnel_person_info',
				),
			),
		),
		'status' => '1',
		'rules' => '0',
	),
	'4' => array(
		'name' => 'deptid',
		'showname' => '部门',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'deptid',
		'sortnum' => '5',
		'issearch' => '1',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_person_info.deptid',
		'table' => 'mis_system_department',
		'field' => 'id',
		'conditions' => '',
		'type' => 'db',
		'isallsearch' => '0',
		'searchsortnum' => '5',
		'0' => array(
			'0' => array(
				'0' => '###',
				'1' => 'id',
				'2' => 'name',
				'3' => 'mis_system_department',
			),
		),
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'mis_system_department',
				),
			),
		),
		'status' => '1',
		'rules' => '0',
	),
	'5' => array(
		'name' => 'dutyname',
		'showname' => '职务',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'dutyname',
		'sortnum' => '6',
		'issearch' => '1',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_person_info.dutylevelid',
		'table' => 'duty',
		'field' => 'id',
		'conditions' => '',
		'type' => 'db',
		'isallsearch' => '0',
		'searchsortnum' => '6',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
				'1' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '#employeeid#',
					'1' => 'id',
					'2' => 'dutylevelid',
					'3' => 'mis_hr_personnel_person_info',
				),
				'1' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'duty',
				),
			),
		),
		'status' => '1',
		'rules' => '1',
	),
	'6' => array(
		'name' => 'createtime',
		'showname' => '申请日期',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'createtime',
		'sortnum' => '7',
		'issearch' => '1',
		'isexport' => '1',
		'searchField' => 'mis_hr_leave_employee.applicationdate',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'time',
		'isallsearch' => '0',
		'searchsortnum' => '7',
		'func' => array(
			'0' => array(
				'0' => 'transTime',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
				),
			),
		),
		'status' => '1',
		'rules' => '0',
	),
	'7' => array(
		'name' => 'indate',
		'showname' => '入职日期',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'indate',
		'sortnum' => '8',
		'issearch' => '1',
		'isexport' => '1',
		'searchField' => 'mis_hr_personnel_person_info.indate',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'time',
		'isallsearch' => '0',
		'searchsortnum' => '8',
		'func' => array(
			'0' => array(
				'0' => 'transTime',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
				),
			),
		),
		'status' => '1',
		'rules' => '0',
	),
	'8' => array(
		'name' => 'leavedate',
		'showname' => '离职日期',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'mis_hr_leave_employee.leavedate',
		'sortnum' => '9',
		'func' => array(
			'0' => array(
				'0' => 'transTime',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
				),
			),
		),
		'issearch' => '1',
		'isexport' => '1',
		'searchField' => 'mis_hr_leave_employee.preliminaryexitdate',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'time',
		'isallsearch' => '0',
		'searchsortnum' => '9',
		'status' => '1',
		'rules' => '0',
	),
	'9' => array(
		'name' => 'leavetype',
		'showname' => '离职类型',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'leavetype',
		'sortnum' => '10',
		'issearch' => '0',
		'isexport' => '1',
		'searchField' => 'mis_hr_leave_employee.leavetype',
		'table' => 'mis_hr_typeinfo',
		'field' => 'id',
		'conditions' => 'status=1 and pid=18 and typeid=2',
		'type' => 'radio|leavetype',
		'isallsearch' => '0',
		'searchsortnum' => '10',
		'func' => array(
			'0' => array(
				'0' => 'excelTplselected',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => '1:正式自离,2:试用自离,3:代办正式,4:代办试用',
				),
			),
		),
		'status' => '1',
		'rules' => '0',
	),
	'18' => array(
		'name' => 'forleavetype',
		'showname' => '离职类别',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'forleavetype',
		'sortnum' => '11',
		'issearch' => '1',
		'isexport' => '1',
		'searchField' => 'mis_hr_leave_employee.forleavetype',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'select|forleavetype',
		'isallsearch' => '1',
		'searchsortnum' => '11',
		'status' => '1',
		'rules' => '0',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'mis_hr_typeinfo',
				),
			),
		),
	),
	'10' => array(
		'name' => 'leavereason',
		'showname' => '离职原因',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'leavereason',
		'sortnum' => '12',
		'issearch' => '1',
		'isexport' => '1',
		'searchField' => 'mis_hr_leave_employee.leavereason',
		'table' => 'mis_hr_typeinfo',
		'field' => 'id',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '12',
		'conditions' => '',
		'status' => '1',
		'rules' => '0',
	),
	'11' => array(
		'name' => 'remark',
		'showname' => '备注',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'remark',
		'sortnum' => '13',
		'issearch' => '0',
		'searchField' => 'mis_hr_leave_employee.remark',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '13',
		'status' => '1',
		'rules' => '0',
		'isexport' => '0',
	),
	'12' => array(
		'name' => 'createtime',
		'showname' => '创建时间',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'createtime',
		'sortnum' => '14',
		'func' => array(
			'0' => array(
				'0' => 'transTime',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
				),
			),
		),
		'issearch' => '0',
		'searchField' => 'mis_hr_leave_employee.createtime',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '14',
		'status' => '1',
		'rules' => '0',
		'isexport' => '0',
	),
	'13' => array(
		'name' => 'createid',
		'showname' => '创建人',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'createid',
		'sortnum' => '15',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'user',
				),
			),
		),
		'issearch' => '0',
		'searchField' => 'mis_hr_leave_employee.createid',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '15',
		'status' => '1',
		'rules' => '0',
		'isexport' => '0',
	),
	'14' => array(
		'name' => 'updatetime',
		'showname' => '修改时间',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'updatetime',
		'sortnum' => '16',
		'func' => array(
			'0' => array(
				'0' => 'transTime',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
				),
			),
		),
		'issearch' => '0',
		'searchField' => 'mis_hr_leave_employee.updatetime',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '16',
		'status' => '1',
		'rules' => '0',
		'isexport' => '0',
	),
	'15' => array(
		'name' => 'updateid',
		'showname' => '修改人',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'updateid',
		'sortnum' => '17',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'user',
				),
			),
		),
		'issearch' => '0',
		'searchField' => 'mis_hr_leave_employee.updateid',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '17',
		'status' => '1',
		'rules' => '0',
		'isexport' => '0',
	),
	'16' => array(
		'name' => 'auditState',
		'showname' => '审核状态',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'auditState',
		'func' => array(
			'0' => array(
				'0' => 'getAuditState',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => '#id#',
					'2' => '#ptmptid#',
				),
			),
		),
		'sortnum' => '18',
		'issearch' => '0',
		'isexport' => '1',
		'searchField' => 'mis_hr_leave_employee.auditState',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '0',
		'searchsortnum' => '18',
		'status' => '1',
		'rules' => '0',
	),
	'17' => array(
		'name' => 'action',
		'showname' => '操作',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'status',
		'sortnum' => '19',
		'issearch' => '0',
		'searchField' => '',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'isallsearch' => '0',
		'searchsortnum' => '0',
		'status' => '1',
		'extention_html_end' => array(
			'0' => ' ',
		),
		'func' => array(
			'0' => array(
				'0' => 'getOperateStatus',
			),
			'1' => array(
				'0' => 'getStatus',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '#createid#',
					'1' => '#auditState#',
					'2' => 'id/#leaveid#',
					'3' => '',
					'4' => '',
					'5' => 'dialog',
					'6' => '员工离职',
					'7' => '688',
					'8' => '500',
				),
			),
			'1' => array(
				'0' => array(
					'0' => '#status#',
				),
			),
		),
		'rules' => '0',
		'isexport' => '0',
	),
);

?>