<?php 
return array(
	'0' => array(
		'name' => 'name',
		'showname' => '名称',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'name',
		'sortnum' => '1',
		'searchField' => 'mis_auto_hcfwc.name',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '0',
	),
	'1' => array(
		'name' => 'supcategory',
		'showname' => '上级工作流类型',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'supcategory',
		'sortnum' => '2',
		'searchField' => 'mis_auto_hcfwc.supcategory',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '1',
	),
	'2' => array(
		'name' => 'category',
		'showname' => '子级工作流类型',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'category',
		'sortnum' => '3',
		'searchField' => 'mis_auto_hcfwc.category',
		'conditions' => 'aa',
		'type' => 'lookup',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '2',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'a',
					'2' => NULL,
					'3' => 'a',
				),
			),
		),
		'table' => 'a',
		'field' => '',
	),
	'3' => array(
		'name' => 'modelname',
		'showname' => '对应模板',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'modelname',
		'sortnum' => '4',
		'searchField' => 'mis_auto_hcfwc.modelname',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '3',
	),
	'4' => array(
		'name' => 'parentid',
		'showname' => '父任务id',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'parentid',
		'sortnum' => '5',
		'searchField' => 'mis_auto_hcfwc.parentid',
		'conditions' => 'aa',
		'type' => 'lookup',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '4',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'a',
					'2' => NULL,
					'3' => 'a',
				),
			),
		),
		'table' => 'a',
		'field' => '',
	),
	'5' => array(
		'name' => 'summary',
		'showname' => '是否为子任务',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'summary',
		'sortnum' => '6',
		'searchField' => 'mis_auto_hcfwc.summary',
		'conditions' => '',
		'type' => 'radio',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '5',
		'func' => array(
			'0' => array(
				'0' => 'getSelectlistValue',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'debit',
				),
			),
		),
	),
	'6' => array(
		'name' => 'days',
		'showname' => '几个工作日',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'days',
		'sortnum' => '7',
		'searchField' => 'mis_auto_hcfwc.days',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '6',
	),
	'7' => array(
		'name' => 'begintime',
		'showname' => '计划开始时间',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'begintime',
		'sortnum' => '8',
		'searchField' => 'mis_auto_hcfwc.begintime',
		'conditions' => '',
		'type' => 'time',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '7',
		'func' => array(
			'0' => array(
				'0' => 'transtime',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
				),
			),
		),
	),
	'8' => array(
		'name' => 'endtime',
		'showname' => '计划结束时间',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'endtime',
		'sortnum' => '9',
		'searchField' => 'mis_auto_hcfwc.endtime',
		'conditions' => '',
		'type' => 'time',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '8',
		'func' => array(
			'0' => array(
				'0' => 'transtime',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
				),
			),
		),
	),
	'9' => array(
		'name' => 'outlinenumber',
		'showname' => '大纲数字',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'outlinenumber',
		'sortnum' => '10',
		'searchField' => 'mis_auto_hcfwc.outlinenumber',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '9',
	),
	'10' => array(
		'name' => 'outlinelevel',
		'showname' => '大纲级别',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'outlinelevel',
		'sortnum' => '11',
		'searchField' => 'mis_auto_hcfwc.outlinelevel',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '10',
	),
	'11' => array(
		'name' => 'readyonly',
		'showname' => '只读',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'readyonly',
		'sortnum' => '12',
		'searchField' => 'mis_auto_hcfwc.readyonly',
		'conditions' => '',
		'type' => 'radio',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '11',
		'func' => array(
			'0' => array(
				'0' => 'getSelectlistValue',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'debit',
				),
			),
		),
	),
	'12' => array(
		'name' => 'percentcomplete',
		'showname' => '完成百分比',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'percentcomplete',
		'sortnum' => '13',
		'searchField' => 'mis_auto_hcfwc.percentcomplete',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '12',
	),
	'13' => array(
		'name' => 'notes',
		'showname' => '任务备注',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'notes',
		'sortnum' => '14',
		'searchField' => 'mis_auto_hcfwc.notes',
		'conditions' => '',
		'type' => 'textarea',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '13',
	),
	'14' => array(
		'name' => 'constrainttype',
		'showname' => '任务的限制类型',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'constrainttype',
		'sortnum' => '15',
		'searchField' => 'mis_auto_hcfwc.constrainttype',
		'conditions' => '',
		'type' => 'select',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '14',
		'func' => array(
			'0' => array(
				'0' => 'getSelectlistValue',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'debit',
				),
			),
		),
	),
	'15' => array(
		'name' => 'hyperlink',
		'showname' => '超级链接的文本',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'hyperlink',
		'sortnum' => '16',
		'searchField' => 'mis_auto_hcfwc.hyperlink',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '15',
	),
	'16' => array(
		'name' => 'hyperlinkurl',
		'showname' => '超级链接的URL',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'hyperlinkurl',
		'sortnum' => '17',
		'searchField' => 'mis_auto_hcfwc.hyperlinkurl',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '16',
	),
	'17' => array(
		'name' => 'classname',
		'showname' => '任务的显示样式',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'classname',
		'sortnum' => '18',
		'searchField' => 'mis_auto_hcfwc.classname',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '17',
	),
	'18' => array(
		'name' => 'critical',
		'showname' => '是否是关键任务',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'critical',
		'sortnum' => '19',
		'searchField' => 'mis_auto_hcfwc.critical',
		'conditions' => '',
		'type' => 'radio',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '18',
		'func' => array(
			'0' => array(
				'0' => 'getSelectlistValue',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'debit',
				),
			),
		),
	),
	'19' => array(
		'name' => 'custtypeid',
		'showname' => '客户主体编码',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'custtypeid',
		'sortnum' => '20',
		'searchField' => 'mis_auto_hcfwc.custtypeid',
		'conditions' => 'aa',
		'type' => 'lookup',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '19',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'a',
					'2' => NULL,
					'3' => 'a',
				),
			),
		),
		'table' => 'a',
		'field' => '',
	),
	'20' => array(
		'name' => 'hyid',
		'showname' => '行业编码',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'hyid',
		'sortnum' => '21',
		'searchField' => 'mis_auto_hcfwc.hyid',
		'conditions' => 'aa',
		'type' => 'lookup',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '20',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'a',
					'2' => NULL,
					'3' => 'a',
				),
			),
		),
		'table' => 'a',
		'field' => '',
	),
	'21' => array(
		'name' => 'cylid',
		'showname' => '产业链编码',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'cylid',
		'sortnum' => '22',
		'searchField' => 'mis_auto_hcfwc.cylid',
		'conditions' => 'aa',
		'type' => 'lookup',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '21',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'a',
					'2' => NULL,
					'3' => 'a',
				),
			),
		),
		'table' => 'a',
		'field' => '',
	),
	'22' => array(
		'name' => 'formtype',
		'showname' => '任务类型',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'formtype',
		'sortnum' => '23',
		'searchField' => 'mis_auto_hcfwc.formtype',
		'conditions' => '',
		'type' => 'radio',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '22',
		'func' => array(
			'0' => array(
				'0' => 'getSelectlistValue',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'debit',
				),
			),
		),
	),
	'23' => array(
		'name' => 'yzid',
		'showname' => '印章编码',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'yzid',
		'sortnum' => '24',
		'searchField' => 'mis_auto_hcfwc.yzid',
		'conditions' => 'aa',
		'type' => 'lookup',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '23',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'a',
					'2' => NULL,
					'3' => 'a',
				),
			),
		),
		'table' => 'a',
		'field' => '',
	),
	'24' => array(
		'name' => 'action',
		'showname' => '操作',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'status',
		'func' => array(
			'0' => array(
				'0' => 'showStatus',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '#status#',
					'1' => '#id#',
				),
			),
		),
		'sortnum' => '25',
	),
);

?>