<?php 
return array(
	'id' => array(
		'name' => 'id',
		'showname' => 'ID',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'id',
		'sortnum' => '1',
		'issearch' => '1',
		'searchField' => 'mis_system_data_access_sub.id',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '1',
		'searchsortnum' => '3',
		'status' => '1',
		'rules' => '0',
		'message' => '0',
	),
	'accessfields' => array(
		'name' => 'accessfields',
		'showname' => '授权字段',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'accessfields',
		'sortnum' => '2',
		'issearch' => '1',
		'searchField' => 'mis_system_data_access_sub.accessfields',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '1',
		'searchsortnum' => '3',
		'status' => '1',
		'rules' => '0',
		'message' => '0',
	),
	'accesstype' => array(
		'name' => 'accesstype',
		'showname' => '授权类型',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'accesstype',
		'sortnum' => '4',
		'issearch' => '1',
		'searchField' => 'mis_system_data_access_sub.accesstype',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '1',
		'searchsortnum' => '3',
		'status' => '1',
		'rules' => '0',
		'message' => '0',
		'func' => array(
				'0' => array(
						'0' => 'excelTplselected',
				),
		),
		'funcdata' => array(
				'0' => array(
						'0' => array(
								'0' => '###',
								'1' => '1:直接授权,2:分组授权',
						),
				),
		),
	),
	'fieldtitle' => array(
		'name' => 'fieldtitle',
		'showname' => '字段名称',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'fieldtitle',
		'sortnum' => '5',
		'issearch' => '1',
		'searchField' => 'mis_system_data_access_sub.fieldtitle',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '1',
		'searchsortnum' => '3',
		'status' => '1',
		'rules' => '0',
		'message' => '0',
	),
	'type' => array(
		'name' => 'type',
		'showname' => '授权类型',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'fieldtitle',
		'sortnum' => '5',
		'issearch' => '1',
		'searchField' => 'mis_system_data_access_sub.type',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => 'text',
		'isallsearch' => '1',
		'searchsortnum' => '3',
		'status' => '1',
		'rules' => '0',
		'message' => '0',
		
	),
	'startstatus'=>array(
		'name' => 'action',
		'showname' => '状态',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'mis_system_data_access_sub.startstatus',
		'sortnum' => '16',
		'issearch' => '',
		'searchField' => '',
		'table' => '',
		'field' => '',
		'conditions' => '',
		'type' => '',
		'isallsearch' => '',
		'searchsortnum' => '',
		'status' => '1',
		'extention_html_end' => array(
				'0' => ' ',
		),
		'func' => array(
				'0' => array(
						'0' => 'getStatus',
				),
		),
		'funcdata' => array(
				'0' => array(
						'0' => array(
								'0' => '#startstatus#',
						),
				),
		),
		'helpvalue' => '',
	),
);

?>